import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { AuthContext } from "@/providers/auth-provider";
import { LanguageProvider } from "@/providers/language-provider-component";
import IncidentsPage from "./incidents-page";

const { api, searchPatients, printIncidentReport } = vi.hoisted(() => ({ api: { createIncident: vi.fn(), fetchIncident: vi.fn(), fetchIncidentEquipment: vi.fn(), fetchIncidents: vi.fn(), listIncidentAttachments: vi.fn(), reviewIncident: vi.fn(), uploadIncidentAttachment: vi.fn() }, searchPatients: vi.fn(), printIncidentReport: vi.fn() }));
vi.mock("@/lib/api/incidents", async () => ({ ...(await vi.importActual<typeof import("@/lib/api/incidents")>("@/lib/api/incidents")), ...api }));
vi.mock("@/lib/api/patients", () => ({ searchPatients: (...args: unknown[]) => searchPatients(...args) }));
vi.mock("@/lib/incident-printing", () => ({ printIncidentReport: (...args: unknown[]) => printIncidentReport(...args) }));

const equipmentIncident = { id: 7, incidentNumber: "INC-000007", incident_type: "equipment" as const, status: "submitted" as const, occurred_at: "2026-08-26T21:30:00.000Z", created_at: "2026-08-26T22:00:00.000Z", description: "Long equipment description", immediate_action: null, review_notes: null, reporter_name: "Reporter One", equipment_name: "MRI Scanner A", equipment_type: "MRI", location: "Room A", equipment_condition: "operational", vendor_contacted: true, vendor_contact_person: "Vendor", vendor_reference: "T-1", patient_arabic_name: null, patient_english_name: null, mrn: null, clinical_category: null, harm_level: null };
const clinicalIncident = { ...equipmentIncident, id: 8, incidentNumber: "INC-000008", incident_type: "clinical_workflow" as const, equipment_name: null, patient_arabic_name: "مريض عربي", patient_english_name: "English Patient", mrn: "MRN-8", clinical_category: "wrong_exam" as const, harm_level: "no_harm" };
function renderPage(role = "supervisor", language = "en") { localStorage.setItem("rispro-language", language); return render(<LanguageProvider><AuthContext.Provider value={{ user: { id: 1, username: role, fullName: role, role: role as never }, isLoading: false, login: vi.fn(), loginWithPasskey: vi.fn(), logout: vi.fn(), reAuth: vi.fn(), changePassword: vi.fn() }}><QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } })}><IncidentsPage /></QueryClientProvider></AuthContext.Provider></LanguageProvider>); }
describe("IncidentsPage", () => {
  beforeEach(() => { vi.clearAllMocks(); api.fetchIncidents.mockResolvedValue({ incidents: [equipmentIncident, clinicalIncident] }); api.fetchIncidentEquipment.mockResolvedValue({ equipment: [{ id: 1, name: "MRI Scanner A", equipment_type: "MRI", location: "Room A" }] }); api.fetchIncident.mockResolvedValue({ incident: equipmentIncident }); api.listIncidentAttachments.mockResolvedValue({ documents: [{ id: 1, original_filename: "proof.pdf", mime_type: "application/pdf", document_type: "incident_attachment", created_at: "2026-08-26" }] }); api.createIncident.mockResolvedValue({ incident: equipmentIncident }); api.reviewIncident.mockResolvedValue({ incident: equipmentIncident }); api.uploadIncidentAttachment.mockResolvedValue({ document: {} }); searchPatients.mockResolvedValue([{ id: 22, arabicFullName: "مريض عربي", englishFullName: "English Patient", mrn: "MRN-22" }]); });
  it("renders register context, formatted local time, status, description, reporter, and LTR equipment", async () => { renderPage(); expect(await screen.findByText("INC-000007")).toBeTruthy(); expect(screen.getByText("MRI Scanner A").getAttribute("dir")).toBe("ltr"); expect(screen.getAllByText("Long equipment description").length).toBeGreaterThan(0); expect(screen.getAllByText(/Reporter: Reporter One/).length).toBeGreaterThan(0); expect(screen.getAllByText("Clinical / Workflow Incident").length).toBeGreaterThan(1); expect(screen.queryByText("2026-08-26T21:30:00.000Z")).toBeNull(); });
  it("converts local datetime to ISO and sends vendor fields only after Yes", async () => { const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "New Incident" })); const yes = screen.getByLabelText("Yes"); await user.click(yes); await user.type(screen.getByPlaceholderText("Contact person"), "Vendor"); await user.type(screen.getByPlaceholderText("Service reference / ticket"), "TICKET-9"); fireEvent.change(document.querySelector("input[name='occurredAt']")!, { target: { value: "2026-08-26T23:30" } }); await user.selectOptions(document.querySelector("select[name='equipmentId']")!, "1"); await user.type(screen.getByPlaceholderText("Description of incident"), "Equipment issue"); await user.click(screen.getByRole("button", { name: "Submit incident" })); await waitFor(() => expect(api.createIncident).toHaveBeenCalled()); expect(api.createIncident.mock.calls[0][0]).toMatchObject({ occurredAt: new Date("2026-08-26T23:30").toISOString(), vendorContacted: true, vendorContactPerson: "Vendor", vendorReference: "TICKET-9" }); });
  it("shows all clinical categories, optional patient results and clear control", async () => { const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "New Incident" })); await user.selectOptions(screen.getAllByRole("combobox")[2]!, "clinical_workflow"); expect(screen.getByRole("option", { name: "Wrong examination" })).toBeTruthy(); expect(screen.getByRole("option", { name: "Reporting issue" })).toBeTruthy(); await user.type(screen.getByPlaceholderText("Patient (optional)"), "En"); const patient = await screen.findByRole("button", { name: /English Patient.*MRN-22/ }); await user.click(patient); expect(screen.getByRole("button", { name: "Clear patient" })).toBeTruthy(); await user.click(screen.getByRole("button", { name: "Clear patient" })); });
});
