import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { tripoliDateTimeLocalToIso } from "@/lib/date-format";
import { fetchExamTypes } from "@/lib/api/catalog";
import type { ComplementaryRecallRequestPayload } from "@/lib/api/doctor-portal-reporting";
import type { ComplementaryRecallOriginalReportDependency, ComplementaryRecallQaClassification, ComplementaryRecallReasonCode, ComplementaryRecallUrgency } from "@/lib/api/complementary-recalls";
import { Button, Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, Input, Textarea } from "@/components/shared";

type Plan = "supplement_original_report" | "separate_report";
type CatalogRow = { id: number; nameEn?: string; name_en?: string; code?: string; modalityId?: number; modality_id?: number };
const label = (row: CatalogRow) => row.nameEn ?? row.name_en ?? row.code ?? `#${row.id}`;

export function ComplementaryRecallRequestDialog({ open, onClose, examLabel, submitting, error, onSubmit }: { open: boolean; onClose: () => void; examLabel: string; submitting: boolean; error?: string | null; onSubmit: (payload: ComplementaryRecallRequestPayload) => void; }) {
  const catalog = useQuery({ queryKey: ["exam-types", "additional-imaging"], queryFn: () => fetchExamTypes(), staleTime: 300_000, enabled: open });
  const [reasonCode, setReasonCode] = useState<ComplementaryRecallReasonCode | "">("");
  const [qaClassification, setQaClassification] = useState<ComplementaryRecallQaClassification | "">("");
  const [urgency, setUrgency] = useState<ComplementaryRecallUrgency>("routine");
  const [dueAt, setDueAt] = useState("");
  const [plan, setPlan] = useState<Plan | null>(null);
  const [requestedModalityId, setRequestedModalityId] = useState<number | null>(null);
  const [requestedExamTypeId, setRequestedExamTypeId] = useState<number | null>(null);
  const [dependency, setDependency] = useState<ComplementaryRecallOriginalReportDependency | null>(null);
  const [notifyOnArrival, setNotifyOnArrival] = useState(false);
  const [notifyOnImagingCompleted, setNotifyOnImagingCompleted] = useState(false);
  const [receptionInstruction, setReceptionInstruction] = useState("");
  const [technologistInstruction, setTechnologistInstruction] = useState("");
  const [showHelp, setShowHelp] = useState(false);
  useEffect(() => { if (open) { setReasonCode(""); setQaClassification(""); setUrgency("routine"); setDueAt(""); setPlan(null); setRequestedModalityId(null); setRequestedExamTypeId(null); setDependency(null); setNotifyOnArrival(false); setNotifyOnImagingCompleted(false); setReceptionInstruction(""); setTechnologistInstruction(""); setShowHelp(false); } }, [examLabel, open]);
  const modalities = (catalog.data?.modalities ?? []) as CatalogRow[];
  const examTypes = (catalog.data?.examTypes ?? []) as CatalogRow[];
  const filteredExamTypes = useMemo(() => examTypes.filter((exam) => Number(exam.modalityId ?? exam.modality_id) === requestedModalityId), [examTypes, requestedModalityId]);
  const currentDependency = plan === "supplement_original_report" ? "imaging_completed" : dependency;
  const consequence = plan === "supplement_original_report" ? "Current report: Waiting for additional imaging · Separate report: No" : plan === "separate_report" && dependency === "none" ? "Current report: Continue normally · Additional exam: Separate report" : plan === "separate_report" && dependency === "imaging_completed" ? "Current report: Waiting for additional imaging · Additional exam: Separate report" : plan === "separate_report" ? "Current report: Waiting for additional report · Additional exam: Separate report" : "Choose how the additional imaging should be reported.";
  const invalid = !reasonCode || !qaClassification || !technologistInstruction.trim() || !plan || (plan === "separate_report" && (!requestedModalityId || !requestedExamTypeId || !dependency));
  const submit = () => { if (invalid) return; onSubmit({ reasonCode: reasonCode!, qaClassification: qaClassification!, urgency, dueAt: tripoliDateTimeLocalToIso(dueAt), reportingDisposition: plan!, requestedModalityId: plan === "separate_report" ? requestedModalityId : null, requestedExamTypeId: plan === "separate_report" ? requestedExamTypeId : null, originalReportDependency: currentDependency!, notifyOnArrival, notifyOnImagingCompleted, receptionInstruction: receptionInstruction.trim() || null, technologistInstruction: technologistInstruction.trim() }); };
  return <Dialog open={open} onClose={() => !submitting && onClose()}><DialogContent maxWidth="620px" className="max-h-[calc(100dvh-1rem)] overflow-hidden"><DialogHeader><DialogTitle>Request additional imaging</DialogTitle><DialogDescription>Original exam: {examLabel}</DialogDescription></DialogHeader><div className="grid max-h-[60dvh] gap-3 overflow-y-auto pe-1">
    <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Reason<select required aria-label="Recall reason" value={reasonCode} onChange={(event) => setReasonCode(event.target.value as ComplementaryRecallReasonCode)} className="input-premium font-normal"><option value="">Select reason</option><option value="missing_sequence_phase">Missing sequence or phase</option><option value="incomplete_anatomical_coverage">Incomplete anatomical coverage</option><option value="motion_nondiagnostic_quality">Motion or nondiagnostic quality</option><option value="incorrect_protocol">Incorrect protocol</option><option value="incorrect_contrast_phase_timing">Incorrect contrast phase/timing</option><option value="additional_diagnostic_characterization">Additional diagnostic characterization</option><option value="technical_equipment_problem">Technical equipment problem</option><option value="patient_related_limitation">Patient-related limitation</option><option value="other">Other</option></select></label><label className="grid gap-1 text-sm font-medium">QA classification<select required aria-label="QA classification" value={qaClassification} onChange={(event) => setQaClassification(event.target.value as ComplementaryRecallQaClassification)} className="input-premium font-normal"><option value="">Select classification</option><option value="diagnostic_addition">Diagnostic addition</option><option value="technical_repeat">Technical repeat</option><option value="protocol_error">Protocol error</option><option value="acquisition_error">Acquisition error</option><option value="equipment_failure">Equipment failure</option><option value="patient_related_unavoidable">Patient-related unavoidable</option><option value="other">Other</option></select></label><label className="grid gap-1 text-sm font-medium">Urgency<select aria-label="Urgency" value={urgency} onChange={(event) => setUrgency(event.target.value as ComplementaryRecallUrgency)} className="input-premium font-normal"><option value="same_day">Same day</option><option value="within_24_hours">Within 24 hours</option><option value="within_72_hours">Within 72 hours</option><option value="routine">Routine</option></select></label><label className="grid gap-1 text-sm font-medium">Due date/time<Input type="datetime-local" value={dueAt} onChange={(event) => setDueAt(event.target.value)} /></label></div>
    <fieldset className="grid gap-2"><legend className="text-sm font-medium">How should this imaging be reported?</legend><button type="button" aria-pressed={plan === "supplement_original_report"} onClick={() => { setPlan("supplement_original_report"); setDependency("imaging_completed"); }} className={`rounded-lg border p-3 text-left ${plan === "supplement_original_report" ? "border-blue-500 bg-blue-50" : "border-slate-200"}`}><b>Add to this report</b><p className="mt-1 text-sm">Use the new images to complete or supplement this report. No separate reporting case will be created.</p></button><button type="button" aria-pressed={plan === "separate_report"} onClick={() => setPlan("separate_report")} className={`rounded-lg border p-3 text-left ${plan === "separate_report" ? "border-blue-500 bg-blue-50" : "border-slate-200"}`}><b>Create a separate report</b><p className="mt-1 text-sm">Book another examination with its own accession and report.</p></button></fieldset>
    {plan === "separate_report" ? <><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Requested modality<select aria-label="Requested modality" value={requestedModalityId ?? ""} onChange={(event) => { setRequestedModalityId(Number(event.target.value) || null); setRequestedExamTypeId(null); }} className="input-premium font-normal"><option value="">Select modality</option>{modalities.map((item) => <option key={item.id} value={item.id}>{label(item)}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Exam type<select aria-label="Requested exam type" value={requestedExamTypeId ?? ""} onChange={(event) => setRequestedExamTypeId(Number(event.target.value) || null)} className="input-premium font-normal" disabled={!requestedModalityId}><option value="">Select exam type</option>{filteredExamTypes.map((item) => <option key={item.id} value={item.id}>{label(item)}</option>)}</select></label></div><fieldset className="grid gap-2"><legend className="text-sm font-medium">What should happen to this report?</legend>{([["none","I can finish this report now","The new examination will be reported separately and does not block this report."],["imaging_completed","Wait for the additional images","Keep this report waiting until the new examination is completed."],["report_finalized","Wait for the additional report","Keep this report waiting until the new examination has a final report."]] as const).map(([value,title,help]) => <label key={value} className="flex gap-2 rounded border p-2 text-sm"><input type="radio" name="dependency" checked={dependency === value} onChange={() => setDependency(value)} /><span><b>{title}</b><small className="block text-slate-600">{help}</small></span></label>)}</fieldset></> : null}
    <p className="rounded-md border border-blue-200 bg-blue-50 p-2 text-sm text-blue-900" aria-live="polite">{consequence}</p><button type="button" className="w-fit text-sm font-medium text-blue-700 underline" onClick={() => setShowHelp((current) => !current)}>How does this work?</button>{showHelp ? <p className="rounded bg-slate-50 p-2 text-sm">Add to this report keeps the current report waiting for images. A separate report creates its own reportable case; you may continue now, wait for images, or wait for its final report.</p> : null}
    <fieldset className="grid gap-2"><legend className="text-sm font-medium">Updates</legend><label className="flex gap-2 text-sm"><input type="checkbox" checked={notifyOnArrival} onChange={(event) => setNotifyOnArrival(event.target.checked)} />Notify me when the patient arrives</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={notifyOnImagingCompleted} onChange={(event) => setNotifyOnImagingCompleted(event.target.checked)} />Notify me when the additional imaging is completed</label></fieldset><label className="grid gap-1 text-sm font-medium">Reception note (optional)<Textarea value={receptionInstruction} onChange={(event) => setReceptionInstruction(event.target.value)} className="min-h-20 font-normal" /></label><label className="grid gap-1 text-sm font-medium">What additional imaging is needed?<Textarea required value={technologistInstruction} onChange={(event) => setTechnologistInstruction(event.target.value)} className="min-h-24 font-normal" /></label>{error ? <p role="alert" className="text-sm text-red-700">{error}</p> : null}
  </div><DialogFooter><Button variant="secondary" onClick={onClose} disabled={submitting}>Cancel</Button><Button onClick={submit} disabled={invalid || submitting}>{submitting ? "Requesting..." : "Request additional imaging"}</Button></DialogFooter></DialogContent></Dialog>;
}
