import assert from "node:assert/strict";
import http from "node:http";
import jwt from "jsonwebtoken";
import { after, test } from "node:test";
import { pool } from "../db/pool.js";
import { env } from "../config/env.js";

process.env.JWT_SECRET ||= "request-scan-cleanup-test";
const ids: number[] = []; const users: number[] = [];
async function server() { const { createApp } = await import("../app.js"); const value = http.createServer(createApp()); await new Promise<void>((resolve) => value.listen(0, resolve)); const address = value.address() as { port:number }; return { baseUrl:`http://127.0.0.1:${address.port}`, close:() => new Promise<void>((resolve,reject) => value.close((e) => e ? reject(e) : resolve())) }; }
async function user(role:string) { const r=await pool.query<{id:number}>("insert into users(username,full_name,password_hash,role,is_active) values($1,$1,'x',$2,true) returning id", [`rs_http_${role}_${Date.now()}_${Math.random()}`,role]); const id=Number(r.rows[0]!.id); users.push(id); return { id, cookie:`${env.cookieName}=${jwt.sign({sub:id,role,username:role,fullName:role},env.jwtSecret)}` }; }
async function job() { const x=await pool.query<{id:number}>("insert into request_scan_jobs(filename,source_relative_path,mime_type,status,error_message,failure_category) values($1,$2,'image/jpeg','failed','safe failure','recognition') returning id", [`request-${Date.now()}-${Math.random()}.jpg`,`Requests\\Failed\\x-${Date.now()}.jpg`]); const id=Number(x.rows[0]!.id); ids.push(id); return id; }
async function post(baseUrl:string,path:string,cookie?:string,body?:unknown) { return fetch(`${baseUrl}${path}`,{method:"POST",headers:{"content-type":"application/json",...(cookie?{cookie}:{})},body:JSON.stringify(body??{})}); }
test("Request Scan cleanup routes enforce authenticated supervisor roles", async (t) => { try { await pool.query("select 1"); } catch { t.skip("PostgreSQL unavailable"); return; } const app=await server(); try { const id=await job(); const receptionist=await user("receptionist"); const doctor=await user("doctor"); const supervisor=await user("supervisor"); const admin=await user("super_admin"); assert.equal((await post(app.baseUrl,`/api/request-scans/${id}/dismiss`)).status,401); assert.equal((await post(app.baseUrl,`/api/request-scans/${id}/dismiss`,receptionist.cookie)).status,403); assert.equal((await post(app.baseUrl,`/api/request-scans/${id}/dismiss`,doctor.cookie)).status,403); assert.equal((await post(app.baseUrl,`/api/request-scans/${id}/dismiss`,supervisor.cookie,{reason:"ok"})).status,200); assert.equal((await post(app.baseUrl,`/api/request-scans/${id}/restore-dismissed`,doctor.cookie)).status,403); assert.equal((await post(app.baseUrl,`/api/request-scans/${id}/restore-dismissed`,admin.cookie)).status,200); assert.equal((await post(app.baseUrl,"/api/request-scans/bulk-dismiss",receptionist.cookie,{jobIds:[id]})).status,403); assert.equal((await post(app.baseUrl,"/api/request-scans/bulk-dismiss",supervisor.cookie,{jobIds:[id]})).status,200); assert.equal((await post(app.baseUrl,"/api/request-scans/bulk-retry",supervisor.cookie,{jobIds:[]})).status,400); } finally { await app.close(); } });
after(async()=>{if(ids.length)await pool.query("delete from request_scan_jobs where id=any($1::bigint[])",[ids]); if(users.length) { await pool.query("delete from audit_log where changed_by_user_id=any($1::bigint[])",[users]); await pool.query("delete from users where id=any($1::bigint[])",[users]); } await pool.end();});
