import { api } from "@/lib/api-client";

export type ComplementaryRecallReasonCode = "missing_sequence_phase" | "incomplete_anatomical_coverage" | "motion_nondiagnostic_quality" | "incorrect_protocol" | "incorrect_contrast_phase_timing" | "additional_diagnostic_characterization" | "technical_equipment_problem" | "patient_related_limitation" | "other";
export type ComplementaryRecallQaClassification = "diagnostic_addition" | "technical_repeat" | "protocol_error" | "acquisition_error" | "equipment_failure" | "patient_related_unavoidable" | "other";
export type ComplementaryRecallUrgency = "same_day" | "within_24_hours" | "within_72_hours" | "routine";
export type ComplementaryRecallReportingDisposition = "supplement_original_report" | "separate_report" | "no_separate_report";

export type ComplementaryRecallMetadataPayload = { reasonCode: ComplementaryRecallReasonCode; qaClassification: ComplementaryRecallQaClassification; urgency: ComplementaryRecallUrgency; dueAt: string | null; reportingDisposition: ComplementaryRecallReportingDisposition; };
export type ComplementaryRecall = { id: number; originalAppointmentId: number; recallAppointmentId: number | null; receptionInstruction: string | null; technologistInstruction: string; status: "pending_scheduling" | "scheduled" | "completed" | "cancelled"; requestedByUserId: number; requestedAt: string; receptionSeenAt: string | null; receptionAcknowledgedAt: string | null; receptionAcknowledgedByUserId: number | null; scheduledAt: string | null; completedAt: string | null; cancelledAt: string | null; reasonCode: ComplementaryRecallReasonCode | null; qaClassification: ComplementaryRecallQaClassification | null; urgency: ComplementaryRecallUrgency | null; dueAt: string | null; reportingDisposition: ComplementaryRecallReportingDisposition | null; patientDisplayName?: string | null; patientArabicName?: string | null; patientEnglishName?: string | null; patientMrn?: string | null; patientIdentifier?: string | null; originalAccession?: string; originalExam?: string | null; originalExamAr?: string | null; originalExamEn?: string | null; modalityName?: string | null; modalityNameAr?: string | null; modalityNameEn?: string | null; modalityCode?: string | null; requesterDisplayName?: string | null; receptionAcknowledgedByDisplayName?: string | null; recallAppointmentAccession?: string | null; recallAppointmentDate?: string | null; previousAttemptAppointmentId?: number | null; previousAttemptReason?: string | null; previousAttemptAt?: string | null; };

export async function fetchComplementaryRecalls(): Promise<ComplementaryRecall[]> { return (await api<{ recalls: ComplementaryRecall[] }>("/v2/complementary-recall-requests")).recalls; }
export async function fetchComplementaryRecallUnseenCount(): Promise<number> { return (await api<{ count: number }>("/v2/complementary-recall-requests/unseen-count")).count; }
export type ComplementaryRecallReceptionSummary = { pendingCount: number; unseenPendingCount: number; };
export async function fetchComplementaryRecallReceptionSummary(): Promise<ComplementaryRecallReceptionSummary> { return api<ComplementaryRecallReceptionSummary>("/v2/complementary-recall-requests/reception-summary"); }
export async function markComplementaryRecallsSeen(ids: number[]): Promise<void> { await api<void>("/v2/complementary-recall-requests/mark-seen", { method: "POST", body: JSON.stringify({ ids }) }); }
export async function acknowledgeComplementaryRecall(id: number): Promise<ComplementaryRecall> { return (await api<{ recall: ComplementaryRecall }>(`/v2/complementary-recall-requests/${id}/acknowledge`, { method: "POST" })).recall; }
export async function fetchComplementaryRecall(id: number): Promise<ComplementaryRecall> { return (await api<{ recall: ComplementaryRecall }>(`/v2/complementary-recall-requests/${id}`)).recall; }
export type ComplementaryRecallBookingContext = ComplementaryRecall & { patientId: number; modalityId: number; examTypeId: number; originalAccession: string; originalExam: string | null; };
export async function fetchComplementaryRecallBookingContext(id: number): Promise<ComplementaryRecallBookingContext> { return (await api<{ recall: ComplementaryRecallBookingContext }>(`/v2/complementary-recall-requests/${id}/booking-context`)).recall; }
export async function withdrawComplementaryRecall(id: number): Promise<ComplementaryRecall> { return (await api<{ recall: ComplementaryRecall }>(`/v2/complementary-recall-requests/${id}/withdraw`, { method: "POST" })).recall; }
