import { api } from "@/lib/api-client";

export type IrReferral = { id:number; patientId:number; patientMrn:string|null; patientDicomId:string|null; patientEnglishName:string|null; patientArabicName:string|null; requestedProcedure:string; clinicalIndication:string|null; status:string; assignedDoctorId:number|null; assignedDoctorName:string|null; assignedDoctorNameAr:string|null; assignedDoctorNameEn:string|null; notifyAssignedDoctor:boolean; documentsConfirmed:boolean; imagesConfirmed:boolean; materialsConfirmed:boolean; assessmentText:string|null; decision:string|null; decisionNote:string|null; reviewedByDoctorId:number|null; reviewedByDoctorName:string|null; reviewedByDoctorNameAr:string|null; reviewedByDoctorNameEn:string|null; reviewedAt:string|null; createdAt:string; documentCount:number; scheduleRequestId:number|null };
export type IrDoctor = { id:number; displayName:string|null; fullName:string|null; englishName:string|null; username:string|null };
export const fetchAssignableIrDoctors = async () => (await api<{doctors:IrDoctor[]}>("/ir-referrals/doctors")).doctors;
export const createIrReferral = async (payload:{patientId:number;requestedProcedure:string;clinicalIndication?:string|null;assignedDoctorId:number;notifyAssignedDoctor:boolean}) => (await api<{referral:IrReferral}>("/ir-referrals",{method:"POST",body:JSON.stringify(payload)})).referral;
export const fetchIrReferral = async (id:number) => (await api<{referral:IrReferral}>(`/ir-referrals/${id}`)).referral;
export const fetchIrReferrals = async () => (await api<{referrals:IrReferral[]}>("/ir-referrals")).referrals;
export type IrDocument = { id:number; original_filename?:string; originalFilename?:string; file_size?:number; fileSize?:number; mime_type?:string; mimeType?:string };
export const listIrReferralDocuments = async (id:number) => (await api<{documents:IrDocument[]}>(`/ir-referrals/${id}/documents`)).documents;
export const uploadIrReferralDocument = async (id:number,payload:{originalFilename:string;mimeType:string;fileContentBase64:string}) => (await api<{document:IrDocument}>(`/ir-referrals/${id}/documents`,{method:"POST",body:JSON.stringify(payload)})).document;
export const deleteIrReferralDocument = async (id:number,documentId:number) => api<{deleted:true;documentId:number}>(`/ir-referrals/${id}/documents/${documentId}`,{method:"DELETE"});
export const confirmIrReferralMaterials = async (id:number,payload:{documentsConfirmed:boolean;imagesConfirmed:boolean;note?:string|null}) => (await api<{referral:IrReferral}>(`/ir-referrals/${id}/confirm-materials`,{method:"POST",body:JSON.stringify(payload)})).referral;
export const fetchMyIrReferralWorklist = async () => (await api<{referrals:IrReferral[]}>("/ir-referrals/my-worklist")).referrals;
export const recordIrReferralDecision = async (id:number,payload:{assessmentText?:string|null;decision:string;decisionNote?:string|null}) => (await api<{referral:IrReferral}>(`/ir-referrals/${id}/decision`,{method:"POST",body:JSON.stringify(payload)})).referral;
export type IrReferralScheduleRequest = { id:number; irReferralCaseId:number; patientId:number; patientMrn:string|null; patientEnglishName:string|null; patientArabicName:string|null; requestedProcedure:string; assignedDoctorName:string|null; requestedModalityId:number; requestedExamTypeId:number; preferredDate:string|null; urgency:"same_day"|"within_24_hours"|"within_72_hours"|"routine"; receptionInstruction:string|null; technologistInstruction:string; status:"pending_scheduling"|"scheduled"|"cancelled"; appointmentId:number|null; requestedAt:string; scheduledAt:string|null };
export const createIrReferralScheduleRequest = async (id:number,payload:{modalityId:number;examTypeId:number;preferredDate?:string|null;urgency:IrReferralScheduleRequest["urgency"];receptionInstruction?:string|null;technologistInstruction:string}) => (await api<{request:IrReferralScheduleRequest}>(`/ir-referrals/${id}/schedule-requests`,{method:"POST",body:JSON.stringify(payload)})).request;
export const fetchIrReferralScheduleRequests = async () => (await api<{requests:IrReferralScheduleRequest[]}>("/ir-referrals/schedule-requests")).requests;
export const fetchIrReferralScheduleBookingContext = async (id:number) => (await api<{request:IrReferralScheduleRequest}>(`/ir-referrals/schedule-requests/${id}/booking-context`)).request;
