export const BACKUP_V3_LOCAL_DEPLOYMENT_ENV_KEYS = ["NODE_ENV", "PORT"] as const;

export const BACKUP_V3_MANAGED_ENV_KEYS = [
  "RISPRO_DB_MODE",
  "RISPRO_DICOM_MODE",
  "RISPRO_MPPS_MODE",
  "DATABASE_URL",
  "DATABASE_SSL",
  "DATABASE_SSL_REJECT_UNAUTHORIZED",
  "DB_POOL_MAX",
  "JWT_SECRET",
  "COOKIE_NAME",
  "REAUTH_COOKIE_NAME",
  "COOKIE_SECURE",
  "COOKIE_SAME_SITE",
  "SESSION_HOURS",
  "SUPERVISOR_REAUTH_MINUTES",
  "REQUEST_BODY_LIMIT",
  "TRUST_PROXY",
  "UPLOADS_DIR",
  "SCAN_SESSION_TOKEN_SECRET",
  "NAPS2_WEBSCAN_ENABLED",
  "NAPS2_WEBSCAN_ENDPOINT",
  "NAPS2_WEBSCAN_ALLOWED_ORIGINS",
  "SEED_SUPERVISOR_USERNAME",
  "SEED_SUPERVISOR_PASSWORD",
  "SEED_SUPERVISOR_FULL_NAME",
  "SEED_SUPER_ADMIN_USERNAME",
  "SEED_SUPER_ADMIN_PASSWORD",
  "SEED_SUPER_ADMIN_FULL_NAME",
  "ORTHANC_AUTH_ENABLED",
  "ORTHANC_MWL_ENABLED",
  "ORTHANC_MWL_SHADOW_MODE",
  "ORTHANC_BASE_URL",
  "ORTHANC_USERNAME",
  "ORTHANC_PASSWORD",
  "ORTHANC_TIMEOUT_SECONDS",
  "ORTHANC_VERIFY_TLS",
  "ORTHANC_WORKLIST_TARGET",
  "SANTE_HL7_ENABLED",
  "SANTE_HL7_OUTPUT_FOLDER_PATH",
  "SANTE_HL7_ALLOWED_BASE_PATHS",
  "SANTE_HL7_HOST_OUTBOX_HINT",
  "SANTE_HL7_WINDOWS_SHARE_SOURCE_HINT",
  "MPPS_BRIDGE_PORT",
  "MPPS_BRIDGE_AE_TITLE",
  "MPPS_AUTH_ENABLED",
  "MPPS_USERNAME",
  "MPPS_PASSWORD",
  "WEB_PUSH_ENABLED",
  "WEB_PUSH_VAPID_PUBLIC_KEY",
  "WEB_PUSH_VAPID_PRIVATE_KEY",
  "WEB_PUSH_VAPID_SUBJECT",
  "WEB_PUSH_REMINDER_HOURS",
  "WEB_PUSH_WORKER_INTERVAL_SECONDS",
  "WEB_PUSH_DELIVERY_MAX_ATTEMPTS",
  "WEB_PUSH_REPORT_READY_SCAN_INTERVAL_SECONDS",
  "WEB_PUSH_REPORT_READY_LOOKBACK_DAYS",
  "WEB_PUSH_REPORT_READY_MAX_CHECKS_PER_RUN",
  "DOCTOR_PORTAL_ENABLED",
  "DOCTOR_PORTAL_AUTO_REDIRECT",
] as const;

const MANAGED_ENV_KEYS = new Set<string>(BACKUP_V3_MANAGED_ENV_KEYS);
const LOCAL_DEPLOYMENT_ENV_KEYS = new Set<string>(BACKUP_V3_LOCAL_DEPLOYMENT_ENV_KEYS);

export function isBackupV3ManagedEnvKey(name: string): boolean {
  return MANAGED_ENV_KEYS.has(name);
}

export function isBackupV3LocalDeploymentEnvKey(name: string): boolean {
  return LOCAL_DEPLOYMENT_ENV_KEYS.has(name);
}
