import fs from "fs/promises";
import path from "path";
import { spawn, type ChildProcess } from "child_process";
import { pool } from "../db/pool.js";
import { resolveGatewaySettings, detectDicomTools } from "./dicom-settings-resolver.js";
import type { ResolvedGatewaySettings } from "./dicom-settings-resolver.js";

export interface DicomGatewayServer {
  stop(): Promise<void>;
}

export async function startDicomGateway(): Promise<DicomGatewayServer | null> {
  try {
    const settings = await resolveGatewaySettings();

    if (!settings.enabled) {
      console.log("[DICOM Gateway] Disabled in settings. Not starting.");
      return null;
    }

    // Detect tools
    const tools = await detectDicomTools();

    if (tools.dump2dcm.detected && tools.dump2dcm.path) {
      await updateSettingIfDifferent("dump2dcm_command", tools.dump2dcm.path);
    }

    if (tools.dcmdump.detected && tools.dcmdump.path) {
      await updateSettingIfDifferent("dcmdump_command", tools.dcmdump.path);
    }

    // Check if dcmqrscp is available
    const dcmqrscpPath = await findBinary("dcmqrscp");

    if (!dcmqrscpPath) {
      console.log("[DICOM Gateway] dcmqrscp not found. MWL SCP server disabled.");
      console.log("[DICOM Gateway] Install DCMTK: apt-get install -y dcmtk");
      return null;
    }

    // Start MWL SCP server using dcmqrscp
    const mwlProcess = await startMwlScpServer(settings, dcmqrscpPath);

    if (mwlProcess) {
      console.log(`[DICOM Gateway] MWL SCP running on ${settings.bindHost}:${settings.mwlPort} (AE: ${settings.mwlAeTitle})`);
      console.log(`[DICOM Gateway] Serving worklists from: ${settings.worklistOutputDir}`);
    }

    return {
      async stop() {
        if (mwlProcess) {
          mwlProcess.kill("SIGTERM");
          console.log("[DICOM Gateway] MWL SCP stopped.");
        }
      }
    };
  } catch (error) {
    console.error("[DICOM Gateway] Failed to start:", error);
    return null;
  }
}

async function startMwlScpServer(settings: ResolvedGatewaySettings, dcmqrscpPath: string): Promise<ChildProcess | null> {
  const configDir = path.join(settings.worklistOutputDir, "dcmqrscp-config");
  const dbDir = path.join(settings.worklistOutputDir, "dcmqrscp-db");
  const configFile = path.join(configDir, "dcmqrscp.cfg");
  const indexFile = path.join(dbDir, "index.dat");

  try {
    // Create config and DB directories
    await fs.mkdir(configDir, { recursive: true });
    await fs.mkdir(dbDir, { recursive: true });

    // Generate dcmqrscp configuration
    const configContent = generateDcmqrscpConfig(settings, dbDir);
    await fs.writeFile(configFile, configContent, "utf8");

    // Initialize the database if it doesn't exist
    if (!(await fileExists(indexFile))) {
      await fs.writeFile(indexFile, "", "utf8");
    }

    // Start dcmqrscp
    const args = [
      "--config", configFile,
      "--port", String(settings.mwlPort),
      "--verbose"
    ];

    const proc = spawn(dcmqrscpPath, args, {
      env: { ...process.env },
      stdio: ["ignore", "pipe", "pipe"]
    });

    proc.stdout?.on("data", (data: Buffer) => {
      const line = data.toString().trim();
      if (line) {
        console.log(`[DICOM MWL] ${line}`);
      }
    });

    proc.stderr?.on("data", (data: Buffer) => {
      const line = data.toString().trim();
      if (line && !line.includes("Association Accepted") && !line.includes("Sending Store Response")) {
        console.error(`[DICOM MWL] ${line}`);
      }
    });

    proc.on("error", (error) => {
      console.error("[DICOM MWL] Process error:", error.message);
    });

    proc.on("exit", (code, signal) => {
      console.log(`[DICOM MWL] Process exited with code ${code} (signal: ${signal})`);
    });

    return proc;
  } catch (error) {
    console.error("[DICOM MWL] Failed to start dcmqrscp:", error);
    return null;
  }
}

function generateDcmqrscpConfig(settings: ResolvedGatewaySettings, dbDir: string): string {
  return `
# dcmqrscp configuration file - auto-generated by RISpro
NetworkTCPPort = ${settings.mwlPort}
MaxPDUSize = 16384
MaxAssociations = 16

HostTable = (
  {
    Name = ANY
    HostName = ${settings.bindHost}
    Port = ${settings.mwlPort}
  }
)

AETable = (
  ${settings.mwlAeTitle}  ${dbDir}  RW (99, 1024mb)   ANY
)

VendorCap = (
  DefaultLimit = 0
  DefaultSupportedLimit = 0
)
`;
}

async function findBinary(name: string): Promise<string | null> {
  try {
    const { exec } = await import("child_process");
    const { promisify } = await import("util");
    const execAsync = promisify(exec);

    const whichCmd = process.platform === "win32" ? "where" : "which";
    const { stdout } = await execAsync(`${whichCmd} ${name}`);
    return stdout.trim() || null;
  } catch {
    return null;
  }
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function updateSettingIfDifferent(key: string, newValue: string): Promise<void> {
  try {
    const { rows } = await pool.query(
      `select setting_value->>'value' as current_value from system_settings where category = 'dicom_gateway' and setting_key = $1 limit 1`,
      [key]
    );

    const currentValue = rows[0]?.current_value || "";

    if (currentValue !== newValue) {
      await pool.query(
        `update system_settings set setting_value = $2::jsonb where category = 'dicom_gateway' and setting_key = $1`,
        [key, JSON.stringify({ value: newValue })]
      );
      console.log(`[DICOM Gateway] Updated ${key} to ${newValue}`);
    }
  } catch (error) {
    console.error(`[DICOM Gateway] Failed to update ${key}:`, error);
  }
}
