import type { Pool, PoolClient } from "pg";
import { pool } from "../db/pool.js";
import { HttpError } from "../utils/http-error.js";
import { decryptRuntimeSecret, encryptRuntimeSecret, isRuntimeSecretEncryptionConfigured, type RuntimeSecretBundle } from "./runtime-secret-crypto.js";
import { logAuditEntry } from "./audit-service.js";

export type EmailSettings = { enabled: boolean; senderName: string; senderEmail: string; replyToEmail: string; smtpHost: string; smtpPort: number; securityMode: "tls"|"starttls"; smtpUsername: string; connectionTimeoutSeconds: number; passwordConfigured: boolean; encryptionKeyConfigured: boolean };
export type EmailSettingsInput = Omit<EmailSettings,"passwordConfigured"|"encryptionKeyConfigured"> & { password?: string };
type Row = { enabled:boolean; sender_name:string; sender_email:string; reply_to_email:string|null; smtp_host:string; smtp_port:number; security_mode:"tls"|"starttls"; smtp_username:string; smtp_password_secret:RuntimeSecretBundle|null; connection_timeout_seconds:number };
const email = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const host = /^[A-Za-z0-9][A-Za-z0-9.-]*[A-Za-z0-9]$/;
const toPublic=(r:Row):EmailSettings=>({enabled:r.enabled,senderName:r.sender_name,senderEmail:r.sender_email,replyToEmail:r.reply_to_email||"",smtpHost:r.smtp_host,smtpPort:Number(r.smtp_port),securityMode:r.security_mode,smtpUsername:r.smtp_username,connectionTimeoutSeconds:Number(r.connection_timeout_seconds),passwordConfigured:Boolean(r.smtp_password_secret),encryptionKeyConfigured:isRuntimeSecretEncryptionConfigured()});
async function row(db:Pool|PoolClient=pool):Promise<Row>{ const q=await db.query<Row>("select enabled,sender_name,sender_email,reply_to_email,smtp_host,smtp_port,security_mode,smtp_username,smtp_password_secret,connection_timeout_seconds from email_smtp_configuration where id=1"); if(!q.rows[0]) throw new Error("Email SMTP configuration is not initialized."); return q.rows[0]; }
export async function getEmailSettings(db:Pool|PoolClient=pool){ return toPublic(await row(db)); }
export async function resolveEmailSettings(db:Pool|PoolClient=pool){ const r=await row(db); return {...toPublic(r), password:r.smtp_password_secret ? decryptRuntimeSecret(r.smtp_password_secret) : ""}; }
export function validateEmailSettings(input:EmailSettingsInput, passwordConfigured:boolean):void { if(!email.test(input.senderEmail.trim())) throw new HttpError(400,"A valid sender email is required."); if(input.replyToEmail && !email.test(input.replyToEmail.trim())) throw new HttpError(400,"Reply-to email is invalid."); if(!host.test(input.smtpHost.trim())) throw new HttpError(400,"SMTP host is invalid."); if(!Number.isInteger(input.smtpPort)||input.smtpPort<1||input.smtpPort>65535) throw new HttpError(400,"SMTP port must be between 1 and 65535."); if(input.securityMode!=="tls"&&input.securityMode!=="starttls") throw new HttpError(400,"Security mode must be TLS or STARTTLS."); if(!Number.isInteger(input.connectionTimeoutSeconds)||input.connectionTimeoutSeconds<3||input.connectionTimeoutSeconds>60) throw new HttpError(400,"Connection timeout must be between 3 and 60 seconds."); if(input.enabled&&(!input.smtpUsername.trim()||!(input.password?.trim()||passwordConfigured))) throw new HttpError(400,"Enabled SMTP requires a username and password."); }
export async function saveEmailSettings(input:EmailSettingsInput, userId:number|string, db:Pool|PoolClient=pool):Promise<EmailSettings>{ const old=await row(db); validateEmailSettings(input,Boolean(old.smtp_password_secret)); let secret=old.smtp_password_secret; if(input.password?.trim()){ if(!isRuntimeSecretEncryptionConfigured()) throw new HttpError(400,"RISPRO_SECRET_ENCRYPTION_KEY must be configured before saving an SMTP password."); secret=encryptRuntimeSecret(input.password); } const values=[input.enabled,input.senderName.trim(),input.senderEmail.trim(),input.replyToEmail.trim()||null,input.smtpHost.trim(),input.smtpPort,input.securityMode,input.smtpUsername.trim(),secret?JSON.stringify(secret):null,input.connectionTimeoutSeconds,userId]; const q=await db.query<Row>("update email_smtp_configuration set enabled=$1,sender_name=$2,sender_email=$3,reply_to_email=$4,smtp_host=$5,smtp_port=$6,security_mode=$7,smtp_username=$8,smtp_password_secret=$9::jsonb,connection_timeout_seconds=$10,updated_by_user_id=$11,updated_at=now() where id=1 returning enabled,sender_name,sender_email,reply_to_email,smtp_host,smtp_port,security_mode,smtp_username,smtp_password_secret,connection_timeout_seconds",values); const result=toPublic(q.rows[0]); await logAuditEntry({entityType:"email_smtp_configuration",entityId:1,actionType:"updated",newValues:{enabled:result.enabled,senderEmail:result.senderEmail,smtpHost:result.smtpHost,smtpPort:result.smtpPort,securityMode:result.securityMode,smtpUsername:result.smtpUsername,passwordConfigured:result.passwordConfigured},changedByUserId:userId as number},db); return result; }
export async function mergeEmailTestConfiguration(input:EmailSettingsInput, db:Pool|PoolClient=pool){ const saved=await resolveEmailSettings(db); const candidate={...input,password:input.password?.trim()||saved.password}; validateEmailSettings(candidate,Boolean(candidate.password)); if(!candidate.password) throw new HttpError(400,"An SMTP password is required to test the connection."); return candidate; }
