import type { Pool, PoolClient } from "pg";
import { pool } from "../db/pool.js";
import { HttpError } from "../utils/http-error.js";

const definitions = { additional_imaging_completed: { label: "Additional imaging completed", description: "Email the doctor currently assigned to report the original examination when requested additional imaging is completed and ready for review.", recipientDescription: "Assigned reporting doctor", defaultSubjectTemplate: "RISpro: Additional imaging completed — {{additional_imaging_accession}}", defaultTextBodyTemplate: "Additional imaging has been completed and is ready for review.\n\nPatient: {{patient_name}}\nOriginal examination: {{original_examination}}\nModality: {{modality}}\nOriginal accession: {{original_accession}}\nAdditional imaging accession: {{additional_imaging_accession}}\nReporting action: {{reporting_action}}\n\nPlease review the additional images and complete the appropriate reporting action.\n\nRISpro", availableBodyPlaceholders: ["patient_name", "original_examination", "modality", "original_accession", "additional_imaging_accession", "reporting_action"], availableSubjectPlaceholders: ["original_examination", "modality", "original_accession", "additional_imaging_accession", "reporting_action"] } } as const;
export type EmailNotificationEventType = keyof typeof definitions;
export type EmailNotificationRule = { eventType: EmailNotificationEventType; enabled: boolean; subjectTemplate: string; textBodyTemplate: string } & typeof definitions[EmailNotificationEventType];
const requireEvent=(eventType:string):EmailNotificationEventType=>{if(!(eventType in definitions))throw new HttpError(400,"Unknown email notification event type.");return eventType as EmailNotificationEventType;};
function validate(template:string,allowed:readonly string[],field:string){const value=template.trim();if(!value)throw new HttpError(400,`${field} is required.`);if(value.length>(field==="Subject template"?250:10_000))throw new HttpError(400,`${field} is too long.`);for(const token of value.matchAll(/{{\s*([^{}\s]+)\s*}}/g))if(!allowed.includes(token[1]!))throw new HttpError(400,`Unsupported placeholder: {{${token[1]}}}.`);return value;}
function mapRule(eventType:EmailNotificationEventType,row:{enabled:boolean;subject_template:string;text_body_template:string}):EmailNotificationRule{return {eventType,enabled:row.enabled,subjectTemplate:row.subject_template,textBodyTemplate:row.text_body_template,...definitions[eventType]};}
export async function listEmailNotificationRules(db:Pool|PoolClient=pool):Promise<EmailNotificationRule[]>{const r=await db.query<{event_type:string;enabled:boolean;subject_template:string;text_body_template:string}>("select event_type,enabled,subject_template,text_body_template from email_notification_rules where event_type=any($1::text[]) order by event_type",[Object.keys(definitions)]);return r.rows.map(x=>mapRule(requireEvent(x.event_type),x));}
export async function getEmailNotificationRule(eventType:string,db:Pool|PoolClient=pool):Promise<EmailNotificationRule>{const known=requireEvent(eventType);const r=await db.query<{enabled:boolean;subject_template:string;text_body_template:string}>("select enabled,subject_template,text_body_template from email_notification_rules where event_type=$1",[known]);if(!r.rows[0])throw new Error(`Email notification rule ${known} is not initialized.`);return mapRule(known,r.rows[0]);}
export async function setEmailNotificationRule(eventType:string,enabled:boolean,updatedByUserId:number|string,db:Pool|PoolClient=pool){const known=requireEvent(eventType);const r=await db.query<{enabled:boolean;subject_template:string;text_body_template:string}>("update email_notification_rules set enabled=$2,updated_by_user_id=$3,updated_at=now() where event_type=$1 returning enabled,subject_template,text_body_template",[known,enabled,updatedByUserId]);if(!r.rows[0])throw new Error(`Email notification rule ${known} is not initialized.`);return mapRule(known,r.rows[0]);}
export async function setEmailNotificationTemplate(eventType:string,input:{subjectTemplate:unknown;textBodyTemplate:unknown},updatedByUserId:number|string,db:Pool|PoolClient=pool){const known=requireEvent(eventType),d=definitions[known],subjectTemplate=validate(String(input.subjectTemplate??""),d.availableSubjectPlaceholders,"Subject template"),textBodyTemplate=validate(String(input.textBodyTemplate??""),d.availableBodyPlaceholders,"Message template");const r=await db.query<{enabled:boolean;subject_template:string;text_body_template:string}>("update email_notification_rules set subject_template=$2,text_body_template=$3,updated_by_user_id=$4,updated_at=now() where event_type=$1 returning enabled,subject_template,text_body_template",[known,subjectTemplate,textBodyTemplate,updatedByUserId]);if(!r.rows[0])throw new Error(`Email notification rule ${known} is not initialized.`);return mapRule(known,r.rows[0]);}
