import nodemailer from "nodemailer";
import type { EmailSettingsInput } from "./email-settings-service.js";

export type EmailSendResult = { messageId: string; accepted: string[]; rejected: string[]; response: string };
export function createEmailTransporter(config: Pick<EmailSettingsInput,"smtpHost"|"smtpPort"|"securityMode"|"smtpUsername"|"password"|"connectionTimeoutSeconds">) {
  return nodemailer.createTransport({ host: config.smtpHost, port: config.smtpPort, secure: config.securityMode === "tls", requireTLS: config.securityMode === "starttls", auth: { user: config.smtpUsername, pass: config.password || "" }, connectionTimeout: config.connectionTimeoutSeconds * 1000, socketTimeout: config.connectionTimeoutSeconds * 1000, tls: { rejectUnauthorized: true } });
}
export async function verifyEmailConfiguration(config: EmailSettingsInput): Promise<void> { await createEmailTransporter(config).verify(); }
export async function sendEmail(config: EmailSettingsInput, message: { to:string; subject:string; text:string }): Promise<EmailSendResult> { const result=await createEmailTransporter(config).sendMail({ from: config.senderName ? `${config.senderName} <${config.senderEmail}>` : config.senderEmail, replyTo: config.replyToEmail || undefined, to: message.to, subject: message.subject, text: message.text }); return {messageId:String(result.messageId||""),accepted:(result.accepted||[]).map(String),rejected:(result.rejected||[]).map(String),response:String(result.response||"")}; }
export function classifyEmailError(error: unknown): { code:string; summary:string; transient:boolean } { const item=error as { code?:unknown; responseCode?:unknown; message?:unknown }; const code=String(item?.code || item?.responseCode || "SMTP_ERROR").slice(0,80); const summary=String(item?.message || "SMTP operation failed.").replace(/[\r\n]+/g," ").slice(0,500); const responseCode=Number(item?.responseCode); const transient=!(code === "EAUTH" || (responseCode >= 500 && responseCode < 600) || /recipient|invalid address/i.test(summary)) && (responseCode >=400 && responseCode<500 || /ETIMEDOUT|ECONN|ENOTFOUND|EAI_AGAIN|socket|timeout/i.test(code+" "+summary)); return {code,summary,transient}; }
