import { pool } from "../db/pool.js";
import { HttpError } from "../utils/http-error.js";
import { normalizePositiveInteger } from "../utils/normalize.js";
import { logAuditEntry } from "./audit-service.js";
import type { UserId } from "../types/http.js";
import type { PoolClient } from "pg";

export const EQUIPMENT_TYPES = ["CT", "MRI", "MAMMOGRAPHY", "ULTRASOUND", "XRAY", "WORKSTATION", "PACS_IT", "INJECTOR", "PRINTER", "OTHER"] as const;
export type EquipmentType = (typeof EQUIPMENT_TYPES)[number];

export interface EquipmentRow { id:number; name:string; equipmentType:EquipmentType; modality:string|null; modalityId:number|null; modalityCode:string|null; vendor:string|null; model:string|null; serialNumber:string|null; location:string|null; dicomDeviceId:number|null; dicomDeviceName:string|null; dicomDeviceAeTitle:string|null; fieldStrength:string|null; ctSliceDetectorSpecification:string|null; notes:string|null; isActive:boolean; createdAt:string; updatedAt:string; }
type Input = Record<string, unknown>;
const text = (value: unknown) => { const result = String(value ?? "").trim(); return result || null; };
const optionalId = (value: unknown, field: string) => value === undefined ? undefined : (value === null || value === "" ? null : normalizePositiveInteger(value, field));
function type(value: unknown): EquipmentType { const result = String(value ?? "").trim().toUpperCase(); if (!EQUIPMENT_TYPES.includes(result as EquipmentType)) throw new HttpError(400, "equipmentType is invalid."); return result as EquipmentType; }
function map(row: Record<string, unknown>): EquipmentRow { return { id:Number(row.id), name:String(row.name), equipmentType:String(row.equipment_type) as EquipmentType, modality:row.modality === null ? null : String(row.modality), modalityId:row.modality_id === null ? null : Number(row.modality_id), modalityCode:row.modality_code === null ? null : String(row.modality_code), vendor:text(row.vendor), model:text(row.model), serialNumber:text(row.serial_number), location:text(row.location), dicomDeviceId:row.dicom_device_id === null ? null : Number(row.dicom_device_id), dicomDeviceName:text(row.dicom_device_name), dicomDeviceAeTitle:text(row.dicom_device_ae_title), fieldStrength:text(row.field_strength), ctSliceDetectorSpecification:text(row.ct_slice_detector_specification), notes:text(row.notes), isActive:Boolean(row.is_active), createdAt:String(row.created_at), updatedAt:String(row.updated_at) }; }
const select = `select e.*, m.code as modality_code, d.device_name as dicom_device_name, d.modality_ae_title as dicom_device_ae_title from equipment e left join modalities m on m.id=e.modality_id left join dicom_devices d on d.id=e.dicom_device_id`;
async function validate(client: PoolClient, equipmentType: EquipmentType, modalityId: number|null, dicomDeviceId: number|null, id?: number) {
  let modalityCode: string|null = null;
  if (modalityId) { const r=await client.query("select code from modalities where id=$1",[modalityId]); if(!r.rows[0]) throw new HttpError(400,"Linked modality not found."); modalityCode=String(r.rows[0].code).trim().toUpperCase(); }
  if ((equipmentType === "CT" && modalityCode !== "CT") || (equipmentType === "MRI" && !["MR","MRI"].includes(modalityCode ?? ""))) throw new HttpError(400, `${equipmentType} equipment requires a compatible linked RIS modality.`);
  if (dicomDeviceId) { const r=await client.query("select modality_id from dicom_devices where id=$1",[dicomDeviceId]); if(!r.rows[0]) throw new HttpError(400,"Linked DICOM device not found."); if(modalityId && Number(r.rows[0].modality_id)!==modalityId) throw new HttpError(400,"Linked DICOM device modality must match equipment modality."); const used=await client.query("select id from equipment where dicom_device_id=$1 and id <> coalesce($2, 0)",[dicomDeviceId,id ?? null]); if(used.rows[0]) throw new HttpError(409,"DICOM identity is already linked to another equipment record."); }
}
export async function listEquipment(includeInactive=false): Promise<EquipmentRow[]> { const r=await pool.query(`${select} ${includeInactive ? "" : "where e.is_active=true"} order by e.is_active desc,e.name asc`); return r.rows.map(map); }
export async function getEquipment(id:number|string): Promise<EquipmentRow|null> { const r=await pool.query(`${select} where e.id=$1`,[Number(normalizePositiveInteger(id,"equipmentId"))]); return r.rows[0] ? map(r.rows[0]) : null; }
export async function createEquipment(input:Input, actor:UserId): Promise<EquipmentRow> { const name=text(input.name); if(!name) throw new HttpError(400,"name is required."); const equipmentType=type(input.equipmentType ?? input.equipment_type); const modalityId=optionalId(input.modalityId ?? input.modality_id,"modalityId") ?? null; const dicomDeviceId=optionalId(input.dicomDeviceId ?? input.dicom_device_id,"dicomDeviceId") ?? null; const client=await pool.connect(); try { await client.query("begin"); await validate(client,equipmentType,modalityId,dicomDeviceId); const r=await client.query(`insert into equipment(name,equipment_type,modality,modality_id,vendor,model,serial_number,location,dicom_device_id,field_strength,ct_slice_detector_specification,notes,is_active) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) returning id`,[name,equipmentType,equipmentType === "CT" ? "CT" : equipmentType === "MRI" ? "MRI" : null,modalityId,text(input.vendor),text(input.model),text(input.serialNumber ?? input.serial_number),text(input.location),dicomDeviceId,equipmentType === "MRI" ? text(input.fieldStrength ?? input.field_strength) : null,equipmentType === "CT" ? text(input.ctSliceDetectorSpecification ?? input.ct_slice_detector_specification) : null,text(input.notes),input.isActive ?? input.is_active ?? true]); await logAuditEntry({entityType:"equipment",entityId:Number(r.rows[0].id),actionType:"create",newValues:{id:r.rows[0].id},changedByUserId:actor},client); await client.query("commit"); return (await getEquipment(Number(r.rows[0].id)))!; } catch(e){await client.query("rollback");throw e;} finally {client.release();} }
export async function updateEquipment(id:number|string,input:Input,actor:UserId): Promise<EquipmentRow> { const equipmentId=Number(normalizePositiveInteger(id,"equipmentId")); const existing=await getEquipment(equipmentId); if(!existing) throw new HttpError(404,"Equipment not found."); const nextType= input.equipmentType === undefined && input.equipment_type === undefined ? existing.equipmentType : type(input.equipmentType ?? input.equipment_type); const nextModality=optionalId(input.modalityId ?? input.modality_id,"modalityId") ?? existing.modalityId; const nextDicom=optionalId(input.dicomDeviceId ?? input.dicom_device_id,"dicomDeviceId") ?? existing.dicomDeviceId; const client=await pool.connect(); try {await client.query("begin");await validate(client,nextType,nextModality,nextDicom,equipmentId); const r=await client.query(`update equipment set name=$2,equipment_type=$3,modality=$4,modality_id=$5,vendor=$6,model=$7,serial_number=$8,location=$9,dicom_device_id=$10,field_strength=$11,ct_slice_detector_specification=$12,notes=$13,is_active=$14 where id=$1 returning id`,[equipmentId,text(input.name) ?? existing.name,nextType,nextType === "CT" ? "CT" : nextType === "MRI" ? "MRI" : null,nextModality,"vendor" in input ? text(input.vendor):existing.vendor,"model" in input ? text(input.model):existing.model,"serialNumber" in input || "serial_number" in input ? text(input.serialNumber ?? input.serial_number):existing.serialNumber,"location" in input?text(input.location):existing.location,nextDicom,nextType === "MRI" ? ("fieldStrength" in input || "field_strength" in input ? text(input.fieldStrength ?? input.field_strength):existing.fieldStrength):null,nextType === "CT" ? ("ctSliceDetectorSpecification" in input || "ct_slice_detector_specification" in input ? text(input.ctSliceDetectorSpecification ?? input.ct_slice_detector_specification):existing.ctSliceDetectorSpecification):null,"notes" in input?text(input.notes):existing.notes,input.isActive ?? input.is_active ?? existing.isActive]); await logAuditEntry({entityType:"equipment",entityId:equipmentId,actionType:"update",oldValues:existing,newValues:{id:r.rows[0].id},changedByUserId:actor},client); await client.query("commit"); return (await getEquipment(equipmentId))!;}catch(e){await client.query("rollback");throw e;}finally{client.release();} }
export async function deactivateEquipment(id:number|string,actor:UserId): Promise<EquipmentRow> { return updateEquipment(id,{isActive:false},actor); }
