import { pool } from "../db/pool.js";
import { HttpError } from "../utils/http-error.js";
import { normalizePositiveInteger } from "../utils/normalize.js";
import { logAuditEntry } from "./audit-service.js";

export const INCIDENT_TYPES = ["equipment", "clinical_workflow"] as const;
export const INCIDENT_STATUSES = ["submitted", "under_review", "action_required", "resolved", "closed"] as const;
const EQUIPMENT_CONDITIONS = ["operational", "degraded", "out_of_service"] as const;
const CLINICAL_CATEGORIES = ["wrong_patient", "wrong_exam", "wrong_protocol", "acquisition_quality", "contrast_event", "delay", "communication_failure", "reporting_issue", "other"] as const;
const HARM_LEVELS = ["near_miss", "no_harm", "harm"] as const;
const allowed = (value: unknown, list: readonly string[], name: string, required = false) => { const v = String(value ?? "").trim(); if (!v && !required) return null; if (!list.includes(v)) throw new HttpError(400, `Invalid ${name}.`); return v; };
const text = (value: unknown) => String(value ?? "").trim() || null;
const row = (r: Record<string, unknown>) => ({ ...r, incidentNumber: `INC-${String(r.id).padStart(6, "0")}` });

export async function listIncidents(filters: { incidentType?: unknown; status?: unknown } = {}) {
  const type = allowed(filters.incidentType, INCIDENT_TYPES, "incident type"); const status = allowed(filters.status, INCIDENT_STATUSES, "status");
  const clauses: string[] = []; const values: unknown[] = [];
  if (type) { values.push(type); clauses.push(`i.incident_type=$${values.length}`); } if (status) { values.push(status); clauses.push(`i.status=$${values.length}`); }
  const { rows } = await pool.query(`select i.*,e.name equipment_name,e.equipment_type,e.location,p.english_full_name patient_name,p.mrn,u.full_name reporter_name,u.username reporter_username from department_incidents i left join equipment e on e.id=i.equipment_id left join patients p on p.id=i.patient_id left join users u on u.id=i.reported_by_user_id ${clauses.length ? `where ${clauses.join(" and ")}` : ""} order by i.occurred_at desc,i.id desc`, values);
  return rows.map((r) => row(r));
}
export async function getIncident(id: unknown) { const incidentId = normalizePositiveInteger(id, "incidentId"); const rows = await listIncidentRows(incidentId!); if (!rows[0]) throw new HttpError(404, "Incident not found."); return row(rows[0]); }
async function listIncidentRows(id: number) { return (await pool.query(`select i.*,e.name equipment_name,e.equipment_type,e.location,p.english_full_name patient_name,p.mrn,u.full_name reporter_name,u.username reporter_username,ru.full_name reviewer_name from department_incidents i left join equipment e on e.id=i.equipment_id left join patients p on p.id=i.patient_id left join users u on u.id=i.reported_by_user_id left join users ru on ru.id=i.reviewed_by_user_id where i.id=$1`, [id])).rows as Record<string, unknown>[]; }
export async function createIncident(input: Record<string, unknown>, actorId: unknown) {
 const incidentType=allowed(input.incidentType, INCIDENT_TYPES,"incident type",true)!; const occurredAt=text(input.occurredAt); const description=text(input.description); if (!occurredAt || Number.isNaN(Date.parse(occurredAt))) throw new HttpError(400,"occurredAt is required."); if (!description) throw new HttpError(400,"description is required.");
 const equipmentId=normalizePositiveInteger(input.equipmentId,"equipmentId",{required:false}); const patientId=normalizePositiveInteger(input.patientId,"patientId",{required:false}); const condition=allowed(input.equipmentCondition,EQUIPMENT_CONDITIONS,"equipment condition"); const category=allowed(input.clinicalCategory,CLINICAL_CATEGORIES,"clinical category"); const harm=allowed(input.harmLevel,HARM_LEVELS,"harm level");
 if (incidentType === "equipment" && (!equipmentId || !condition)) throw new HttpError(400,"Equipment and equipment condition are required."); if (incidentType === "clinical_workflow" && (!category || !harm)) throw new HttpError(400,"Clinical category and harm level are required.");
 const client=await pool.connect(); try { await client.query("begin"); if (equipmentId && !(await client.query("select 1 from equipment where id=$1",[equipmentId])).rowCount) throw new HttpError(404,"Equipment not found."); if (patientId && !(await client.query("select 1 from patients where id=$1",[patientId])).rowCount) throw new HttpError(404,"Patient not found."); const result=await client.query(`insert into department_incidents(incident_type,occurred_at,equipment_id,patient_id,equipment_condition,clinical_category,harm_level,description,immediate_action,vendor_contacted,vendor_contact_person,vendor_reference,reported_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) returning id`,[incidentType,occurredAt,incidentType==='equipment'?equipmentId:null,incidentType==='clinical_workflow'?patientId:null,incidentType==='equipment'?condition:null,incidentType==='clinical_workflow'?category:null,incidentType==='clinical_workflow'?harm:null,description,text(input.immediateAction),Boolean(input.vendorContacted),text(input.vendorContactPerson),text(input.vendorReference),actorId]); const incident=await getIncidentByExecutor(Number(result.rows[0].id),client); await logAuditEntry({entityType:"incident",entityId:Number(result.rows[0].id),actionType:"create",newValues:incident,changedByUserId:actorId as never},client); await client.query("commit"); return incident; } catch(e){await client.query("rollback");throw e;} finally{client.release();}
}
async function getIncidentByExecutor(id:number, executor:{query:typeof pool.query}) { const result=await executor.query("select * from department_incidents where id=$1",[id]); return row(result.rows[0] as Record<string,unknown>); }
export async function reviewIncident(id: unknown,input:Record<string,unknown>,actorId:unknown) { const incidentId=normalizePositiveInteger(id,"incidentId")!; const before=await getIncident(incidentId); const status=allowed(input.status,INCIDENT_STATUSES,"status",true)!; const reviewNotes=text(input.reviewNotes); if (["resolved","closed"].includes(status) && !reviewNotes) throw new HttpError(400,"Review notes are required when resolving or closing an incident."); const client=await pool.connect(); try{await client.query("begin"); await client.query("update department_incidents set status=$2,review_notes=$3,reviewed_by_user_id=$4,updated_at=now() where id=$1",[incidentId,status,reviewNotes,actorId]); const after=await getIncidentByExecutor(incidentId,client); await logAuditEntry({entityType:"incident",entityId:incidentId,actionType:"review",oldValues:before,newValues:after,changedByUserId:actorId as never},client); await client.query("commit"); return getIncident(incidentId);}catch(e){await client.query("rollback");throw e;}finally{client.release();} }
export async function listIncidentEquipment(){ return (await pool.query("select id,name,equipment_type,location from equipment where is_active=true order by name asc")).rows; }
