import assert from "node:assert/strict";
import { after, test } from "node:test";
import { pool } from "../db/pool.js";
import { bulkDismissRequestScanJobs, dismissRequestScanJob, listRequestScanJobs, restoreDismissedRequestScanJob } from "./request-scan-service.js";
import { getRequestScanStatus } from "../routes/request-scans.js";

const ids: number[] = [];
async function ready(t: { skip(message: string): void }) { try { await pool.query("select 1"); return true; } catch { t.skip("PostgreSQL is not reachable at configured DATABASE_URL."); return false; } }
async function job(status = "failed", category: string | null = "recognition") { const tag = `${Date.now()}-${Math.random()}`; const r = await pool.query<{ id: number }>("insert into request_scan_jobs(filename,source_relative_path,mime_type,status,error_message,failure_category,attempt_count) values($1,$2,'image/jpeg',$3,'safe failure',$4,2) returning id", [`request-${tag}.jpg`, `Requests\\Failed\\request-${tag}.jpg`, status, category]); const id = Number(r.rows[0]!.id); ids.push(id); return id; }

test("migration 138 exposes cleanup schema, constraints, and indexes", async (t) => { if (!(await ready(t))) return; const columns = await pool.query<{ column_name: string }>("select column_name from information_schema.columns where table_name='request_scan_jobs' and column_name=any($1::text[])", [["dismissed_at","dismissed_by","dismiss_reason","failure_category"]]); assert.equal(columns.rows.length, 4); const indexes = await pool.query<{ indexname: string }>("select indexname from pg_indexes where tablename='request_scan_jobs' and indexname=any($1::text[])", [["request_scan_jobs_visible_failed_idx","request_scan_jobs_dismissed_idx","request_scan_jobs_failed_category_idx"]]); assert.equal(indexes.rows.length, 3); const id = await job(); await assert.rejects(() => pool.query("update request_scan_jobs set failure_category='bad' where id=$1", [id]), /check constraint/i); });
test("failed and dismissed filters preserve category and audit state", async (t) => { if (!(await ready(t))) return; const actor = await pool.query<{ id:number }>("insert into users(username,full_name,password_hash,role,is_active) values($1,$1,'x','supervisor',true) returning id", [`rs_cleanup_${Date.now()}`]); const userId = Number(actor.rows[0]!.id); const visible = await job("failed", "recognition"); const dismissed = await job("failed", "smb_storage"); await dismissRequestScanJob(dismissed, userId, "  reviewed  "); const failed = await listRequestScanJobs("failed"); const dismissedRows = await listRequestScanJobs("dismissed", "smb_storage"); assert.ok(failed.some((row) => row.id === visible)); assert.ok(!failed.some((row) => row.id === dismissed)); assert.equal(dismissedRows.find((row) => row.id === dismissed)?.dismiss_reason, "reviewed"); const restored = await restoreDismissedRequestScanJob(dismissed, userId); assert.equal(restored.dismissed_at, null); assert.equal(restored.failure_category, "smb_storage"); await pool.query("delete from users where id=$1", [userId]); });
test("bulk dismiss is all-or-nothing", async (t) => { if (!(await ready(t))) return; const actor = await pool.query<{ id:number }>("insert into users(username,full_name,password_hash,role,is_active) values($1,$1,'x','super_admin',true) returning id", [`rs_bulk_${Date.now()}`]); const userId = Number(actor.rows[0]!.id); const one = await job(); const ineligible = await job("processed", null); await assert.rejects(() => bulkDismissRequestScanJobs([one, ineligible], userId), /visible failed/); const row = await pool.query<{ dismissed_at: string | null }>("select dismissed_at from request_scan_jobs where id=$1", [one]); assert.equal(row.rows[0]!.dismissed_at, null); await pool.query("delete from users where id=$1", [userId]); });
test("dismissal transitions visible failed and dismissed status counts", async (t) => { if (!(await ready(t))) return; const actor = await pool.query<{ id:number }>("insert into users(username,full_name,password_hash,role,is_active) values($1,$1,'x','supervisor',true) returning id", [`rs_count_${Date.now()}`]); const userId = Number(actor.rows[0]!.id); const id = await job(); const deps = { readSettings: async () => ({ enabled:true } as never), workerStatus: () => ({ lastRunAt:null,lastError:null,running:false }), query: pool.query.bind(pool) }; const before = await getRequestScanStatus(new Date(), deps); await dismissRequestScanJob(id, userId); const afterDismiss = await getRequestScanStatus(new Date(), deps); await restoreDismissedRequestScanJob(id, userId); const afterRestore = await getRequestScanStatus(new Date(), deps); assert.equal(afterDismiss.failed, before.failed - 1); assert.equal(afterDismiss.dismissed, before.dismissed + 1); assert.equal(afterRestore.failed, before.failed); assert.equal(afterRestore.dismissed, before.dismissed); });
after(async () => { if (ids.length) await pool.query("delete from request_scan_jobs where id=any($1::bigint[])", [ids]); await pool.query("delete from audit_log where entity_type='request_scan_job' and action_type like 'request_scan_%'"); await pool.end(); });
