insert into system_settings (category, setting_key, setting_value)
values (
  'appointment_slip',
  'config',
  '{
    "paperMode": "preprinted",
    "languageMode": "bilingual",
    "safeTopMm": 58,
    "safeBottomMm": 56,
    "safeLeftMm": 10,
    "safeRightMm": 10,
    "contentPaddingMm": 3,
    "fontScale": 1,
    "qrSizeMm": 24,
    "barcodeHeightMm": 12,
    "barcodeWidthMm": 100,
    "hospitalNameAr": "المركز الوطني للأورام بنغازي",
    "hospitalNameEn": "National Cancer Center Benghazi",
    "departmentNameAr": "قسم الأشعة التشخيصية",
    "departmentNameEn": "Diagnostic Radiology Department",
    "showPatientName": true,
    "showMrn": true,
    "showNationalId": false,
    "showPhone": true,
    "showAgeSex": true,
    "showAppointmentNumber": true,
    "showAccessionNumber": true,
    "showModality": true,
    "showExamName": true,
    "showDate": true,
    "showTime": true,
    "showWalkIn": true,
    "showLocation": true,
    "showArrivalNote": true,
    "showQrCode": true,
    "qrCaptionAr": "امسح للاطلاع على تفاصيل الموعد",
    "qrCaptionEn": "Scan for appointment details",
    "qrHelperTextAr": "استخدم الرمز لعرض تعليمات الفحص والموقع وخدمات الموعد.",
    "qrHelperTextEn": "Use this QR code to open your appointment page, instructions, and location details.",
    "showAccessionBarcode": true,
    "barcodeValueMode": "accessionNumber",
    "barcodeCaptionAr": "امسح للدخول إلى قائمة الانتظار",
    "barcodeCaptionEn": "Scan to Enter The Queue",
    "showModalityInstructions": true,
    "showExamSpecificInstructions": true,
    "maxInstructionLinesOnSlip": 4,
    "fallbackInstructionTextAr": "يرجى مسح رمز QR للاطلاع على تعليمات الجهاز والفحص والموقع.",
    "fallbackInstructionTextEn": "Scan the QR code for modality instructions, exam-specific instructions, and location details.",
    "locationTextAr": "",
    "locationTextEn": ""
  }'::jsonb
)
on conflict (category, setting_key) do nothing;
