import type { AppointmentStatus } from '../types/domain.js';

export const APPOINTMENT_STATUS_SCHEDULED = "scheduled";
export const APPOINTMENT_STATUS_ARRIVED = "arrived";
export const APPOINTMENT_STATUS_WAITING = "waiting";
export const APPOINTMENT_STATUS_IN_PROGRESS = "in-progress";
export const APPOINTMENT_STATUS_COMPLETED = "completed";
export const APPOINTMENT_STATUS_DISCONTINUED = "discontinued";
export const APPOINTMENT_STATUS_NO_SHOW = "no-show";
export const APPOINTMENT_STATUS_CANCELLED = "cancelled";

export const APPOINTMENT_RECEPTION_ACTIVE_STATUSES: readonly AppointmentStatus[] = [
  APPOINTMENT_STATUS_SCHEDULED,
  APPOINTMENT_STATUS_ARRIVED,
  APPOINTMENT_STATUS_WAITING
];

export const APPOINTMENT_NON_CANCELLABLE_STATUSES: readonly AppointmentStatus[] = [
  APPOINTMENT_STATUS_CANCELLED,
  APPOINTMENT_STATUS_COMPLETED,
  APPOINTMENT_STATUS_DISCONTINUED,
  APPOINTMENT_STATUS_NO_SHOW,
  APPOINTMENT_STATUS_IN_PROGRESS
];

export const APPOINTMENT_QUEUE_CLOSED_STATUSES: readonly AppointmentStatus[] = [
  APPOINTMENT_STATUS_CANCELLED,
  APPOINTMENT_STATUS_COMPLETED,
  APPOINTMENT_STATUS_NO_SHOW
];

export const APPOINTMENT_QUEUE_WORKING_STATUSES: readonly AppointmentStatus[] = [
  APPOINTMENT_STATUS_ARRIVED,
  APPOINTMENT_STATUS_WAITING,
  APPOINTMENT_STATUS_IN_PROGRESS
];

export const APPOINTMENT_ACTIVE_WORKLIST_STATUSES: readonly AppointmentStatus[] = [
  APPOINTMENT_STATUS_SCHEDULED,
  APPOINTMENT_STATUS_ARRIVED,
  APPOINTMENT_STATUS_WAITING,
  APPOINTMENT_STATUS_IN_PROGRESS
];

export const APPOINTMENT_LISTABLE_STATUSES: readonly AppointmentStatus[] = [
  APPOINTMENT_STATUS_SCHEDULED,
  APPOINTMENT_STATUS_ARRIVED,
  APPOINTMENT_STATUS_WAITING,
  APPOINTMENT_STATUS_COMPLETED,
  APPOINTMENT_STATUS_NO_SHOW,
  APPOINTMENT_STATUS_CANCELLED
];

export function isListableAppointmentStatus(value: unknown): value is AppointmentStatus {
  return typeof value === "string" && APPOINTMENT_LISTABLE_STATUSES.includes(value as AppointmentStatus);
}
