import { lstat, readFile, realpath } from "node:fs/promises";
import path from "node:path";
import { env } from "../../../config/env.js";
import { pool } from "../../../db/pool.js";
import { resolveStorageBasePath } from "../../../services/document-storage-path.js";
import { HttpError } from "../../../utils/http-error.js";

const TEACHING_IMAGE_MIME_TYPES = new Set(["image/jpeg", "image/png", "image/webp"]);

async function teachingAssetFile(assetId: number) {
  const result = await pool.query<{ storage_key: string; mime_type: string; original_filename: string }>(
    "select storage_key, mime_type, original_filename from teaching.assets where id = $1",
    [assetId],
  );
  const asset = result.rows[0];
  if (!asset || !TEACHING_IMAGE_MIME_TYPES.has(asset.mime_type)) throw new HttpError(404, "Teaching asset not found.");

  // Storage keys are generated by the Teaching importer. Validate that invariant
  // before resolving a path so even corrupt metadata cannot escape this namespace.
  const fileName = path.posix.basename(asset.storage_key);
  const validExtensions = asset.mime_type === "image/jpeg" ? ["jpg", "jpeg"] : asset.mime_type === "image/png" ? ["png"] : ["webp"];
  if (!/^teaching\/assets\/[0-9a-f-]{36}\.(?:jpe?g|png|webp)$/i.test(asset.storage_key)
    || !validExtensions.includes(path.posix.extname(fileName).slice(1).toLowerCase())) {
    throw new HttpError(404, "Teaching asset not found.");
  }

  const storageRoot = resolveStorageBasePath(env.uploadsDir);
  const absolutePath = path.resolve(storageRoot, ...asset.storage_key.split("/"));
  const relativePath = path.relative(storageRoot, absolutePath);
  if (relativePath.startsWith("..") || path.isAbsolute(relativePath)) throw new HttpError(404, "Teaching asset not found.");
  try {
    const details = await lstat(absolutePath);
    if (!details.isFile() || details.isSymbolicLink() || details.size > 8 * 1024 * 1024) throw new HttpError(404, "Teaching asset not found.");
    const [rootRealPath, assetRealPath] = await Promise.all([realpath(storageRoot), realpath(absolutePath)]);
    const actualRelativePath = path.relative(rootRealPath, assetRealPath);
    if (actualRelativePath.startsWith("..") || path.isAbsolute(actualRelativePath)) throw new HttpError(404, "Teaching asset not found.");
    const safeFilename = path.basename(asset.original_filename).replace(/[^A-Za-z0-9._-]/g, "_").replace(/_+/g, "_") || "teaching-image";
    return { absolutePath: assetRealPath, mimeType: asset.mime_type, filename: safeFilename };
  } catch (error) {
    if (error instanceof HttpError) throw error;
    throw new HttpError(404, "Teaching asset not found.");
  }
}

export async function readTeachingAsset(assetId: number): Promise<{ content: Buffer; mimeType: string; filename: string }> {
  const asset = await teachingAssetFile(assetId);
  return { mimeType: asset.mimeType, filename: asset.filename, content: await readFile(asset.absolutePath) };
}

export async function assertTeachingAssetsAvailable(assetIds: number[]): Promise<void> {
  await Promise.all(assetIds.map((assetId) => teachingAssetFile(assetId)));
}
