import { pool } from "../../db/pool.js";
import { logAuditEntry } from "../../services/audit-service.js";
import { HttpError } from "../../utils/http-error.js";
import { asUnknownRecord } from "../../utils/records.js";
import { SOP_CATEGORIES, SOP_MANAGEMENT_ROLES, SOP_SECTION_DEFINITIONS, SOP_STATUSES } from "./constants.js";
import { archiveSop, findSop, findSopByCode, findSopVersion, getSopDetail, insertSop, insertSopRevision, listSopSummaries, updateSopDraft, publishSopVersion } from "./sop-repository.js";
import { normalizeSopCategory, normalizeSopCode, normalizeSopDate, normalizeSopVersion, requiredText, validateSopDocument } from "./sop-validation.js";
import type { SopDocument, SopFilters, SopSummary, SopVersion } from "./types.js";

export const SOP_META = { categories: [...SOP_CATEGORIES], sections: SOP_SECTION_DEFINITIONS.map((section) => ({ ...section })) };

function managementRole(role: string): boolean { return (SOP_MANAGEMENT_ROLES as readonly string[]).includes(role); }
export function requireSopManagement(role: string | undefined): void { if (!role) throw new HttpError(401, "Authentication required."); if (!managementRole(role)) throw new HttpError(403, "SOP management access is required."); }
function positiveId(value: unknown, field: string): number { const parsed = Number(value); if (!Number.isInteger(parsed) || parsed <= 0) throw new HttpError(400, `${field} must be a positive integer.`); return parsed; }

export { normalizeSopCode, normalizeSopVersion, validateSopDocument } from "./sop-validation.js";

function parseInput(body: unknown, requireContent = true) {
  const input = asUnknownRecord(body);
  const contentJson = requireContent ? validateSopDocument(input.contentJson ?? input.content_json, false) : undefined;
  return { title: requiredText(input.title, "Title"), code: normalizeSopCode(input.code), category: normalizeSopCategory(input.category), version: normalizeSopVersion(input.version), effectiveDate: normalizeSopDate(input.effectiveDate ?? input.effective_date), changeSummary: String(input.changeSummary ?? input.change_summary ?? "").trim(), contentJson };
}

function isUniqueViolation(error: unknown): boolean { return Boolean(error && typeof error === "object" && "code" in error && (error as { code?: unknown }).code === "23505"); }
function isNotFound(value: unknown): value is null { return value === null; }
function toDetail(sop: SopSummary, versions: SopVersion[]) { return { sop, versions }; }

export async function listSops(filters: SopFilters, role: string | undefined): Promise<SopSummary[]> { if (!role) throw new HttpError(401, "Authentication required."); return listSopSummaries(filters, managementRole(role)); }
export async function getSopDetailForUser(sopIdValue: unknown, role: string | undefined): Promise<{ sop: SopSummary; versions: SopVersion[] }> {
  if (!role) throw new HttpError(401, "Authentication required."); const sopId = positiveId(sopIdValue, "sopId"); const detail = await getSopDetail(sopId, managementRole(role)); if (!detail) throw new HttpError(404, "SOP not found."); if (!managementRole(role) && detail.sop.status !== "published") throw new HttpError(404, "SOP not found."); return toDetail(detail.sop, detail.versions);
}
export async function getSopVersionForUser(sopIdValue: unknown, versionValue: unknown, role: string | undefined): Promise<SopVersion> { if (!role) throw new HttpError(401, "Authentication required."); const sopId = positiveId(sopIdValue, "sopId"); const sop = await findSop(sopId); if (!sop || (!managementRole(role) && sop.status !== "published")) throw new HttpError(404, "SOP version not found."); const version = normalizeSopVersion(versionValue); const result = await findSopVersion(sopId, version, managementRole(role)); if (!result) throw new HttpError(404, "SOP version not found."); return result; }

export async function createSop(body: unknown, actorUserIdValue: unknown, actorRole: string | undefined) {
  requireSopManagement(actorRole);
  const actorUserId = positiveId(actorUserIdValue, "acting user"); const input = parseInput(body); if (!input.contentJson) throw new HttpError(400, "SOP content is required.");
  const client = await pool.connect();
  try { await client.query("begin"); const created = await insertSop({ ...input, contentJson: input.contentJson, actorUserId }, client); await logAuditEntry({ entityType: "sop", entityId: created.sop.id, actionType: "sop_created", newValues: { sop_id: created.sop.id, sop_code: created.sop.code, version: created.version.version }, changedByUserId: actorUserId }, client); await client.query("commit"); return created; } catch (error) { await client.query("rollback").catch(() => undefined); if (isUniqueViolation(error)) throw new HttpError(409, "SOP code or version already exists."); throw error; } finally { client.release(); }
}

export async function updateSopDraftForUser(sopIdValue: unknown, versionValue: unknown, body: unknown, actorUserIdValue: unknown, actorRole: string | undefined) {
  requireSopManagement(actorRole); const sopId = positiveId(sopIdValue, "sopId"); const version = normalizeSopVersion(versionValue); const existing = await findSop(sopId); if (!existing) throw new HttpError(404, "SOP not found."); if (existing.status === "archived") throw new HttpError(409, "Archived SOPs cannot be edited."); const existingVersion = await findSopVersion(sopId, version, true); if (!existingVersion || existingVersion.status !== "draft") throw new HttpError(409, "Only editable draft versions can be updated."); const input = parseInput({ ...asUnknownRecord(body), code: existing.code, version }, true); if (!input.contentJson) throw new HttpError(400, "SOP content is required.");
  const client = await pool.connect(); try { await client.query("begin"); await client.query("select id from sops where id=$1 for update", [sopId]); const locked = await findSop(sopId, client); const lockedDraft = await findSopVersion(sopId, version, true, client); if (!locked || !lockedDraft || lockedDraft.status !== "draft") throw new HttpError(409, "Only editable draft versions can be updated."); const actorUserId = positiveId(actorUserIdValue, "acting user"); const publishedMetadataFixed = Boolean(locked.currentVersion); if (publishedMetadataFixed && (input.title !== locked.title || input.category !== locked.category)) throw new HttpError(409, "Title and category cannot be changed on an unpublished revision."); const updated = await updateSopDraft({ sopId, version, title: publishedMetadataFixed ? locked.title : input.title, category: publishedMetadataFixed ? locked.category : input.category, contentJson: input.contentJson, changeSummary: input.changeSummary, effectiveDate: input.effectiveDate, actorUserId }, client); await logAuditEntry({ entityType: "sop", entityId: sopId, actionType: "sop_draft_updated", newValues: { sop_id: sopId, sop_code: existing.code, version }, changedByUserId: actorUserId }, client); await client.query("commit"); return updated; } catch (error) { await client.query("rollback").catch(() => undefined); throw error; } finally { client.release(); }
}

export async function createSopRevisionForUser(sopIdValue: unknown, body: unknown, actorUserIdValue: unknown, actorRole: string | undefined) {
  requireSopManagement(actorRole); const sopId = positiveId(sopIdValue, "sopId"); const existing = await findSop(sopId); if (!existing) throw new HttpError(404, "SOP not found."); if (existing.status !== "published") throw new HttpError(409, "A revision can only be created from a published SOP."); const current = await findSopVersion(sopId, existing.currentVersion ?? "", true); if (!current || current.status !== "published") throw new HttpError(409, "The published SOP version is unavailable."); const input = asUnknownRecord(body); const version = normalizeSopVersion(input.version); const changeSummary = requiredText(input.changeSummary ?? input.change_summary, "Change summary"); const effectiveDate = normalizeSopDate(input.effectiveDate ?? input.effective_date); const actorUserId = positiveId(actorUserIdValue, "acting user");
  const client = await pool.connect(); try { await client.query("begin"); await client.query("select id from sops where id=$1 for update", [sopId]); const locked = await findSop(sopId, client); if (!locked || locked.status !== "published") throw new HttpError(409, "A revision can only be created from a published SOP."); const revision = await insertSopRevision({ sopId, version, changeSummary, effectiveDate, actorUserId, contentJson: current.contentJson }, client); await client.query("update sops set updated_by_user_id=$2, updated_at=now() where id=$1", [sopId, actorUserId]); await logAuditEntry({ entityType: "sop", entityId: sopId, actionType: "sop_revision_created", newValues: { sop_id: sopId, sop_code: existing.code, version, source_version: current.version }, changedByUserId: actorUserId }, client); await client.query("commit"); return revision; } catch (error) { await client.query("rollback").catch(() => undefined); if (isUniqueViolation(error)) throw new HttpError(409, "That revision version already exists or a draft revision is already open."); throw error; } finally { client.release(); }
}

export async function publishSopVersionForUser(sopIdValue: unknown, versionValue: unknown, actorUserIdValue: unknown, actorRole: string | undefined) {
  requireSopManagement(actorRole); const sopId = positiveId(sopIdValue, "sopId"); const version = normalizeSopVersion(versionValue); const actorUserId = positiveId(actorUserIdValue, "acting user"); const existing = await findSop(sopId); if (!existing) throw new HttpError(404, "SOP not found."); if (existing.status === "archived") throw new HttpError(409, "Archived SOPs cannot be published."); const draft = await findSopVersion(sopId, version, true); if (!draft || draft.status !== "draft") throw new HttpError(409, "Only a draft version can be published."); const input = parseInput({ title: existing.title, code: existing.code, category: existing.category, version, contentJson: draft.contentJson }); if (!input.contentJson) throw new HttpError(400, "SOP content is required."); validateSopDocument(draft.contentJson, true); if (!draft.effectiveDate) throw new HttpError(400, "Effective date is required before publishing.");
  const client = await pool.connect(); try { await client.query("begin"); await client.query("select id from sops where id=$1 for update", [sopId]); const locked = await findSop(sopId, client); if (!locked) throw new HttpError(404, "SOP not found."); const lockedDraft = await findSopVersion(sopId, version, true, client); if (!lockedDraft || lockedDraft.status !== "draft") throw new HttpError(409, "This draft has already been published or changed."); const published = await publishSopVersion(sopId, version, actorUserId, client); await logAuditEntry({ entityType: "sop", entityId: sopId, actionType: "sop_published", newValues: { sop_id: sopId, sop_code: locked.code, version }, changedByUserId: actorUserId }, client); await client.query("commit"); return published; } catch (error) { await client.query("rollback").catch(() => undefined); throw error; } finally { client.release(); }
}

export async function archiveSopForUser(sopIdValue: unknown, actorUserIdValue: unknown, actorRole: string | undefined) { requireSopManagement(actorRole); const sopId = positiveId(sopIdValue, "sopId"); const actorUserId = positiveId(actorUserIdValue, "acting user"); const client = await pool.connect(); try { await client.query("begin"); await client.query("select id from sops where id=$1 for update", [sopId]); const existing = await findSop(sopId, client); if (!existing) throw new HttpError(404, "SOP not found."); if (existing.status === "archived") throw new HttpError(409, "SOP is already archived."); const archived = await archiveSop(sopId, actorUserId, client); await logAuditEntry({ entityType: "sop", entityId: sopId, actionType: "sop_archived", newValues: { sop_id: sopId, sop_code: archived.code, version: archived.currentVersion }, changedByUserId: actorUserId }, client); await client.query("commit"); return archived; } catch (error) { await client.query("rollback").catch(() => undefined); throw error; } finally { client.release(); } }

export function validateSopFilters(input: unknown): SopFilters { const query = asUnknownRecord(input); const status = String(query.status ?? "").trim(); if (status && !(SOP_STATUSES as readonly string[]).includes(status)) throw new HttpError(400, "Status is invalid."); return { search: String(query.search ?? "").trim() || null, category: String(query.category ?? "").trim() || null, status: status || null }; }
