import { readFileSync } from "node:fs";
import type { SopDocument, SopSectionDocument, SopSummary, SopVersion } from "./types.js";
import { SOP_SECTION_DEFINITIONS } from "./constants.js";

export type SopPrintStatus = "CURRENT" | "DRAFT" | "SUPERSEDED" | "ARCHIVED";

export interface SopPrintDocument {
  sop: SopSummary;
  version: SopVersion;
  status: SopPrintStatus;
  generatedAt: Date;
  logoDataUrl?: string;
}

interface TiptapNode {
  type?: unknown;
  text?: unknown;
  attrs?: unknown;
  content?: unknown;
  marks?: unknown;
}

const SECTION_LABELS: Record<string, { en: string; ar: string }> = {
  purpose: { en: "Purpose", ar: "الغرض" },
  scope: { en: "Scope", ar: "النطاق" },
  responsibilities: { en: "Responsibilities", ar: "المسؤوليات" },
  definitions: { en: "Definitions / Abbreviations", ar: "التعريفات والاختصارات" },
  safety: { en: "Safety / Precautions", ar: "السلامة والاحتياطات" },
  procedure: { en: "Procedure", ar: "الإجراء" },
  documentation: { en: "Documentation / Records", ar: "التوثيق والسجلات" },
  references: { en: "References", ar: "المراجع" },
};

const PRINT_COPY = {
  hospitalEn: "National Cancer Center Benghazi",
  departmentEn: "Diagnostic & Interventional Radiology Department",
  hospitalAr: "المركز الوطني للأورام بنغازي",
  departmentAr: "قسم الأشعة التشخيصية والتداخلية",
  documentAr: "إجراء تشغيلي قياسي",
  documentEn: "STANDARD OPERATING PROCEDURE",
  sopCodeEn: "SOP Code",
  sopCodeAr: "رمز الإجراء",
  versionEn: "Version",
  versionAr: "الإصدار",
  categoryEn: "Category",
  categoryAr: "الفئة",
  effectiveDateEn: "Effective Date",
  effectiveDateAr: "تاريخ السريان",
  statusEn: "Document Status",
  statusAr: "حالة الوثيقة",
  currentEn: "CURRENT",
  draftEn: "DRAFT",
  supersededEn: "SUPERSEDED",
  archivedEn: "ARCHIVED",
  revisionEn: "Revision information",
  revisionAr: "معلومات المراجعة",
  changeSummaryEn: "Change Summary",
  changeSummaryAr: "ملخص التغيير",
  publishedByEn: "Published By",
  publishedByAr: "نشر بواسطة",
  publishedAtEn: "Published At",
  publishedAtAr: "تاريخ النشر",
  lastEditedByEn: "Last Edited By",
  lastEditedByAr: "آخر تعديل بواسطة",
  lastEditedAtEn: "Last Edited At",
  lastEditedAtAr: "تاريخ آخر تعديل",
  generatedEn: "Generated by RISpro",
  generatedAr: "تم الإنشاء بواسطة RISpro",
} as const;

const STATUS_LABELS: Record<SopPrintStatus, string> = {
  CURRENT: PRINT_COPY.currentEn,
  DRAFT: PRINT_COPY.draftEn,
  SUPERSEDED: PRINT_COPY.supersededEn,
  ARCHIVED: PRINT_COPY.archivedEn,
};

const DEFAULT_LOGO_DATA_URL = readAssetDataUrl(
  new URL("../../../assets/nccb-logo.png", import.meta.url),
  "image/png",
);

const PRINT_FONT_CSS = [
  ["Noto Naskh Arabic", "400", "../../../frontend/src/assets/fonts/NotoNaskhArabic-Regular.ttf"],
  ["Noto Naskh Arabic", "700", "../../../frontend/src/assets/fonts/NotoNaskhArabic-Bold.ttf"],
].map(([family, weight, asset]) => {
  try {
    return `@font-face{font-family:"${family}";font-style:normal;font-weight:${weight};src:url(${readAssetDataUrl(new URL(asset, import.meta.url), "font/ttf")}) format("truetype");}`;
  } catch {
    return "";
  }
}).join("");

function readAssetDataUrl(asset: URL, mimeType: string): string {
  return `data:${mimeType};base64,${readFileSync(asset).toString("base64")}`;
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : {};
}

function asNodes(value: unknown): TiptapNode[] {
  return Array.isArray(value) ? value.filter((node): node is TiptapNode => Boolean(node && typeof node === "object")) : [];
}

function escapeHtml(value: unknown): string {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeAttribute(value: string): string {
  return escapeHtml(value);
}

function blockAttributes(node: TiptapNode): string {
  const attrs = asRecord(node.attrs);
  const dir = attrs.dir === "rtl" || attrs.dir === "ltr" || attrs.dir === "auto" ? attrs.dir : null;
  const textAlign = attrs.textAlign === "left" || attrs.textAlign === "center" || attrs.textAlign === "right" || attrs.textAlign === "justify"
    ? attrs.textAlign
    : null;
  return `${dir ? ` dir="${dir}"` : ""}${textAlign ? ` style="text-align:${textAlign}"` : ""}`;
}

function nodeText(node: TiptapNode): string {
  const ownText = typeof node.text === "string" ? node.text : "";
  const children = asNodes(node.content).map(nodeText).join("");
  return `${ownText}${children}`;
}

function renderMarks(value: string, marks: unknown): string {
  return asNodes(marks).reduce((result, mark) => {
    switch (mark.type) {
      case "bold": return `<strong>${result}</strong>`;
      case "italic": return `<em>${result}</em>`;
      case "underline": return `<u>${result}</u>`;
      case "code": return `<code>${result}</code>`;
      case "strike": return `<del>${result}</del>`;
      default: return result;
    }
  }, escapeHtml(value));
}

function renderNode(node: TiptapNode): string {
  const type = typeof node.type === "string" ? node.type : "";
  const attrs = blockAttributes(node);
  const children = asNodes(node.content).map(renderNode).join("");
  switch (type) {
    case "text":
      return renderMarks(typeof node.text === "string" ? node.text : "", node.marks);
    case "hardBreak":
      return "<br>";
    case "paragraph":
      return `<p${attrs}>${children}</p>`;
    case "heading": {
      const level = Number(asRecord(node.attrs).level);
      const safeLevel = Number.isInteger(level) && level >= 1 && level <= 6 ? level : 2;
      return `<h${safeLevel}${attrs}>${children}</h${safeLevel}>`;
    }
    case "bulletList":
      return `<ul${attrs}>${children}</ul>`;
    case "orderedList":
      return `<ol${attrs}>${children}</ol>`;
    case "listItem":
      return `<li${attrs}>${children}</li>`;
    case "blockquote":
      return `<blockquote${attrs}>${children}</blockquote>`;
    case "horizontalRule":
      return "<hr>";
    case "codeBlock":
      return `<pre${attrs}><code>${escapeHtml(nodeText(node))}</code></pre>`;
    case "table":
      return renderTable(node);
    case "tableRow":
      return `<tr${attrs}>${children}</tr>`;
    case "tableHeader":
      return `<th${attrs}>${children}</th>`;
    case "tableCell":
      return `<td${attrs}>${children}</td>`;
    case "doc":
    case "sop":
      return children;
    default:
      // Unknown nodes are deliberately reduced to their safe children. Stored HTML is never emitted.
      return children || (typeof node.text === "string" ? escapeHtml(node.text) : "");
  }
}

function renderTable(node: TiptapNode): string {
  const rows = asNodes(node.content).filter((row) => row.type === "tableRow");
  const firstRow = rows[0];
  const hasHeader = Boolean(firstRow && asNodes(firstRow.content).some((cell) => cell.type === "tableHeader"));
  const renderRows = (items: TiptapNode[]) => items.map((row) => renderNode(row)).join("");
  return `<table class="content-table">${hasHeader ? `<thead>${renderRows([firstRow!])}</thead>` : ""}<tbody>${renderRows(hasHeader ? rows.slice(1) : rows)}</tbody></table>`;
}

function meaningfulSection(section: SopSectionDocument): boolean {
  return nodeText(section.content).trim().length > 0;
}

function formatDate(value: string | null): string {
  if (!value) return "—";
  const date = new Date(/^\d{4}-\d{2}-\d{2}$/.test(value) ? `${value}T00:00:00Z` : value);
  if (Number.isNaN(date.getTime())) return "—";
  return new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(date);
}

function formatDateTime(value: string | Date | null): string {
  if (!value) return "—";
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return "—";
  return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short", timeZone: "Africa/Tripoli" }).format(date);
}

function statusClass(status: SopPrintStatus): string {
  return status.toLowerCase();
}

function revisionPeople(document: SopPrintDocument): { byLabel: string; byValue: string; atLabel: string; atValue: string } {
  if (document.version.status === "draft") {
    return {
      byLabel: `${PRINT_COPY.lastEditedByEn} / ${PRINT_COPY.lastEditedByAr}`,
      byValue: document.version.updatedByName ?? document.version.createdByName ?? document.version.createdByUsername ?? "—",
      atLabel: `${PRINT_COPY.lastEditedAtEn} / ${PRINT_COPY.lastEditedAtAr}`,
      atValue: formatDateTime(document.version.updatedAt),
    };
  }
  return {
    byLabel: `${PRINT_COPY.publishedByEn} / ${PRINT_COPY.publishedByAr}`,
    byValue: document.version.publishedByName ?? document.version.createdByName ?? document.version.createdByUsername ?? "—",
    atLabel: `${PRINT_COPY.publishedAtEn} / ${PRINT_COPY.publishedAtAr}`,
    atValue: formatDateTime(document.version.publishedAt ?? document.version.updatedAt),
  };
}

function metadataCell(en: string, ar: string, value: string): string {
  return `<div class="metadata-cell"><dt>${escapeHtml(en)}<span class="metadata-ar" dir="rtl">${escapeHtml(ar)}</span></dt><dd dir="auto">${escapeHtml(value)}</dd></div>`;
}

function revisionCell(label: string, value: string): string {
  return `<div class="revision-cell"><dt>${escapeHtml(label)}</dt><dd dir="auto">${escapeHtml(value)}</dd></div>`;
}

function orderedSections(document: SopDocument): SopSectionDocument[] {
  const order = new Map(SOP_SECTION_DEFINITIONS.map((section, index) => [section.key, index]));
  return [...document.sections].sort((left, right) => (order.get(left.key) ?? 999) - (order.get(right.key) ?? 999));
}

function renderSection(section: SopSectionDocument): string {
  const label = SECTION_LABELS[section.key] ?? { en: section.title, ar: "" };
  return `<tr class="document-row"><td><section class="sop-section"><h2 class="section-heading"><span dir="ltr">${escapeHtml(label.en)}</span><span class="section-heading-ar" dir="rtl">${escapeHtml(label.ar)}</span></h2><div class="section-content">${renderNode(section.content)}</div></section></td></tr>`;
}

function renderRevisionInformation(document: SopPrintDocument): string {
  const people = revisionPeople(document);
  return `<tr class="document-row"><td><section class="revision-information"><h2 class="section-heading"><span dir="ltr">${PRINT_COPY.revisionEn}</span><span class="section-heading-ar" dir="rtl">${PRINT_COPY.revisionAr}</span></h2><dl class="revision-grid">${revisionCell(`${PRINT_COPY.versionEn} / ${PRINT_COPY.versionAr}`, document.version.version)}${revisionCell(`${PRINT_COPY.effectiveDateEn} / ${PRINT_COPY.effectiveDateAr}`, formatDate(document.version.effectiveDate))}${revisionCell(`${PRINT_COPY.changeSummaryEn} / ${PRINT_COPY.changeSummaryAr}`, document.version.changeSummary || "—")}${revisionCell(people.byLabel, people.byValue)}${revisionCell(people.atLabel, people.atValue)}</dl><p class="generated-line"><span dir="ltr">${PRINT_COPY.generatedEn}</span><span dir="rtl">${PRINT_COPY.generatedAr}</span> · ${escapeHtml(formatDateTime(document.generatedAt))}</p></section></td></tr>`;
}

export function deriveSopPrintStatus(sop: SopSummary, version: SopVersion): SopPrintStatus {
  if (sop.status === "archived") return "ARCHIVED";
  if (version.status === "draft") return "DRAFT";
  if (version.status === "published" && sop.currentVersion === version.version) return "CURRENT";
  return "SUPERSEDED";
}

export function buildSopPdfFooterTemplate(code: string, version: string): string {
  return `<div style="width:100%;padding:0 13mm;font:600 7px Arial,sans-serif;color:#4b5563;display:flex;justify-content:space-between;box-sizing:border-box"><span>${escapeHtml(code)} · Version ${escapeHtml(version)}</span><span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span></div>`;
}

export function buildSopPrintHtml(document: SopPrintDocument): string {
  const status = document.status;
  const sections = orderedSections(document.version.contentJson)
    .filter((section) => section.required || meaningfulSection(section))
    .map(renderSection)
    .join("");
  const logo = document.logoDataUrl ?? DEFAULT_LOGO_DATA_URL;
  const title = escapeHtml(document.sop.title);
  const statusLabel = STATUS_LABELS[status];
  const watermark = status === "CURRENT" ? "" : `<div class="status-watermark" aria-hidden="true">${statusLabel}</div>`;

  return `<!doctype html><html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title} · ${escapeHtml(document.sop.code)} · v${escapeHtml(document.version.version)}</title><style>
${PRINT_FONT_CSS}
@page { size: A4 portrait; margin: 14mm 13mm 18mm; }
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body { color: #18212b; background: #eef0f2; font-family: Arial, "Noto Naskh Arabic", Tahoma, sans-serif; font-size: 9.5pt; line-height: 1.45; }
.print-frame { width: 100%; max-width: 210mm; margin: 10mm auto; border-collapse: separate; border-spacing: 0; table-layout: fixed; background: #fff; }
.print-frame > thead { display: table-header-group; }
.print-frame > thead th, .document-row > td { padding: 0; border: 0; vertical-align: top; }
.running-header { padding: 1.5mm 0 2mm; border-bottom: 0.25mm solid #9aa3ad; color: #4b5563; font-size: 7pt; font-weight: 700; display: flex; justify-content: space-between; gap: 4mm; }
.running-header span { min-width: 0; overflow-wrap: anywhere; }
.running-header .running-status { color: #374151; }
.document-content { position: relative; z-index: 2; }
.status-watermark { position: fixed; z-index: 1; inset: 0; display: grid; place-items: center; color: rgba(107, 114, 128, 0.11); font-size: 42pt; font-weight: 800; letter-spacing: 0.12em; transform: rotate(-30deg); pointer-events: none; user-select: none; }
.institutional-header { display: grid; grid-template-columns: minmax(0, 1fr) 30mm minmax(0, 1fr); align-items: center; gap: 4mm; padding: 1mm 0 3mm; border-bottom: 0.65mm solid #18212b; }
.institutional-english { grid-column: 1; min-width: 0; text-align: center; direction: ltr; }
.institutional-arabic { grid-column: 3; min-width: 0; text-align: center; direction: rtl; }
.institutional-logo-cell { grid-column: 2; display: grid; place-items: center; }
.institutional-logo { display: block; width: 25mm; height: 25mm; object-fit: contain; }
.hospital-name { margin: 0; font-size: 12pt; font-weight: 800; line-height: 1.25; }
.department-name { margin: 1mm 0 0; font-size: 8.5pt; line-height: 1.3; }
.document-title { padding: 4mm 0 3mm; text-align: center; }
.document-title-ar { margin: 0; font-family: "Noto Naskh Arabic", Tahoma, Arial, sans-serif; font-size: 15pt; font-weight: 700; line-height: 1.25; }
.document-title-en { margin: 1mm 0 0; font-size: 12pt; font-weight: 800; letter-spacing: 0.13em; line-height: 1.2; }
.sop-title { margin: 2.5mm 0 0; font-size: 17pt; line-height: 1.25; overflow-wrap: anywhere; }
.status-pill { display: inline-block; margin-top: 2mm; padding: 1.3mm 4mm; border: 0.35mm solid #4b5563; border-radius: 999px; font-size: 8pt; font-weight: 800; letter-spacing: 0.08em; }
.status-pill.draft { color: #92400e; border-color: #b45309; }
.status-pill.superseded, .status-pill.archived { color: #4b5563; border-color: #6b7280; }
.status-pill.current { color: #166534; border-color: #15803d; }
.metadata-grid { display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); margin: 2mm 0 5mm; border: 0.35mm solid #68727c; }
.metadata-cell { min-width: 0; padding: 2.3mm 2.5mm; border-inline-start: 0.2mm solid #b5bdc5; }
.metadata-cell:first-child { border-inline-start: 0; }
.metadata-cell dt, .revision-cell dt { color: #46515b; font-size: 7.5pt; font-weight: 700; }
.metadata-ar { display: block; margin-top: 0.5mm; font-family: "Noto Naskh Arabic", Tahoma, Arial, sans-serif; font-weight: 700; }
.metadata-cell dd { margin: 1.2mm 0 0; font-size: 9pt; font-weight: 700; overflow-wrap: anywhere; }
.sop-section, .revision-information { margin: 0 0 4mm; border: 0.3mm solid #68727c; }
.section-heading { display: flex; justify-content: space-between; align-items: baseline; gap: 4mm; margin: 0; padding: 2mm 3mm; border-bottom: 0.25mm solid #68727c; background: #eef0f2; color: #18212b; font-size: 10.5pt; font-weight: 800; line-height: 1.3; break-after: avoid-page; page-break-after: avoid; }
.section-heading-ar { font-family: "Noto Naskh Arabic", Tahoma, Arial, sans-serif; font-size: 11pt; font-weight: 700; }
.section-content { min-width: 0; padding: 3mm; overflow-wrap: anywhere; word-break: break-word; }
.section-content p { margin: 0 0 2.5mm; orphans: 3; widows: 3; }
.section-content p:last-child { margin-bottom: 0; }
.section-content h1, .section-content h2, .section-content h3, .section-content h4, .section-content h5, .section-content h6 { margin: 3mm 0 1.5mm; line-height: 1.3; break-after: avoid-page; page-break-after: avoid; }
.section-content ul, .section-content ol { margin: 1mm 0 2.5mm; padding-inline-start: 7mm; }
.section-content li { padding-inline-start: 1mm; margin: 0 0 1.3mm; break-inside: avoid-page; page-break-inside: avoid; }
.section-content blockquote { margin: 2mm 0; padding: 2mm 3mm; border-inline-start: 1mm solid #9aa3ad; background: #f7f8f9; }
.section-content hr { margin: 4mm 0; border: 0; border-top: 0.25mm solid #9aa3ad; }
.section-content pre { margin: 2mm 0; padding: 2.5mm; overflow-wrap: anywhere; white-space: pre-wrap; background: #f3f4f6; font: 8.5pt ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
.section-content code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
.content-table { width: 100%; max-width: 100%; margin: 2mm 0 3mm; border-collapse: collapse; table-layout: fixed; overflow-wrap: anywhere; word-break: break-word; }
.content-table thead { display: table-header-group; }
.content-table th, .content-table td { min-width: 0; padding: 2mm 2.2mm; border: 0.25mm solid #9aa3ad; vertical-align: top; text-align: start; overflow-wrap: anywhere; word-break: break-word; }
.content-table th { background: #e5e7eb; font-weight: 800; }
.content-table tr { break-inside: avoid-page; page-break-inside: avoid; }
.revision-grid { display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); margin: 0; }
.revision-cell { min-width: 0; padding: 2.5mm 2.5mm; border-inline-start: 0.2mm solid #b5bdc5; }
.revision-cell:first-child { border-inline-start: 0; }
.revision-cell dd { margin: 1mm 0 0; overflow-wrap: anywhere; }
.generated-line { margin: 0; padding: 2mm 3mm; border-top: 0.2mm solid #b5bdc5; color: #46515b; font-size: 7.5pt; display: flex; justify-content: space-between; gap: 4mm; }
@media screen and (max-width: 760px) { body { background: #fff; } .print-frame { margin: 0; } .institutional-header { grid-template-columns: 1fr; } .institutional-english, .institutional-logo-cell, .institutional-arabic { grid-column: 1; } .metadata-grid, .revision-grid { grid-template-columns: 1fr 1fr; } .metadata-cell:nth-child(odd), .revision-cell:nth-child(odd) { border-inline-start: 0; } .metadata-cell:nth-child(n+3), .revision-cell:nth-child(n+3) { border-top: 0.2mm solid #b5bdc5; } }
@media print { body { background: #fff; } .print-frame { max-width: none; margin: 0; } .running-header { padding-top: 0; } .status-watermark { position: fixed; } .sop-section, .revision-information { break-inside: auto; page-break-inside: auto; } .document-title, .metadata-grid { break-inside: avoid-page; page-break-inside: avoid; } a { color: inherit; text-decoration: none; } }
</style></head><body>${watermark}<table class="print-frame"><thead><tr><th><div class="running-header"><span>NCCB · ${escapeHtml(document.sop.code)} · Version ${escapeHtml(document.version.version)}</span><span class="running-status">${escapeHtml(statusLabel)}</span></div></th></tr></thead><tbody><tr class="document-row"><td><main class="document-content"><header class="institutional-header"><div class="institutional-english"><p class="hospital-name">${PRINT_COPY.hospitalEn}</p><p class="department-name">${PRINT_COPY.departmentEn}</p></div><div class="institutional-logo-cell"><img class="institutional-logo" src="${escapeAttribute(logo)}" alt="NCCB logo"></div><div class="institutional-arabic"><p class="hospital-name">${PRINT_COPY.hospitalAr}</p><p class="department-name">${PRINT_COPY.departmentAr}</p></div></header><section class="document-title"><p class="document-title-ar" dir="rtl">${PRINT_COPY.documentAr}</p><p class="document-title-en" dir="ltr">${PRINT_COPY.documentEn}</p><h1 class="sop-title" dir="auto">${title}</h1><span class="status-pill ${statusClass(status)}">${escapeHtml(statusLabel)}</span></section><dl class="metadata-grid">${metadataCell(PRINT_COPY.sopCodeEn, PRINT_COPY.sopCodeAr, document.sop.code)}${metadataCell(PRINT_COPY.versionEn, PRINT_COPY.versionAr, document.version.version)}${metadataCell(PRINT_COPY.categoryEn, PRINT_COPY.categoryAr, document.sop.category)}${metadataCell(PRINT_COPY.effectiveDateEn, PRINT_COPY.effectiveDateAr, formatDate(document.version.effectiveDate))}${metadataCell(PRINT_COPY.statusEn, PRINT_COPY.statusAr, statusLabel)}</dl></main></td></tr>${sections}${renderRevisionInformation(document)}</tbody></table></body></html>`;
}

export const __sopPrintTestables = {
  escapeHtml,
  renderNode,
  meaningfulSection,
  formatDate,
  DEFAULT_LOGO_DATA_URL,
};
