import { useEffect, useState, type ReactNode } from "react";
import { Badge, Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/shared";
import { ApiError } from "@/lib/api-client";
import { chooseLocalized, t } from "@/lib/i18n";
import { useCreateV2DayExamMixQuota, useCreateV2DayExamRestriction, useCreateV2DayModalityBlock, useRemoveV2DayManagementRule, useV2DayManagementContext } from "@/v2/appointments/api";
import type { DayManagementContextDto, DayManagementExamTypeDto, DayManagementRemovableRuleFamily, DayManagementRuleType } from "@/v2/appointments/types";

interface ManageDayDialogProps { open: boolean; onClose: () => void; language: "ar" | "en"; modalityId: number | null; modalityLabel: string; date: string; dateLabel: string; }
type Action = DayManagementRuleType | null;
type RemoveTarget = { family: DayManagementRemovableRuleFamily; ruleId: number; title: string } | null;
const scopeKey = { specific_date: "calendar.manageDaySpecificDate", date_range: "calendar.manageDayDateRange", weekly_recurrence: "calendar.manageDayWeeklyRecurrence", yearly_recurrence: "calendar.manageDayYearlyRecurrence" } as const;
function examTypeNames(language: "ar" | "en", items: DayManagementExamTypeDto[]) { return items.map((item) => chooseLocalized(language, item.nameAr, item.nameEn) || item.name || String(item.id)).join(", "); }
function capability(language: "ar" | "en", type: DayManagementRuleType) { const keys = { block_modality: ["calendar.manageDayBlockModality", "calendar.manageDayBlockModalityHelp"], restrict_exam_types: ["calendar.manageDayRestrictExamTypes", "calendar.manageDayRestrictExamTypesHelp"], set_exam_mix_quota: ["calendar.manageDaySetExamMixQuota", "calendar.manageDaySetExamMixQuotaHelp"] } as const; return { title: t(language, keys[type][0]), help: t(language, keys[type][1]) }; }

export function ManageDayDialog({ open, onClose, language, modalityId, modalityLabel, date, dateLabel }: ManageDayDialogProps) {
  const contextQuery = useV2DayManagementContext(open && modalityId != null ? { modalityId, date, policySetKey: "default" } : undefined);
  const block = useCreateV2DayModalityBlock(), restriction = useCreateV2DayExamRestriction(), quota = useCreateV2DayExamMixQuota(), remove = useRemoveV2DayManagementRule();
  const context = contextQuery.data; const [action, setAction] = useState<Action>(null); const [removeTarget, setRemoveTarget] = useState<RemoveTarget>(null); const [reason, setReason] = useState(""); const [examTypeIds, setExamTypeIds] = useState<number[]>([]); const [isOverridable, setIsOverridable] = useState(false); const [effectMode, setEffectMode] = useState<"hard_restriction" | "restriction_overridable">("hard_restriction"); const [dailyLimit, setDailyLimit] = useState(""); const [error, setError] = useState<string | null>(null); const [feedback, setFeedback] = useState<string | null>(null);
  const hasDraft = context?.policy.draft != null, published = context?.policy.published; const pending = block.isPending || restriction.isPending || quota.isPending || remove.isPending;
  const resetEditorState = () => { setAction(null); setRemoveTarget(null); setReason(""); setExamTypeIds([]); setIsOverridable(false); setEffectMode("hard_restriction"); setDailyLimit(""); setError(null); };
  const resetAllInteractionState = () => { resetEditorState(); setFeedback(null); };
  useEffect(() => {
    setAction(null); setRemoveTarget(null); setReason(""); setExamTypeIds([]); setIsOverridable(false); setEffectMode("hard_restriction"); setDailyLimit(""); setError(null); setFeedback(null);
  }, [open, date, modalityId]);
  const handleClose = () => { if (pending) return; resetAllInteractionState(); onClose(); };
  const refetchError = (caught: unknown) => { const codes = caught instanceof ApiError ? caught.reasonCodes : []; if (codes.includes("day_management_context_stale")) { setError(t(language, "calendar.manageDayStaleContext")); void contextQuery.refetch(); } else if (codes.includes("day_management_draft_conflict")) { setError(t(language, "calendar.manageDayChangesBlockedByDraft", { version: context?.policy.draft?.versionNo ?? "" })); void contextQuery.refetch(); } else setError(caught instanceof Error ? caught.message : t(language, "calendar.manageDayMutationError")); };
  const base = () => published && modalityId != null ? { policySetKey: "default", modalityId, date, expectedPublishedVersionId: published.id, reason } : null;
  const submit = async () => { if (pending) return; const payload = base(); if (!payload) return; if (reason.trim().length < 3) return setError(t(language, "calendar.manageDayReason")); setError(null); try { if (action === "block_modality") await block.mutateAsync({ ...payload, isOverridable }); if (action === "restrict_exam_types") { if (!examTypeIds.length) return setError(t(language, "calendar.manageDayExamTypesRequired")); await restriction.mutateAsync({ ...payload, examTypeIds, effectMode }); } if (action === "set_exam_mix_quota") { if (!examTypeIds.length) return setError(t(language, "calendar.manageDayExamTypesRequired")); const trimmedLimit = dailyLimit.trim(); const parsedLimit = Number(trimmedLimit); const capacity = context?.modality.dailyCapacity; if (!trimmedLimit || !Number.isFinite(parsedLimit) || !Number.isInteger(parsedLimit) || parsedLimit < 1 || (typeof capacity === "number" && Number.isFinite(capacity) && capacity > 0 && parsedLimit > capacity)) return setError(t(language, "calendar.manageDayMutationError")); await quota.mutateAsync({ ...payload, examTypeIds, dailyLimit: parsedLimit }); } setFeedback(t(language, "calendar.manageDayMutationSuccess")); resetEditorState(); } catch (caught) { refetchError(caught); } };
  const submitRemoval = async () => { if (pending) return; const payload = base(); if (!payload || !removeTarget) return; if (reason.trim().length < 3) return setError(t(language, "calendar.manageDayReason")); try { await remove.mutateAsync({ family: removeTarget.family, ruleId: removeTarget.ruleId, input: payload }); setFeedback(t(language, "calendar.manageDayRemovalSuccess")); resetEditorState(); } catch (caught) { refetchError(caught); } };
  const cancelEditor = () => { if (pending) return; resetEditorState(); };
  const openAction = (next: Action) => { if (pending) return; resetAllInteractionState(); setAction(next); };
  const openRemoval = (family: DayManagementRemovableRuleFamily, ruleId: number, title: string) => { if (pending) return; resetAllInteractionState(); setRemoveTarget({ family, ruleId, title }); };
  const toggle = (id: number) => setExamTypeIds((ids) => ids.includes(id) ? ids.filter((value) => value !== id) : [...ids, id]);
  const removeControl = (family: DayManagementRemovableRuleFamily, rule: { id: number; ruleType: string; title: string | null }) => rule.ruleType === "specific_date" ? <button type="button" disabled={hasDraft || pending} onClick={() => openRemoval(family, rule.id, rule.title || t(language, "calendar.manageDayRemoveRule"))}>{t(language, "calendar.manageDayRemoveRule")}</button> : undefined;
  return <Dialog open={open} onClose={handleClose}><DialogContent maxWidth="920px" className="text-left"><DialogHeader showClose={!pending} closeLabel={t(language, "common.dismiss")}><div><DialogTitle>{t(language, "calendar.manageDay")}</DialogTitle><DialogDescription>{t(language, "calendar.manageDayDescription", { date: dateLabel, modality: modalityLabel })}</DialogDescription></div></DialogHeader>
    {contextQuery.isLoading ? <p>{t(language, "common.loading")}</p> : null}{contextQuery.isError ? <p>{t(language, "calendar.manageDayLoadError")}</p> : null}{feedback ? <p role="status">{feedback}</p> : null}
    {context ? <div className="space-y-6"><section><h4>{t(language, "calendar.manageDaySummary")}</h4><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Summary label={t(language, "calendar.capacitySummary", { capacity: context.modality.dailyCapacity ?? t(language, "common.na"), booked: context.bookingSummary.bookedTotal })} value={context.modality.dailyCapacity ?? t(language, "common.na")} /><Summary label={t(language, "calendar.manageDayActiveBookings")} value={context.bookingSummary.bookedTotal} /><Summary label={t(language, "calendar.oncologyLabel")} value={context.bookingSummary.oncologyBooked} /><Summary label={t(language, "calendar.nonOncologyLabel")} value={context.bookingSummary.nonOncologyBooked} /></div>{context.bookingSummary.bookedTotal > 0 ? <p>{t(language, "calendar.manageDayExistingBookingsNotice")}</p> : null}</section>
      <section><h4>{t(language, "calendar.manageDayPolicyStatus")}</h4>{published ? <p>{t(language, "calendar.manageDayPublishedVersion", { version: published.versionNo })}</p> : <p>{t(language, "calendar.manageDayNoPublishedPolicy")}</p>}{context.policy.draft ? <p>{t(language, "calendar.manageDayDraftWarning", { version: context.policy.draft.versionNo })}</p> : null}</section>
      <section><h4>{t(language, "calendar.manageDayRulesAffecting")}</h4>{context.effectiveRules.modalityBlocks.length + context.effectiveRules.examTypeRestrictions.length + context.effectiveRules.examMixQuotas.length === 0 ? <p>{t(language, "calendar.manageDayNoEffectiveRules")}</p> : <div>{context.effectiveRules.modalityBlocks.map((rule) => <Rule key={`b${rule.id}`} title={rule.title || t(language, "calendar.manageDayModalityBlock")} scope={t(language, scopeKey[rule.ruleType])} badge={<Badge variant={rule.isOverridable ? "warning" : "error"} size="sm">{t(language, rule.isOverridable ? "calendar.manageDayOverridable" : "calendar.manageDayHardBlock")}</Badge>} notes={rule.notes} action={removeControl("block_modality", rule)} />)}{context.effectiveRules.examTypeRestrictions.map((rule) => <Rule key={`r${rule.id}`} title={rule.title || t(language, "calendar.manageDayExamRestriction")} scope={t(language, scopeKey[rule.ruleType])} details={examTypeNames(language, rule.examTypes)} notes={rule.notes} action={removeControl("restrict_exam_types", rule)} />)}{context.effectiveRules.examMixQuotas.map((rule) => <Rule key={`q${rule.id}`} title={rule.title || t(language, "calendar.manageDayExamMixQuota")} scope={t(language, scopeKey[rule.ruleType])} details={`${t(language, "calendar.manageDayDailyLimit")}: ${rule.dailyLimit} · ${examTypeNames(language, rule.examTypes)}`} action={removeControl("set_exam_mix_quota", rule)} />)}</div>}</section>
      <section><h4>{t(language, "calendar.manageDayGlobalPolicy")}</h4><p>{t(language, "calendar.manageDayGlobalPolicyHelp")}</p>{context.globalConstraints.categoryDailyLimits.length + context.globalConstraints.specialQuotas.length === 0 && !context.globalConstraints.closedWeekday ? <p>{t(language, "calendar.manageDayNoGlobalConstraints")}</p> : <div>{context.globalConstraints.categoryDailyLimits.map((rule) => <p key={rule.id}>{t(language, rule.caseCategory === "oncology" ? "calendar.oncologyLabel" : "calendar.nonOncologyLabel")}: {rule.dailyLimit}</p>)}{context.globalConstraints.specialQuotas.map((rule) => <Rule key={rule.id} title={rule.title || rule.logicalKey} details={`${t(language, "calendar.manageDayExtraSlots")}: ${rule.dailyExtraSlots} · ${examTypeNames(language, rule.examTypes)}`} />)}{context.globalConstraints.closedWeekday ? <p>{t(language, "calendar.manageDayClosedWeekday", { weekday: context.globalConstraints.closedWeekday })}</p> : null}</div>}</section>
      <section><h4>{t(language, "calendar.manageDayDayRuleTypes")}</h4>{hasDraft ? <p>{t(language, "calendar.manageDayChangesBlockedByDraft", { version: context.policy.draft!.versionNo })}</p> : null}<div className="grid gap-2 sm:grid-cols-3">{context.supportedDayRuleTypes.map((type) => { const item = capability(language, type); return <button type="button" aria-label={item.title} key={type} disabled={hasDraft || !published || pending} onClick={() => openAction(type)}><strong>{item.title}</strong><span>{item.help}</span></button>; })}</div></section>
      {action ? <Form action={action} language={language} context={context} modalityLabel={modalityLabel} dateLabel={dateLabel} reason={reason} setReason={setReason} examTypeIds={examTypeIds} toggle={toggle} isOverridable={isOverridable} setIsOverridable={setIsOverridable} effectMode={effectMode} setEffectMode={setEffectMode} dailyLimit={dailyLimit} setDailyLimit={setDailyLimit} error={error} pending={pending} onCancel={cancelEditor} onSubmit={submit} /> : null}
      {removeTarget ? <section><strong>{removeTarget.title}</strong><p>{t(language, "calendar.manageDayRemoveRuleHelp")}</p><Reason language={language} value={reason} onChange={setReason} error={error} disabled={pending} /><button type="button" disabled={pending} onClick={cancelEditor}>{t(language, "common.cancel")}</button><button type="button" disabled={pending || hasDraft} onClick={submitRemoval}>{t(language, "calendar.manageDayRemoveRuleConfirm")}</button></section> : null}
    </div> : null}</DialogContent></Dialog>;
}
function Form({ action, language, context, modalityLabel, dateLabel, reason, setReason, examTypeIds, toggle, isOverridable, setIsOverridable, effectMode, setEffectMode, dailyLimit, setDailyLimit, error, pending, onCancel, onSubmit }: { action: Exclude<Action, null>; language: "ar" | "en"; context: DayManagementContextDto; modalityLabel: string; dateLabel: string; reason: string; setReason: (v: string) => void; examTypeIds: number[]; toggle: (id: number) => void; isOverridable: boolean; setIsOverridable: (v: boolean) => void; effectMode: "hard_restriction" | "restriction_overridable"; setEffectMode: (v: "hard_restriction" | "restriction_overridable") => void; dailyLimit: string; setDailyLimit: (v: string) => void; error: string | null; pending: boolean; onCancel: () => void; onSubmit: () => void; }) { const key = action === "block_modality" ? "calendar.manageDayBlockConfirm" : action === "restrict_exam_types" ? "calendar.manageDayRestrictionConfirm" : "calendar.manageDayQuotaConfirm"; return <section><strong>{capability(language, action).title}</strong><p>{modalityLabel} · {dateLabel} · {context.bookingSummary.bookedTotal}</p>{action === "block_modality" ? <label><input type="checkbox" disabled={pending} checked={isOverridable} onChange={(e) => setIsOverridable(e.target.checked)} />{t(language, "calendar.manageDayAllowSupervisorOverride")}</label> : <><fieldset><legend>{t(language, "calendar.manageDaySelectExamTypes")}</legend>{context.examTypeOptions.map((exam) => <label key={exam.id}><input type="checkbox" disabled={pending} checked={examTypeIds.includes(exam.id)} onChange={() => toggle(exam.id)} />{chooseLocalized(language, exam.nameAr, exam.nameEn) || exam.name}</label>)}</fieldset>{action === "restrict_exam_types" ? <label>{t(language, "calendar.manageDayRestrictionMode")}<select disabled={pending} value={effectMode} onChange={(e) => setEffectMode(e.target.value as "hard_restriction" | "restriction_overridable")}><option value="hard_restriction">{t(language, "calendar.manageDayHardRestrictionOption")}</option><option value="restriction_overridable">{t(language, "calendar.manageDayOverridableRestrictionOption")}</option></select></label> : <label>{t(language, "calendar.manageDayQuotaLimit")}<input type="number" disabled={pending} min={1} max={context.modality.dailyCapacity && context.modality.dailyCapacity > 0 ? context.modality.dailyCapacity : undefined} value={dailyLimit} onChange={(e) => setDailyLimit(e.target.value)} /></label>}</>}<Reason language={language} value={reason} onChange={setReason} error={error} disabled={pending} /><button type="button" disabled={pending} onClick={onCancel}>{t(language, "common.cancel")}</button><button type="button" disabled={pending} onClick={onSubmit}>{t(language, key)}</button></section>; }
function Reason({ language, value, onChange, error, disabled = false }: { language: "ar" | "en"; value: string; onChange: (v: string) => void; error: string | null; disabled?: boolean }) { return <><label>{t(language, "calendar.manageDayReason")}<textarea required disabled={disabled} value={value} placeholder={t(language, "calendar.manageDayReasonPlaceholder")} onChange={(e) => onChange(e.target.value)} /></label>{error ? <p role="alert">{error}</p> : null}</>; }
function Summary({ label, value }: { label: string; value: string | number }) { return <div><p>{label}</p><p>{value}</p></div>; }
function Rule({ title, scope, badge, details, notes, action }: { title: string; scope?: string; badge?: ReactNode; details?: string; notes?: string | null; action?: ReactNode }) { return <div><strong>{title}</strong>{badge}{action}<p>{scope}</p>{details ? <p>{details}</p> : null}{notes ? <p>{notes}</p> : null}</div>; }
