import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { CheckCircle2, Clock3, Search } from "lucide-react";
import { Badge, Button, Card, Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, Input, SectionLabel } from "@/components/shared";
import { chooseLocalized, type Language } from "@/lib/i18n";
import { confirmNoShow, confirmNoShowBulk, confirmOldNoShows, fetchNoShowReviewSnapshot } from "@/lib/api-hooks";
import { useLanguage } from "@/providers/language-provider";
import type { NoShowReviewCandidate } from "@/types/api";

type Confirmation = { kind: "one" | "bulk" | "old"; ids: number[] } | null;

function candidateName(candidate: NoShowReviewCandidate, language: Language) { return chooseLocalized(language, candidate.arabicFullName, candidate.englishFullName); }

export default function NoShowReviewPage() {
  const { language } = useLanguage(); const queryClient = useQueryClient();
  const [search, setSearch] = useState(""); const [modality, setModality] = useState(""); const [selected, setSelected] = useState<number[]>([]);
  const [oldSelected, setOldSelected] = useState<number[]>([]); const [confirmation, setConfirmation] = useState<Confirmation>(null); const [reason, setReason] = useState(""); const [result, setResult] = useState<string | null>(null);
  const query = useQuery({ queryKey: ["queue", "no-shows"], queryFn: fetchNoShowReviewSnapshot, refetchInterval: 30_000 });
  const refresh = () => { void queryClient.invalidateQueries({ queryKey: ["queue", "no-shows"] }); void queryClient.invalidateQueries({ queryKey: ["queue", "no-show-summary"] }); void queryClient.invalidateQueries({ queryKey: ["queue"] }); };
  const action = useMutation({ mutationFn: async (request: NonNullable<Confirmation> & { reason: string }) => request.kind === "one" ? confirmNoShow(request.ids[0], request.reason) : request.kind === "bulk" ? confirmNoShowBulk(request.ids, request.reason) : confirmOldNoShows(request.ids, request.reason), onSuccess: (data: any) => { const outcomes = data?.results ?? [{ status: "confirmed" }]; setResult(`${outcomes.filter((item: any) => item.status === "confirmed").length} confirmed; ${outcomes.filter((item: any) => item.status !== "confirmed").length} not confirmed.`); setConfirmation(null); setReason(""); setSelected([]); setOldSelected([]); refresh(); }, onError: (error: Error) => setResult(error.message) });
  const candidates = useMemo(() => (query.data?.candidates ?? []).filter((item) => { const value = `${candidateName(item, language)} ${item.accessionNumber}`.toLowerCase(); return (!search || value.includes(search.toLowerCase())) && (!modality || item.modalityNameEn === modality); }), [query.data?.candidates, search, modality, language]);
  const modalities = useMemo(() => [...new Set((query.data?.candidates ?? []).map((item) => item.modalityNameEn).filter(Boolean))], [query.data?.candidates]);
  const toggle = (id: number, old = false) => { const set = old ? oldSelected : selected; const update = set.includes(id) ? set.filter((item) => item !== id) : [...set, id]; old ? setOldSelected(update) : setSelected(update); };
  const selectedNames = confirmation?.ids.slice(0, 5).map((id) => [...(query.data?.candidates ?? []), ...(query.data?.oldCleanupCandidates ?? [])].find((item) => item.appointmentId === id)).filter(Boolean).map((item) => candidateName(item!, language)) ?? [];
  const modeText = query.data?.mode === "manual" ? "Manual confirmation" : query.data?.mode === "automatic" ? "Automatic processing" : "Disabled";
  return <div className="mx-auto max-w-7xl space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><SectionLabel pulsing>No-show review</SectionLabel><h1 className="mt-2 text-2xl font-display">No-show review workspace</h1><p className="mt-1 text-sm text-muted-foreground">Review is backend-authoritative. Action PIN is required for every confirmation.</p></div><Link to="/queue"><Button variant="secondary">Back to Queue</Button></Link></div>
    <Card className="p-4"><div className="flex flex-wrap items-center gap-3"><Badge variant={query.data?.mode === "manual" ? "warning" : "neutral"}>{modeText}</Badge><span className="inline-flex items-center gap-1 text-sm text-muted-foreground"><Clock3 size={15}/> Review time: {query.data?.reviewTime ?? "17:00"} Africa/Tripoli</span><span className="text-sm text-muted-foreground">Booking-time grace: {query.data?.graceMinutes ?? 30} minutes</span>{query.data?.mode === "automatic" && <span className="text-sm text-muted-foreground">Last automatic run processed {query.data.lastAutomaticProcessedCount}.</span>}</div>{query.data && !query.data.reviewActive && <p className="mt-3 rounded-lg bg-muted px-3 py-2 text-sm">Review has not opened yet. No destructive actions are available before {query.data.reviewTime}.</p>}</Card>
    {result && <Card className="p-3 text-sm" role="status">{result}</Card>}
    <Card className="p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-semibold">Today’s eligible pending candidates</h2><p className="text-sm text-muted-foreground">{query.data?.pendingCount ?? 0} eligible appointment(s). Arrived, waiting, completed, cancelled, and future timed bookings are excluded.</p></div>{selected.length > 0 && <Button variant="destructive" onClick={() => setConfirmation({ kind: "bulk", ids: selected })}>Confirm selected ({selected.length})</Button>}</div><div className="mt-4 grid gap-2 sm:grid-cols-2"><label className="relative"><Search className="absolute left-3 top-3 text-muted-foreground" size={16}/><Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search patient or accession" /></label><select value={modality} onChange={(event) => setModality(event.target.value)} className="input-premium h-10"><option value="">All modalities</option>{modalities.map((item) => <option key={item} value={item}>{item}</option>)}</select></div><CandidateList candidates={candidates} selected={selected} onToggle={(id) => toggle(id)} onConfirm={(id) => setConfirmation({ kind: "one", ids: [id] })} language={language} /></Card>
    <Card className="p-4"><h2 className="font-semibold">Scheduled but not yet eligible</h2><p className="text-sm text-muted-foreground">These are shown for operational clarity and cannot be confirmed from this section.</p><CandidateList candidates={query.data?.deferredCandidates ?? []} selected={[]} onToggle={() => undefined} onConfirm={() => undefined} language={language} readOnly /></Card>
    <Card className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Old unreviewed scheduled appointments</h2><p className="text-sm text-muted-foreground">Separate cleanup workflow: select explicit appointments and confirm with an Action PIN.</p></div>{oldSelected.length > 0 && <Button variant="destructive" onClick={() => setConfirmation({ kind: "old", ids: oldSelected })}>Confirm selected cleanup ({oldSelected.length})</Button>}</div><CandidateList candidates={query.data?.oldCleanupCandidates ?? []} selected={oldSelected} onToggle={(id) => toggle(id, true)} onConfirm={() => undefined} language={language} /></Card>
    <Dialog open={Boolean(confirmation)} onClose={() => setConfirmation(null)}><DialogContent maxWidth="560px"><DialogHeader><DialogTitle>Confirm no-show status</DialogTitle></DialogHeader><div className="space-y-3"><p className="text-sm">You are confirming {confirmation?.ids.length ?? 0} appointment(s). This changes booking status, activates the patient restriction, writes audit records, and schedules worklist synchronization.</p>{selectedNames.length > 0 && <p className="text-sm text-muted-foreground">{selectedNames.join(", ")}</p>}<label className="block text-sm font-medium">Required reason<Input className="mt-1" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Reason for no-show confirmation" /></label></div><DialogFooter><Button variant="ghost" onClick={() => setConfirmation(null)}>Cancel</Button><Button variant="destructive" disabled={!reason.trim() || action.isPending} onClick={() => confirmation && action.mutate({ ...confirmation, reason })}>{action.isPending ? "Confirming…" : "Confirm no-show"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function CandidateList({ candidates, selected, onToggle, onConfirm, language, readOnly = false }: { candidates: NoShowReviewCandidate[]; selected: number[]; onToggle: (id: number) => void; onConfirm: (id: number) => void; language: Language; readOnly?: boolean }) {
  if (!candidates.length) return <p className="mt-4 text-sm text-muted-foreground">No appointments in this section.</p>;
  return <ul className="mt-4 divide-y divide-border rounded-lg border border-border">{candidates.map((item) => <li key={item.appointmentId} className="flex flex-col gap-2 p-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3">{!readOnly && <input aria-label={`Select ${candidateName(item, language)}`} type="checkbox" checked={selected.includes(item.appointmentId)} onChange={() => onToggle(item.appointmentId)} className="mt-1" />}<div><div className="font-medium">{candidateName(item, language)} <span className="font-mono text-xs text-muted-foreground">{item.accessionNumber}</span></div><div className="text-sm text-muted-foreground">{item.appointmentDate}{item.bookingTime ? ` · ${item.bookingTime.slice(0, 5)}` : " · no booking time"} · {chooseLocalized(language, item.modalityNameAr, item.modalityNameEn)}{item.examNameEn || item.examNameAr ? ` · ${chooseLocalized(language, item.examNameAr, item.examNameEn)}` : ""}</div><div className="text-xs text-muted-foreground">{item.phone1 || "No phone"} · {item.eligibility.replaceAll("_", " ")}</div></div></div>{!readOnly && onConfirm && <Button size="sm" variant="secondary" onClick={() => onConfirm(item.appointmentId)}><CheckCircle2 size={14}/> Confirm</Button>}</li>)}</ul>;
}
