import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button, Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/shared";
import { createIrReferral, fetchAssignableIrDoctors } from "@/lib/api/ir-referrals";
import { getDoctorDisplayName } from "@/lib/user-display-name";
import { useLanguage } from "@/providers/language-provider";
import { pushToast } from "@/lib/toast";
import type { Patient } from "@/types/api";

export function RequestIrReferralModal({patient,onClose,onCreated}:{patient:Patient;onClose:()=>void;onCreated:(id:number)=>void}) {
 const {language}=useLanguage(); const queryClient=useQueryClient(); const [procedure,setProcedure]=useState(""); const [indication,setIndication]=useState(""); const [doctorId,setDoctorId]=useState<number|null>(null); const [notify,setNotify]=useState(true);
 const doctors=useQuery({queryKey:["ir-referral-doctors"],queryFn:fetchAssignableIrDoctors});
 const create=useMutation({mutationFn:()=>createIrReferral({patientId:patient.id,requestedProcedure:procedure.trim(),clinicalIndication:indication.trim()||null,assignedDoctorId:doctorId!,notifyAssignedDoctor:notify}),onSuccess:(referral)=>{void queryClient.invalidateQueries({queryKey:["ir-referrals"]});pushToast({type:"success",title:"IR consultation created",message:"The assigned doctor can see it as preparing."});onCreated(referral.id);},onError:(error)=>pushToast({type:"error",title:"IR consultation failed",message:error instanceof Error?error.message:"Unable to create IR consultation."})});
 const name=patient.englishFullName||patient.arabicFullName||patient.mrn||`Patient ${patient.id}`;
 return <Dialog open={true} onClose={onClose}><DialogContent maxWidth="576px" className="!p-0" aria-labelledby="request-ir-title"><DialogHeader className="border-b p-4 !mb-0" closeLabel="Close IR consultation"><DialogTitle id="request-ir-title" className="!text-lg !font-semibold">Create IR Consultation</DialogTitle></DialogHeader><div className="grid gap-4 p-4"><div className="rounded border bg-muted/20 p-3 text-sm"><strong>{name}</strong>{patient.mrn?<span className="ml-2 text-muted-foreground">{patient.mrn}</span>:null}</div><label className="grid gap-1 text-sm"><span className="font-medium">Requested procedure / consultation reason</span><textarea value={procedure} onChange={e=>setProcedure(e.target.value)} className="min-h-20 rounded border px-3 py-2"/></label><label className="grid gap-1 text-sm"><span className="font-medium">Clinical indication</span><textarea value={indication} onChange={e=>setIndication(e.target.value)} className="min-h-20 rounded border px-3 py-2"/></label><label className="grid gap-1 text-sm"><span className="font-medium">Assign IR doctor</span><select aria-label="Assign IR doctor" value={doctorId??""} onChange={e=>setDoctorId(e.target.value?Number(e.target.value):null)} className="h-10 rounded border px-3"><option value="">Select doctor</option>{(doctors.data??[]).map(d=><option key={d.id} value={d.id}>{getDoctorDisplayName(d,language)}</option>)}</select></label><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={notify} onChange={e=>setNotify(e.target.checked)}/><span>Notify assigned doctor when referral is ready for review</span></label></div><DialogFooter className="border-t p-4 !mt-0"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="button" disabled={!procedure.trim()||!doctorId||create.isPending} onClick={()=>create.mutate()}>Create IR Consultation</Button></DialogFooter></DialogContent></Dialog>;
}
