import { useEffect, useRef, useState } from "react";
import type { TeachingAnatomyModality, TeachingAnatomyPlane } from "../api/teaching-api";
import { anatomyCrosshairPixel, anatomyPlaneIndexFromWorldPoint, anatomyWorldPointFromPlanePixel, getAnatomyPlaneSpec, type ParsedAnatomyNrrd, type ReslicedAnatomyPlane } from "./anatomy-nrrd";

interface Props { primary: ParsedAnatomyNrrd; segmentation: ParsedAnatomyNrrd | null; modality: Exclude<TeachingAnatomyModality, "3D">; display?: { windowLevel?: { width: number; level: number }; intensityRange?: { min: number; max: number } }; plane: TeachingAnatomyPlane; worldPointLps: [number, number, number]; onWorldPointLpsChange: (point: [number, number, number]) => void; selectedLabel: number | null; selectedColor: string | null; overlayEnabled: boolean; }
function rgb(color: string | null): [number, number, number] { return !color ? [255, 206, 84] : [1, 3, 5].map((i) => Number.parseInt(color.slice(i, i + 2), 16)) as [number, number, number]; }
function defaultRange(volume: ParsedAnatomyNrrd) { const data: number[] = []; const stop = Math.min(100000, volume.data.length); for (let i = 0; i < stop; i += 1) data.push(Number(volume.data[i]) * volume.slope + volume.intercept); data.sort((a, b) => a - b); return { min: data[Math.floor(data.length * .02)] ?? 0, max: data[Math.floor(data.length * .98)] ?? 1 }; }

export function CrossSectionStackViewer({ primary, segmentation, modality, display, plane, worldPointLps, onWorldPointLpsChange, selectedLabel, selectedColor, overlayEnabled }: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const workerRef = useRef<Worker | null>(null); const requestRef = useRef(0); const [slice, setSlice] = useState<ReslicedAnatomyPlane | null>(null);
  const [range, setRange] = useState(display?.intensityRange ?? defaultRange(primary)); const [wl, setWl] = useState(display?.windowLevel ?? { width: 400, level: 40 }); const index = anatomyPlaneIndexFromWorldPoint(primary.geometry, plane, worldPointLps); const spec = getAnatomyPlaneSpec(primary.geometry, plane); const color = rgb(selectedColor);
  useEffect(() => { const worker = new Worker(new URL("./anatomy-reslice-worker.ts", import.meta.url), { type: "module" }); workerRef.current = worker; worker.postMessage({ type: "init", primary, segmentation }); worker.onmessage = (event: MessageEvent<{ requestId: number; result: ReslicedAnatomyPlane }>) => { if (event.data.requestId === requestRef.current) setSlice(event.data.result); }; return () => worker.terminate(); }, [primary, segmentation]);
  useEffect(() => { const requestId = ++requestRef.current; workerRef.current?.postMessage({ type: "slice", requestId, plane, sliceIndex: index }); }, [plane, index]);
  useEffect(() => { const canvas = canvasRef.current; const context = canvas?.getContext("2d", { alpha: false }); if (!canvas || !context || !slice) return; canvas.width = slice.width; canvas.height = slice.height; const image = context.createImageData(slice.width, slice.height); const low = modality === "CT" ? wl.level - wl.width / 2 : range.min; const high = modality === "CT" ? wl.level + wl.width / 2 : range.max; for (let i = 0; i < slice.values.length; i += 1) { const o = i * 4; if (!slice.validMask[i]) { image.data[o + 3] = 255; continue; } const gray = Math.round(255 * Math.max(0, Math.min(1, (slice.values[i]! - low) / Math.max(.001, high - low)))); const selected = overlayEnabled && selectedLabel !== null && slice.labels?.[i] === selectedLabel; image.data[o] = selected ? Math.round(gray * .48 + color[0] * .52) : gray; image.data[o + 1] = selected ? Math.round(gray * .48 + color[1] * .52) : gray; image.data[o + 2] = selected ? Math.round(gray * .48 + color[2] * .52) : gray; image.data[o + 3] = 255; } context.putImageData(image, 0, 0); }, [slice, modality, range, wl, overlayEnabled, selectedLabel, color]);
  const move = (delta: number) => { const next = Math.max(0, Math.min(spec.sliceCount - 1, index + delta)); onWorldPointLpsChange(anatomyWorldPointFromPlanePixel(primary.geometry, plane, next, spec.width / 2, spec.height / 2)); }; const crosshair = anatomyCrosshairPixel(primary.geometry, plane, worldPointLps);
  return <section className="flex min-h-[18rem] min-w-0 flex-col rounded-xl border bg-[#111827] text-white" style={{ borderColor: "var(--border)" }}><header className="flex items-center justify-between gap-2 border-b px-3 py-2 text-xs" style={{ borderColor: "rgba(255,255,255,.12)" }}><strong>{plane.toUpperCase()} {modality}</strong><span>{modality === "CT" ? `W ${Math.round(wl.width)} L ${Math.round(wl.level)}` : "MRI intensity"}</span><button type="button" onClick={() => modality === "CT" ? setWl(display?.windowLevel ?? { width: 400, level: 40 }) : setRange(display?.intensityRange ?? defaultRange(primary))}>Reset</button></header><div tabIndex={0} className="relative flex min-h-0 flex-1 items-center justify-center overflow-hidden" onWheel={(event) => { event.preventDefault(); move(event.deltaY > 0 ? 1 : -1); }} onKeyDown={(event) => { if (["ArrowDown", "ArrowRight"].includes(event.key)) move(1); if (["ArrowUp", "ArrowLeft"].includes(event.key)) move(-1); }} onPointerDown={(event) => { const rect = event.currentTarget.getBoundingClientRect(); onWorldPointLpsChange(anatomyWorldPointFromPlanePixel(primary.geometry, plane, index, ((event.clientX - rect.left) / rect.width) * spec.width, ((event.clientY - rect.top) / rect.height) * spec.height)); }} aria-label={`${plane} radiology view`}><span className="absolute left-2 top-2 z-10 rounded bg-black/60 px-1.5">{spec.leftMarker}</span><span className="absolute right-2 top-2 z-10 rounded bg-black/60 px-1.5">{spec.rightMarker}</span><canvas ref={canvasRef} className="max-h-[28rem] max-w-full object-contain" /><i aria-hidden="true" className="pointer-events-none absolute h-px w-full bg-cyan-300/80" style={{ top: `${100 * crosshair.y / spec.height}%` }} /><i aria-hidden="true" className="pointer-events-none absolute h-full w-px bg-cyan-300/80" style={{ left: `${100 * crosshair.x / spec.width}%` }} /></div><footer className="flex items-center gap-2 border-t px-3 py-2 text-xs" style={{ borderColor: "rgba(255,255,255,.12)" }}><button type="button" onClick={() => move(-1)}>Previous</button><span className="flex-1 text-center">Slice {index + 1}/{spec.sliceCount}</span><button type="button" onClick={() => move(1)}>Next</button>{modality === "CT" && <button type="button" onClick={() => setWl((current) => ({ ...current, width: Math.max(1, current.width * .8) }))}>Contrast</button>}</footer></section>;
}
