import { useEffect, useState } from "react";
import { ApiError } from "@/lib/api-client";
import { isReAuthRequiredError } from "./settings-page.helpers";

type Settings = { enabled: boolean; senderName: string; senderEmail: string; replyToEmail: string; smtpHost: string; smtpPort: number; securityMode: "tls" | "starttls"; smtpUsername: string; connectionTimeoutSeconds: number; passwordConfigured: boolean; encryptionKeyConfigured: boolean };
type Rule = { eventType: "additional_imaging_completed"; enabled: boolean; label: string; description: string; recipientDescription: string; subjectTemplate: string; textBodyTemplate: string; defaultSubjectTemplate: string; defaultTextBodyTemplate: string; availableBodyPlaceholders: string[] };
type History = { id: number; eventType: string; recipientEmail: string; subject: string; status: string; attemptCount: number; lastErrorSummary?: string | null; createdAt: string };
const key = ["settings", "email-notifications"];
const statusLabel: Record<string, string> = { pending: "Pending", processing: "Processing", retry_scheduled: "Retry scheduled", accepted: "Accepted by mail server", failed: "Failed" };

async function api<T>(path: string, options?: RequestInit): Promise<T> {
  const response = await fetch(`/api/settings/email-notifications${path}`, { credentials: "include", headers: { "Content-Type": "application/json" }, ...options });
  if (!response.ok) { const data = await response.json().catch(() => null) as { error?: { message?: string } | string } | null; throw new ApiError(typeof data?.error === "string" ? data.error : data?.error?.message || `Email settings request failed with HTTP ${response.status}.`, response.status, data); }
  return response.json();
}

export default function EmailNotificationsSection({ onReAuthRequired, reauthVersion = 0 }: { onReAuthRequired: (key: string[]) => void; reauthVersion?: number }) {
  const [settings, setSettings] = useState<Settings | null>(null); const [rules, setRules] = useState<Rule[]>([]); const [history, setHistory] = useState<History[]>([]); const [password, setPassword] = useState(""); const [recipient, setRecipient] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { const [s, r, h] = await Promise.all([api<{ settings: Settings }>(""), api<{ rules: Rule[] }>("/rules"), api<{ history: History[] }>("/history")]); setSettings(s.settings); setRules(r.rules); setHistory(h.history); };
  useEffect(() => { void load().catch((error: unknown) => { if (isReAuthRequiredError(error)) onReAuthRequired(key); setMessage(error instanceof Error ? error.message : "Unable to load email settings."); }); }, [reauthVersion]);
  const act = async (path: string, method: string, body: unknown, success: string) => { setBusy(true); setMessage(""); try { const result = await api<{ settings?: Settings; outboxId?: number; status?: string }>(path, { method, body: JSON.stringify(body) }); if (result.settings) setSettings(result.settings); setMessage(path === "/test-email" ? `Test email queued: #${result.outboxId} (${result.status}).` : success); setPassword(""); await load(); } catch (error) { if (isReAuthRequiredError(error)) onReAuthRequired(key); setMessage(error instanceof Error ? error.message : "Email action failed."); } finally { setBusy(false); } };
  if (!settings) return <p>{message || "Loading Email & Notifications…"}</p>;
  const payload = () => ({ ...settings, password });
  const change = <K extends keyof Settings>(name: K, value: Settings[K]) => setSettings({ ...settings, [name]: value });
  const status = (label: string, configured: boolean) => <p className="text-sm">{label}: {configured ? "Configured" : "Not configured"}</p>;
  return <div className="space-y-4">
    <section><h3 className="font-semibold">Outbound Email</h3><div className="mt-2"><p className="text-sm">Outbound email: {settings.enabled ? "Enabled" : "Disabled"}</p>{status("SMTP credentials", settings.passwordConfigured)}{status("Credential encryption", settings.encryptionKeyConfigured)}</div><div className="mt-3 grid gap-3 md:grid-cols-2">
      <label>Enabled<select aria-label="Enabled" className="input-premium mt-1 w-full" value={settings.enabled ? "enabled" : "disabled"} onChange={(event) => change("enabled", event.target.value === "enabled")}><option value="disabled">Disabled</option><option value="enabled">Enabled</option></select></label>
      <label>Sender display name<input aria-label="Sender display name" className="input-premium mt-1 w-full" value={settings.senderName} onChange={(event) => change("senderName", event.target.value)} /></label><label>Sender email<input aria-label="Sender email" className="input-premium mt-1 w-full" value={settings.senderEmail} onChange={(event) => change("senderEmail", event.target.value)} /></label><label>Reply-to<input aria-label="Reply-to" className="input-premium mt-1 w-full" value={settings.replyToEmail} onChange={(event) => change("replyToEmail", event.target.value)} /></label><label>SMTP host<input aria-label="SMTP host" className="input-premium mt-1 w-full" value={settings.smtpHost} onChange={(event) => change("smtpHost", event.target.value)} /></label><label>SMTP port<input aria-label="SMTP port" type="number" className="input-premium mt-1 w-full" value={settings.smtpPort} onChange={(event) => change("smtpPort", Number(event.target.value))} /></label><label>Security mode<select aria-label="Security mode" className="input-premium mt-1 w-full" value={settings.securityMode} onChange={(event) => change("securityMode", event.target.value as Settings["securityMode"])}><option value="tls">TLS</option><option value="starttls">STARTTLS</option></select></label><label>SMTP username<input aria-label="SMTP username" className="input-premium mt-1 w-full" value={settings.smtpUsername} onChange={(event) => change("smtpUsername", event.target.value)} /></label><label>SMTP password<input aria-label="SMTP password" type="password" className="input-premium mt-1 w-full" placeholder={settings.passwordConfigured ? "Saved password — leave blank to keep" : "SMTP password"} value={password} onChange={(event) => setPassword(event.target.value)} /></label><label>Connection timeout (seconds)<input aria-label="Connection timeout (seconds)" type="number" className="input-premium mt-1 w-full" value={settings.connectionTimeoutSeconds} onChange={(event) => change("connectionTimeoutSeconds", Number(event.target.value))} /></label>
    </div><div className="mt-3 flex flex-wrap gap-2"><button className="btn-primary" disabled={busy} onClick={() => void act("", "PUT", payload(), "Settings saved.")}>Save settings</button><button className="btn-secondary" disabled={busy} onClick={() => void act("/test-connection", "POST", payload(), "SMTP connection succeeded.")}>Test connection</button></div><div className="mt-3 flex flex-wrap gap-2"><input aria-label="Test email recipient" className="input-premium" value={recipient} onChange={(event) => setRecipient(event.target.value)} placeholder="recipient address" /><button className="btn-secondary" disabled={busy} onClick={() => void act("/test-email", "POST", { recipient }, "")}>Send test email</button></div></section>
    <section><h3 className="font-semibold">Automatic Email Notifications</h3>{rules.map((rule) => <RuleCard key={rule.eventType} rule={rule} busy={busy} act={act} />)}</section>{message ? <p className="text-sm">{message}</p> : null}
    <section className="overflow-x-auto"><h3 className="font-semibold">Recent Email Activity</h3><table className="min-w-full text-sm"><thead><tr>{["Time", "Recipient", "Event", "Subject", "Status", "Attempts", "Error"].map((heading) => <th key={heading} className="px-2 py-2 text-left">{heading}</th>)}</tr></thead><tbody>{history.map((row) => <tr key={row.id}><td className="px-2 py-2">{new Date(row.createdAt).toLocaleString()}</td><td className="px-2 py-2">{row.recipientEmail}</td><td className="px-2 py-2">{row.eventType}</td><td className="px-2 py-2">{row.subject}</td><td className="px-2 py-2">{statusLabel[row.status] || row.status}</td><td className="px-2 py-2">{row.attemptCount}</td><td className="px-2 py-2">{row.lastErrorSummary || ""}</td></tr>)}</tbody></table></section>
  </div>;
}

function RuleCard({ rule, busy, act }: { rule: Rule; busy: boolean; act: (path: string, method: string, body: unknown, success: string) => Promise<void> }) {
  const [subject, setSubject] = useState(rule.subjectTemplate); const [body, setBody] = useState(rule.textBodyTemplate); useEffect(() => { setSubject(rule.subjectTemplate); setBody(rule.textBodyTemplate); }, [rule]);
  return <div className="mt-2 rounded border p-3"><div className="flex items-center justify-between"><strong>{rule.label}</strong><select aria-label={`${rule.label} status`} className="input-premium" value={rule.enabled ? "enabled" : "disabled"} disabled={busy} onChange={(event) => void act(`/rules/${rule.eventType}`, "PUT", { enabled: event.target.value === "enabled" }, "Notification rule saved.")}><option value="disabled">Disabled</option><option value="enabled">Enabled</option></select></div><p className="mt-2 text-sm">{rule.description}</p><p className="text-sm">Recipient: {rule.recipientDescription}</p><details className="mt-3"><summary className="cursor-pointer font-medium">Email content</summary><p className="mt-2 text-sm">Used by both automatic and manually sent Additional Imaging completion emails.</p><label className="mt-2 block">Subject<input aria-label="Email subject" className="input-premium mt-1 w-full" value={subject} onChange={(event) => setSubject(event.target.value)} /></label><label className="mt-2 block">Message<textarea aria-label="Email message" className="input-premium mt-1 min-h-40 w-full" value={body} onChange={(event) => setBody(event.target.value)} /></label><p className="mt-2 text-xs">Available placeholders: {rule.availableBodyPlaceholders.map((placeholder) => `{{${placeholder}}`).join(", ")}. <strong>{"{{patient_name}} is BODY ONLY."}</strong></p><div className="mt-2 flex gap-2"><button className="btn-primary" disabled={busy} onClick={() => void act(`/rules/${rule.eventType}/template`, "PUT", { subjectTemplate: subject, textBodyTemplate: body }, "Email content saved.")}>Save email content</button><button className="btn-secondary" type="button" disabled={busy} onClick={() => { setSubject(rule.defaultSubjectTemplate); setBody(rule.defaultTextBodyTemplate); }}>Restore default</button></div></details></div>;
}
