import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import EquipmentSection from "./equipment-section";
import { LanguageProvider } from "@/providers/language-provider-component";

const api = vi.hoisted(() => ({ fetchEquipment: vi.fn(), fetchDicomDevices: vi.fn(), createEquipment: vi.fn(), updateEquipment: vi.fn(), saveEquipmentDicomIdentity: vi.fn(), deactivateEquipment: vi.fn() }));
const catalog = vi.hoisted(() => ({ fetchModalitiesSettings: vi.fn() }));
vi.mock("@/lib/api-hooks", () => api); vi.mock("@/lib/api/catalog", () => catalog);
const configured = { id: 1, name: "MRI A", equipment_type: "MRI", modality_id: 4, modality_code: "MRI", vendor: "GE", model: "X", serial_number: "SN-1", location: "Room 1", dicom_device_id: 7, dicomIdentity: { id: 7, deviceName: "MRI AE", modalityAeTitle: "MR1", scheduledStationAeTitle: "MR1", stationName: "MRI room", stationLocation: "North", sourceIp: "10.0.0.7", mwlEnabled: true, isActive: true }, field_strength: "1.5T", is_active: true };
const unlinked = { id: 2, name: "CT B", equipment_type: "CT", modality_id: 5, modality_code: "CT", vendor: "Philips", model: "IQ", location: "Room 2", dicom_device_id: null, is_active: true };
function view(onReAuthRequired = vi.fn()) { const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); return { onReAuthRequired, ...render(<LanguageProvider><QueryClientProvider client={client}><EquipmentSection onReAuthRequired={onReAuthRequired} /></QueryClientProvider></LanguageProvider>) }; }
function defaults(equipment = [configured, unlinked]) { api.fetchEquipment.mockResolvedValue({ equipment }); api.fetchDicomDevices.mockResolvedValue({ devices: [{ id: 7, modalityId: 4, deviceName: "MRI AE", modalityAeTitle: "MR1" }, { id: 8, modalityId: 5, deviceName: "CT legacy", modalityAeTitle: "CT99" }, { id: 9, modalityId: 5, deviceName: "Already linked", modalityAeTitle: "CT10" }] }); catalog.fetchModalitiesSettings.mockResolvedValue({ modalities: [{ id: 4, code: "MRI", name_en: "MRI" }, { id: 5, code: "CT", name_en: "CT" }] }); api.createEquipment.mockResolvedValue({ equipment: unlinked }); api.updateEquipment.mockResolvedValue({ equipment: configured }); api.saveEquipmentDicomIdentity.mockResolvedValue({ equipment: configured }); api.deactivateEquipment.mockResolvedValue({ equipment: configured }); }
afterEach(() => vi.clearAllMocks());

describe("EquipmentSection", () => {
  it("renders configured and unconfigured DICOM status without raw device IDs", async () => { defaults(); view(); expect(await screen.findByText("MRI A")).toBeTruthy(); expect(screen.getByText("DICOM configured")).toBeTruthy(); expect(screen.getByText("DICOM not configured")).toBeTruthy(); expect(screen.getByText(/AE: MR1/)).toBeTruthy(); });
  it("opens configured DICOM identity and saves it through the Equipment endpoint", async () => { defaults(); view(); fireEvent.click(await screen.findAllByText("Edit").then(buttons => buttons[0]!)); expect(screen.getByLabelText("Device name")).toBeTruthy(); fireEvent.change(screen.getByLabelText("Modality AE Title"), { target: { value: "MR2" } }); fireEvent.click(screen.getByText("Save DICOM identity")); await waitFor(() => expect(api.saveEquipmentDicomIdentity).toHaveBeenCalledWith(1, expect.objectContaining({ deviceName: "MRI AE", modalityAeTitle: "MR2" }))); });
  it("requires a linked modality and defaults a new device name from Equipment", async () => { defaults([unlinked]); view(); fireEvent.click(await screen.findByText("Edit")); fireEvent.click(screen.getByText("Configure DICOM")); expect((screen.getByLabelText("Device name") as HTMLInputElement).value).toBe("CT B"); expect(screen.queryByText("MPPS enabled")).toBeNull(); fireEvent.change(screen.getByLabelText("Linked RIS modality"), { target: { value: "" } }); expect(screen.getByText("Select a linked RIS modality before configuring a DICOM identity.")).toBeTruthy(); });
  it("offers only compatible unlinked DICOM identities for explicit linking", async () => { defaults([unlinked, { ...configured, id: 3, dicom_device_id: 9 }]); view(); fireEvent.click(await screen.findAllByText("Edit").then(buttons => buttons[0]!)); const select = screen.getByLabelText("Link existing DICOM identity") as HTMLSelectElement; expect(select.textContent).toContain("CT legacy"); expect(select.textContent).not.toContain("Already linked"); fireEvent.change(select, { target: { value: "8" } }); fireEvent.click(screen.getByText("Link identity")); await waitFor(() => expect(api.saveEquipmentDicomIdentity).toHaveBeenCalledWith(2, { existingDicomDeviceId: "8" })); });
  it("preserves MRI/CT conditional details and regular Equipment save behavior", async () => { defaults([configured]); view(); fireEvent.click(await screen.findByText("Edit")); expect(screen.getByLabelText("Field strength")).toBeTruthy(); fireEvent.change(screen.getByLabelText("Equipment type"), { target: { value: "CT" } }); expect(screen.getByLabelText("CT slice / detector specification")).toBeTruthy(); fireEvent.change(screen.getByLabelText("location"), { target: { value: "Room 3" } }); fireEvent.click(screen.getByText("Save Equipment")); await waitFor(() => expect(api.updateEquipment).toHaveBeenCalledWith(1, expect.objectContaining({ location: "Room 3" }))); });
  it("shows inline DICOM save errors and reauthentication prompts", async () => { defaults([configured]); api.saveEquipmentDicomIdentity.mockRejectedValueOnce(new Error("AE Title already exists")); const { onReAuthRequired } = view(); fireEvent.click(await screen.findByText("Edit")); fireEvent.click(screen.getByText("Save DICOM identity")); expect((await screen.findByRole("alert")).textContent).toContain("AE Title already exists"); api.fetchEquipment.mockRejectedValueOnce(new Error("re-authentication required")); fireEvent.click(screen.getByLabelText("Show inactive")); const reauthButton = await screen.findByRole("button", { name: /إعادة التحقق|Re-authenticate/ }); fireEvent.click(reauthButton); expect(onReAuthRequired).toHaveBeenCalledWith(["equipment"]); });
});
