#!/bin/sh
# =============================================================================
# RISpro Docker Setup - First-Time Bootstrap
# =============================================================================
# Guides the user through initial configuration and starts the stack.
# =============================================================================

set -e

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)"
APP_DIR="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd -P)"
ENV_FILE="$APP_DIR/.env"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info() {
  printf '\n${CYAN}%s${NC}\n' "$1"
}

success() {
  printf '${GREEN}✓ %s${NC}\n' "$1"
}

warn() {
  printf '${YELLOW}⚠ %s${NC}\n' "$1"
}

error() {
  printf '${RED}✗ %s${NC}\n' "$1"
}

prompt() {
  printf '%s [%s]: ' "$1" "$2"
  read -r response
  if [ -z "$response" ]; then
    echo "$2"
  else
    echo "$response"
  fi
}

prompt_secret() {
  printf '%s: ' "$1"
  # shellcheck disable=SC2162
  read -r response
  echo "$response"
}

# URL-encode a string (minimal: encodes @ : / # ? & = + space)
url_encode() {
  echo "$1" | sed 's|@|%40|g; s|:|%3A|g; s|/|%2F|g; s|#|%23|g; s|?|%3F|g; s|&|%26|g; s|=|%3D|g; s|+|%2B|g; s| |%20|g'
}

# Check prerequisites
check_prerequisites() {
  info "Checking prerequisites..."

  if ! command -v docker >/dev/null 2>&1; then
    error "docker is not installed. Please install Docker first."
    exit 1
  fi

  if ! command -v docker compose >/dev/null 2>&1; then
    error "docker compose is not available. Please install Docker Compose V2."
    exit 1
  fi

  success "Docker: $(docker --version)"
  success "Docker Compose: $(docker compose version)"
}

# Generate .env for internal database mode
generate_internal_env() {
  info "Generating .env for internal PostgreSQL mode..."

  # Generate secure defaults
  jwt_secret="$(openssl rand -hex 32 2>/dev/null || dd if=/dev/urandom bs=32 count=1 2>/dev/null | od -An -tx1 | tr -d ' \n')"
  supervisor_password="$(openssl rand -base64 18 2>/dev/null || dd if=/dev/urandom bs=18 count=1 2>/dev/null | base64)"

  # Fallback if openssl/urandom failed
  if [ -z "$jwt_secret" ]; then
    jwt_secret="CHANGE_ME_TO_A_LONG_RANDOM_SECRET_MINIMUM_32_CHARS"
  fi
  if [ -z "$supervisor_password" ]; then
    supervisor_password="ChangeThisPassword123!"
  fi

  cat > "$ENV_FILE" <<EOF
# =============================================================================
# RISpro Reception - Auto-generated Configuration
# =============================================================================
# Generated by setup-docker.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# Database mode: Internal PostgreSQL
# =============================================================================

# -- Node.js Environment --
NODE_ENV=production
PORT=3000
TRUST_PROXY=1

# -- Database (Internal PostgreSQL) --
# The app will connect to the 'postgres' container on the Docker network.
DATABASE_URL=postgresql://rispro:rispro_password@postgres:5432/rispro
DB_USER=rispro
DB_PASSWORD=rispro_password
DB_NAME=rispro

# -- Authentication --
JWT_SECRET=${jwt_secret}

# -- Session Configuration --
COOKIE_NAME=rispro_session
COOKIE_SECURE=false
COOKIE_SAME_SITE=lax
SESSION_HOURS=8

# -- Supervisor Re-authentication --
SUPERVISOR_REAUTH_MINUTES=10

# -- File Uploads --
REQUEST_BODY_LIMIT=8mb
UPLOADS_DIR=storage/uploads

# -- Initial Supervisor Account --
SEED_SUPERVISOR_USERNAME=admin
SEED_SUPERVISOR_PASSWORD=${supervisor_password}
SEED_SUPERVISOR_FULL_NAME=System Administrator

# -- DICOM Gateway (Embedded) --
# MWL and MPPS services start automatically inside the app container.
# AE titles, ports, and directories are managed via Settings UI.
EOF

  success ".env file generated at: $ENV_FILE"
  echo ""
  warn "IMPORTANT: Save these credentials securely:"
  echo "  Supervisor username: admin"
  echo "  Supervisor password: ${supervisor_password}"
  echo "  JWT secret: (auto-generated, stored in .env)"
}

# Generate .env for external database mode
generate_external_env() {
  info "Configuring external PostgreSQL connection..."

  db_host="$(prompt "Database host" "localhost")"
  db_port="$(prompt "Database port" "5432")"
  db_name="$(prompt "Database name" "rispro")"
  db_user="$(prompt "Database username" "rispro")"
  db_password="$(prompt_secret "Database password")"

  if [ -z "$db_password" ]; then
    error "Database password is required."
    exit 1
  fi

  # URL-encode password
  encoded_password="$(url_encode "$db_password")"

  database_url="postgresql://${db_user}:${encoded_password}@${db_host}:${db_port}/${db_name}"

  # Generate secure defaults for non-DB settings
  jwt_secret="$(openssl rand -hex 32 2>/dev/null || dd if=/dev/urandom bs=32 count=1 2>/dev/null | od -An -tx1 | tr -d ' \n')"
  supervisor_password="$(openssl rand -base64 18 2>/dev/null || dd if=/dev/urandom bs=18 count=1 2>/dev/null | base64)"

  if [ -z "$jwt_secret" ]; then
    jwt_secret="CHANGE_ME_TO_A_LONG_RANDOM_SECRET_MINIMUM_32_CHARS"
  fi
  if [ -z "$supervisor_password" ]; then
    supervisor_password="ChangeThisPassword123!"
  fi

  cat > "$ENV_FILE" <<EOF
# =============================================================================
# RISpro Reception - Auto-generated Configuration
# =============================================================================
# Generated by setup-docker.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# Database mode: External PostgreSQL
# =============================================================================

# -- Node.js Environment --
NODE_ENV=production
PORT=3000
TRUST_PROXY=1

# -- Database (External PostgreSQL) --
DATABASE_URL=${database_url}

# -- Authentication --
JWT_SECRET=${jwt_secret}

# -- Session Configuration --
COOKIE_NAME=rispro_session
COOKIE_SECURE=false
COOKIE_SAME_SITE=lax
SESSION_HOURS=8

# -- Supervisor Re-authentication --
SUPERVISOR_REAUTH_MINUTES=10

# -- File Uploads --
REQUEST_BODY_LIMIT=8mb
UPLOADS_DIR=storage/uploads

# -- Initial Supervisor Account --
SEED_SUPERVISOR_USERNAME=admin
SEED_SUPERVISOR_PASSWORD=${supervisor_password}
SEED_SUPERVISOR_FULL_NAME=System Administrator

# -- DICOM Gateway (Embedded) --
# MWL and MPPS services start automatically inside the app container.
# AE titles, ports, and directories are managed via Settings UI.
EOF

  success ".env file generated at: $ENV_FILE"
  echo ""
  warn "IMPORTANT: Save these credentials securely:"
  echo "  Supervisor username: admin"
  echo "  Supervisor password: ${supervisor_password}"
  echo "  Database: ${db_host}:${db_port}/${db_name}"
}

# Main
main() {
  echo ""
  echo "==================================================="
  echo "  RISpro Reception - Docker Setup"
  echo "==================================================="
  echo ""

  # Check if .env already exists
  if [ -f "$ENV_FILE" ]; then
    warn ".env file already exists at: $ENV_FILE"
    printf "Do you want to overwrite it? (y/N): "
    read -r overwrite
    case "$overwrite" in
      [yY][eE][sS]|[yY])
        warn "Existing .env will be overwritten."
        ;;
      *)
        info "Keeping existing .env file. Starting Docker Compose..."
        cd "$APP_DIR"
        docker compose up -d --build
        success "Setup complete! Check logs with: docker compose logs -f app"
        exit 0
        ;;
    esac
  fi

  check_prerequisites
  echo ""

  # Ask for database mode
  info "Choose your database setup:"
  echo "  1) Internal PostgreSQL (Docker-managed, easiest)"
  echo "  2) External PostgreSQL (connect to existing database server)"
  echo ""
  db_mode="$(prompt "Select mode (1 or 2)" "1")"

  case "$db_mode" in
    1|internal|Internal)
      generate_internal_env
      compose_files="-f docker-compose.yml -f docker-compose.internal-db.yml"
      ;;
    2|external|External)
      generate_external_env
      compose_files="-f docker-compose.yml"
      ;;
    *)
      error "Invalid selection. Defaulting to internal database."
      generate_internal_env
      compose_files="-f docker-compose.yml -f docker-compose.internal-db.yml"
      ;;
  esac

  echo ""
  info "Building and starting Docker containers..."
  cd "$APP_DIR"
  # shellcheck disable=SC2086
  docker compose $compose_files up -d --build

  echo ""
  info "Waiting for application to become healthy..."
  attempt=0
  max_attempts=30
  while [ $attempt -lt $max_attempts ]; do
    attempt=$((attempt + 1))
    if wget -qO- "http://127.0.0.1:3000/api/health" >/dev/null 2>&1; then
      success "Application is healthy!"
      break
    fi
    printf "  Waiting... (%d/%d)\n" "$attempt" "$max_attempts"
    sleep 2
  done

  if [ $attempt -ge $max_attempts ]; then
    warn "Application did not become healthy within expected time."
    warn "Check logs with: docker compose logs -f app"
  else
    echo ""
    echo "==================================================="
    success "RISpro is ready!"
    echo "==================================================="
    echo ""
    echo "  Web UI:     http://localhost:3000"
    echo "  DICOM MWL:  127.0.0.1:11112 (AE: RISPRO_MWL)"
    echo "  DICOM MPPS: 127.0.0.1:11113 (AE: RISPRO_MPPS)"
    echo ""
    echo "  Useful commands:"
    echo "    docker compose logs -f app        # View application logs"
    echo "    docker compose down               # Stop all containers"
    echo "    ./scripts/update-docker.sh        # Update to latest code"
    echo ""
  fi
}

main "$@"
