import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";
import RequestScansPage from "./request-scans-page";

const response = (value: unknown) => ({ ok: true, json: async () => value }) as Response;
const health = { name: "archive-share", state: "unavailable", affectedCount: 31, lastConnectionCheck: "2026-07-24T10:00:00Z", lastSuccessfulArchive: "2026-07-24T09:00:00Z", nextRetryAt: "2026-07-24T10:02:00Z", lastError: "Connection unavailable" };
const status = { enabled: true, lastRunAt: "2026-07-24T10:00:00Z", lastError: null, running: false, workerOnline: true, pending: 0, processing: 0, processedToday: 2, failed: 1, canRetryArchives: true, archiveDestination: health };
type JobFixture = { id: number; filename: string; status: string; barcode_value: string | null; appointment_id: number | null; document_id: number | null; attachment_completed_at: string | null; source_moved_at: string | null; archive_attempt_count: number; last_archive_attempt_at: string | null; archive_last_error: string | null; error_message: string | null; attempt_count: number; created_at: string; patient_name: string | null; patient_mrn: string | null; patient_date_of_birth: string | null; modality_name: string | null; exam_name: string | null };
const archiveFailure: JobFixture = { id: 9, filename: "request.pdf", status: "failed", barcode_value: "V2-000009", appointment_id: 9, document_id: 55, attachment_completed_at: "2026-07-24T09:30:00Z", source_moved_at: null, archive_attempt_count: 7, last_archive_attempt_at: "2026-07-24T10:00:00Z", archive_last_error: "Connection unavailable", error_message: "Connection unavailable", attempt_count: 7, created_at: "2026-07-24T09:00:00Z", patient_name: "Patient One", patient_mrn: "MRN-9", patient_date_of_birth: "1980-01-01", modality_name: "CT", exam_name: "Head" };
const completed = { ...archiveFailure, id: 10, status: "processed", source_moved_at: "2026-07-24T10:01:00Z", archive_last_error: null };
function renderPage() { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return render(<QueryClientProvider client={client}><MemoryRouter><RequestScansPage /></MemoryRouter></QueryClientProvider>); }
function mock(jobs = [archiveFailure]) { return vi.spyOn(globalThis, "fetch").mockImplementation(async (input) => { const value = String(input); if (value.endsWith("/status")) return response(status); if (value.includes("eligible-appointments")) return response({ appointments: [{ id: 12, accession_number: "V2-000012", patient_name: "Selected Patient", patient_mrn: "MRN-12", patient_date_of_birth: "1981-01-01", modality_name: "MRI", exam_name: "Brain", appointment_date: "2026-07-25" }] }); if (value.includes("?status=")) return response({ jobs }); return response({ jobs: [] }); }); }
afterEach(() => { vi.restoreAllMocks(); });

describe("RequestScansPage recovery clarity", () => {
  it("shows an attached archive failure as Needs attention, not an attachment failure", async () => { mock(); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Needs attention (1)" })); expect(await screen.findByText("Already attached to the RIS record.")).toBeTruthy(); expect(screen.getByText("Archive failed")).toBeTruthy(); expect(screen.getByRole("button", { name: "Retry archive" })).toBeTruthy(); });
  it("shows one archive incident with its authoritative affected count", async () => { mock(); renderPage(); expect(await screen.findByText("Archive destination unavailable")).toBeTruthy(); expect(screen.getByText(/31 documents are safely attached/)).toBeTruthy(); });
  it("keeps secondary actions in the overflow disclosure", async () => { mock(); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Needs attention (1)" })); await screen.findByText("request.pdf"); expect(screen.getByText("More")).toBeTruthy(); fireEvent.click(screen.getByText("More")); expect(screen.getByText("Preview scanned document")).toBeTruthy(); });
  it("uses archive-only confirmation wording for a selected retry", async () => { mock(); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Needs attention (1)" })); fireEvent.click(await screen.findByLabelText("Select request.pdf")); fireEvent.click(screen.getByRole("button", { name: "Retry selected archives" })); expect(screen.getByText(/The already attached documents will not be duplicated/)).toBeTruthy(); });
  it("does not offer retries for completed records", async () => { mock([completed]); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Processed" })); expect(await screen.findByText("request.pdf")).toBeTruthy(); expect(screen.queryByRole("button", { name: "Retry archive" })).toBeNull(); });
  it("renders the stage-oriented table headers", async () => { mock(); renderPage(); expect(await screen.findByText("Processing result")).toBeTruthy(); expect(screen.getByText("Archive status")).toBeTruthy(); expect(screen.getByText("Patient")).toBeTruthy(); });
  it("requires a scanned-to-selected-patient confirmation before manual assignment", async () => { mock([{ ...archiveFailure, document_id: null, attachment_completed_at: null, appointment_id: null }]); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Needs attention (1)" })); await screen.findByText("request.pdf"); fireEvent.click(screen.getByRole("button", { name: "Assign appointment" })); expect(await screen.findByText("Detected/scanned information")).toBeTruthy(); expect(screen.getByText("Selected RIS appointment")).toBeTruthy(); expect(screen.getByText(/I confirm that this scanned document/)).toBeTruthy(); });
  it("keeps loading and empty states distinct", async () => { const fetchMock = mock([]); renderPage(); expect(await screen.findByText("No active request scans. New scans and retries will appear here automatically.")).toBeTruthy(); await waitFor(() => expect(fetchMock).toHaveBeenCalled()); });
});
