import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";
import RequestScansPage from "./request-scans-page";

const response = (value: unknown) => ({ ok: true, json: async () => value }) as Response;
const health = { name: "archive-share", state: "unavailable", affectedCount: 31, lastConnectionCheck: "2026-07-24T10:00:00Z", lastSuccessfulArchive: "2026-07-24T09:00:00Z", nextRetryAt: "2026-07-24T10:02:00Z", lastError: "Connection unavailable" };
const status = { enabled: true, lastRunAt: "2026-07-24T10:00:00Z", lastError: null, running: false, workerOnline: true, pending: 0, processing: 0, processedToday: 2, failed: 1, canRetryArchives: true, archiveDestination: health };
type JobFixture = { id: number; filename: string; status: string; barcode_value: string | null; appointment_id: number | null; document_id: number | null; attachment_completed_at: string | null; source_moved_at: string | null; archive_attempt_count: number; last_archive_attempt_at: string | null; archive_last_error: string | null; error_message: string | null; attempt_count: number; created_at: string; patient_name: string | null; patient_mrn: string | null; patient_date_of_birth: string | null; modality_name: string | null; exam_name: string | null; failure_category?: string | null; processing_stage?: string | null };
const archiveFailure: JobFixture = { id: 9, filename: "request.pdf", status: "failed", barcode_value: "V2-000009", appointment_id: 9, document_id: 55, attachment_completed_at: "2026-07-24T09:30:00Z", source_moved_at: null, archive_attempt_count: 7, last_archive_attempt_at: "2026-07-24T10:00:00Z", archive_last_error: "Connection unavailable", error_message: "Connection unavailable", attempt_count: 7, created_at: "2026-07-24T09:00:00Z", patient_name: "Patient One", patient_mrn: "MRN-9", patient_date_of_birth: "1980-01-01", modality_name: "CT", exam_name: "Head", failure_category: "smb_storage", processing_stage: "archive" };
const completed = { ...archiveFailure, id: 10, filename: "completed.pdf", status: "processed", source_moved_at: "2026-07-24T10:01:00Z", archive_last_error: null };
function renderPage() { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={["/request-scans"]}><Routes><Route path="/request-scans" element={<RequestScansPage />} /><Route path="/registrations" element={<div>Registration destination</div>} /></Routes></MemoryRouter></QueryClientProvider>); }
function mock(jobs = [archiveFailure]) { return vi.spyOn(globalThis, "fetch").mockImplementation(async (input) => { const value = String(input); if (value.endsWith("/status")) return response(status); if (value.includes("/api/request-scans/") && value.endsWith("/file")) return { ok: true, blob: async () => new Blob(["%PDF-1.4"], { type: "application/pdf" }) } as Response; if (value.includes("eligible-appointments")) return response({ appointments: [{ id: 12, accession_number: "V2-000012", patient_name: "Selected Patient", patient_mrn: "MRN-12", patient_date_of_birth: "1981-01-01", modality_name: "MRI", exam_name: "Brain", appointment_date: "2026-07-25" }] }); if (value.includes("?status=")) return response({ jobs }); return response({ jobs: [] }); }); }
function openMenu(filename = "request.pdf") { fireEvent.click(screen.getByRole("button", { name: "More actions for " + filename })); return screen.getByRole("menu", { name: "Actions for " + filename }); }
afterEach(() => { vi.unstubAllGlobals(); vi.restoreAllMocks(); });

describe("RequestScansPage recovery clarity", () => {
  it("shows an attached archive failure as Needs attention, not an attachment failure", async () => { mock(); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Needs attention (1)" })); expect(await screen.findByText("Already attached to the RIS record.")).toBeTruthy(); expect(screen.getByText("Archive failed")).toBeTruthy(); expect(screen.getByRole("button", { name: "Retry archive" })).toBeTruthy(); });
  it("shows one archive incident with its authoritative affected count", async () => { mock(); renderPage(); expect(await screen.findByText("Archive destination unavailable")).toBeTruthy(); expect(screen.getByText(/31 documents are safely attached/)).toBeTruthy(); });
  it("renders an accessible More actions menu with interactive rows", async () => { mock(); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Needs attention (1)" })); await screen.findByText("request.pdf"); const more = screen.getByRole("button", { name: "More actions for request.pdf" }); expect(more.getAttribute("aria-expanded")).toBe("false"); const menu = openMenu(); expect(more.getAttribute("aria-expanded")).toBe("true"); const items = within(menu).getAllByRole("menuitem"); expect(items).toHaveLength(5); expect(items.every((item) => item.tagName === "BUTTON" || item.tagName === "A")).toBe(true); expect(within(menu).getByRole("menuitem", { name: "Preview scanned document" })).toBeTruthy(); expect(within(menu).getByRole("menuitem", { name: "Open in browser" })).toBeTruthy(); expect(within(menu).getByRole("menuitem", { name: "View attached document" })).toBeTruthy(); expect(within(menu).getByRole("menuitem", { name: "Open appointment" })).toBeTruthy(); expect(within(menu).getByRole("menuitem", { name: "View processing details" })).toBeTruthy(); });
  it("opens request scans in the browser and retains the attached-document link", async () => { mock(); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Needs attention (1)" })); await screen.findByText("request.pdf"); const menu = openMenu(); const browserLink = within(menu).getByRole("menuitem", { name: "Open in browser" }); expect(browserLink.getAttribute("href")).toBe("/api/request-scans/9/file"); expect(browserLink.getAttribute("target")).toBe("_blank"); expect(browserLink.getAttribute("rel")).toBe("noreferrer"); const attachedLink = within(menu).getByRole("menuitem", { name: "View attached document" }); expect(attachedLink.getAttribute("href")).toBe("/api/documents/55/view"); fireEvent.click(browserLink); expect(screen.queryByRole("menu")).toBeNull(); });
  it("navigates to the appointment from the action menu", async () => { mock([completed]); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Processed" })); await screen.findByText("completed.pdf"); const menu = openMenu("completed.pdf"); fireEvent.click(within(menu).getByRole("menuitem", { name: "Open appointment" })); expect(await screen.findByText("Registration destination")).toBeTruthy(); });
  it("opens processing details with diagnostic content", async () => { mock(); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Needs attention (1)" })); await screen.findByText("request.pdf"); const menu = openMenu(); fireEvent.click(within(menu).getByRole("menuitem", { name: "View processing details" })); expect(await screen.findByRole("heading", { name: "Processing details" })).toBeTruthy(); expect(screen.getByText("Processing stage")).toBeTruthy(); expect(screen.getByText("archive")).toBeTruthy(); expect(screen.getByText("Failure category")).toBeTruthy(); expect(screen.getByText("smb_storage")).toBeTruthy(); expect(screen.getByText("Processing attempts")).toBeTruthy(); expect(screen.getAllByText("7").length).toBeGreaterThan(0); expect(screen.getAllByText("Archive error").length).toBeGreaterThan(0); });
  it("uses a large authenticated Blob preview and revokes it on close", async () => { const createObjectURL = vi.fn(() => "blob:request-scan-9"); const revokeObjectURL = vi.fn(); vi.stubGlobal("URL", { createObjectURL, revokeObjectURL }); const fetchMock = mock(); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Needs attention (1)" })); await screen.findByText("request.pdf"); const menu = openMenu(); fireEvent.click(within(menu).getByRole("menuitem", { name: "Preview scanned document" })); const iframe = await screen.findByTitle("Request scan preview"); const fileCall = fetchMock.mock.calls.find(([input]) => String(input).includes("/api/request-scans/9/file")); expect(fileCall?.[0]).toBe("/api/request-scans/9/file"); expect(fileCall?.[1]).toMatchObject({ credentials: "include" }); expect(iframe.getAttribute("src")).toBe("blob:request-scan-9"); const content = iframe.parentElement?.parentElement; expect(content?.style.maxWidth).toBe("min(96vw, 1500px)"); expect(content?.className).toContain("h-[94vh]"); expect(screen.getByRole("link", { name: "Open in browser" }).getAttribute("href")).toBe("/api/request-scans/9/file"); expect(screen.getByRole("link", { name: "View attached document" }).getAttribute("href")).toBe("/api/documents/55/view"); fireEvent.click(screen.getByRole("button", { name: "Close dialog" })); expect(revokeObjectURL).toHaveBeenCalledWith("blob:request-scan-9"); });
  it("revokes the previous Blob URL when a preview is replaced", async () => { const createObjectURL = vi.fn().mockReturnValueOnce("blob:first").mockReturnValueOnce("blob:second"); const revokeObjectURL = vi.fn(); vi.stubGlobal("URL", { createObjectURL, revokeObjectURL }); mock([archiveFailure, completed]); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Needs attention (1)" })); await screen.findByText("request.pdf"); fireEvent.click(screen.getByRole("button", { name: "More actions for request.pdf" })); fireEvent.click(within(screen.getByRole("menu", { name: "Actions for request.pdf" })).getByRole("menuitem", { name: "Preview scanned document" })); await screen.findByTitle("Request scan preview"); fireEvent.click(screen.getByRole("button", { name: "More actions for completed.pdf" })); fireEvent.click(within(screen.getByRole("menu", { name: "Actions for completed.pdf" })).getByRole("menuitem", { name: "Preview scanned document" })); await waitFor(() => expect(createObjectURL).toHaveBeenCalledTimes(2)); expect(revokeObjectURL).toHaveBeenCalledWith("blob:first"); });
  it("uses archive-only confirmation wording for a selected retry", async () => { mock(); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Needs attention (1)" })); fireEvent.click(await screen.findByLabelText("Select request.pdf")); fireEvent.click(screen.getByRole("button", { name: "Retry selected archives" })); expect(screen.getByText(/The already attached documents will not be duplicated/)).toBeTruthy(); });
  it("does not offer retries for completed records", async () => { mock([completed]); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Processed" })); expect(await screen.findByText("completed.pdf")).toBeTruthy(); expect(screen.queryByRole("button", { name: "Retry archive" })).toBeNull(); });
  it("renders the stage-oriented table headers", async () => { mock(); renderPage(); expect(await screen.findByText("Processing result")).toBeTruthy(); expect(screen.getByText("Archive status")).toBeTruthy(); expect(screen.getByText("Patient")).toBeTruthy(); });
  it("shows selected patient identifiers and requires confirmation before queueing manual assignment", async () => { mock([{ ...archiveFailure, document_id: null, attachment_completed_at: null, appointment_id: null }]); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Needs attention (1)" })); await screen.findByText("request.pdf"); fireEvent.click(screen.getByRole("button", { name: "Assign appointment" })); expect(await screen.findByText("Detected/scanned information")).toBeTruthy(); expect(screen.getByText("Selected RIS appointment")).toBeTruthy(); expect(screen.getByText(/I verified the patient identity/)).toBeTruthy(); expect(screen.getByRole("button", { name: "Confirm and queue attachment" })).toBeTruthy(); });
  it("keeps loading and empty states distinct", async () => { const fetchMock = mock([]); renderPage(); expect(await screen.findByText("No active request scans. New scans and retries will appear here automatically.")).toBeTruthy(); await waitFor(() => expect(fetchMock).toHaveBeenCalled()); });
});
