import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { Alert, AlertDescription, AlertTitle, Badge, Button, Checkbox, Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, EmptyState, ErrorState, LoadingState, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/shared";

type Job = { id: number; filename: string; status: "pending" | "processing" | "processed" | "duplicate" | "failed"; barcode_value: string | null; appointment_id: number | null; document_id: number | null; attachment_completed_at?: string | null; source_moved_at?: string | null; archive_attempt_count?: number; last_archive_attempt_at?: string | null; archive_last_error?: string | null; archive_next_retry_at?: string | null; error_message: string | null; failure_category?: string | null; attempt_count: number; created_at: string; processing_stage?: string | null; patient_name?: string | null; patient_mrn?: string | null; patient_date_of_birth?: string | null; modality_name?: string | null; exam_name?: string | null; appointment_date?: string | null; accession_number?: string | null; matchedAppointments?: Array<{ id: number; accessionNumber: string }> };
type Appointment = { id: number; accession_number: string; patient_name: string | null; patient_mrn?: string | null; patient_date_of_birth?: string | null; modality_name?: string | null; exam_name?: string | null; appointment_date?: string | null };
type ArchiveHealth = { name: string | null; state: "connected" | "unavailable" | "degraded" | "unknown"; affectedCount: number; lastConnectionCheck: string | null; lastSuccessfulArchive: string | null; nextRetryAt: string | null; lastError: string | null };
type RequestScanStatus = { enabled: boolean; lastRunAt: string | null; lastError: string | null; running: boolean; workerOnline: boolean; pending: number; processing: number; processedToday: number; failed: number; canRetryArchives?: boolean; archiveDestination: ArchiveHealth; };
type RequestScanTab = "active" | "processed" | "duplicate" | "failed" | "all";
type WorkerTrigger = { status: "accepted" | "already_running" | "disabled" };

export function requestScanStatusPollInterval(status?: RequestScanStatus): number { return status && (status.running || status.processing > 0 || status.pending > 0) ? 2_500 : 15_000; }
export function requestScanJobsPollInterval(tab: RequestScanTab, status?: RequestScanStatus): number | false { const work = Boolean(status && (status.running || status.processing > 0 || status.pending > 0)); return tab === "active" ? (work ? 2_500 : 15_000) : (work ? 15_000 : false); }
async function message(response: Response, fallback: string): Promise<string> { const body = await response.json().catch(() => null) as { error?: { message?: string } | string; message?: string } | null; return typeof body?.error === "object" && body.error?.message ? body.error.message : typeof body?.error === "string" ? body.error : body?.message || fallback; }
async function request<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(`/api/request-scans${url}`, { credentials: "include", headers: { "Content-Type": "application/json" }, ...options }); if (!response.ok) throw new Error(await message(response, "Request Scan action failed")); return response.json() as Promise<T>; }
const date = (value?: string | null) => value ? new Date(value).toLocaleString() : "—";
const archivePending = (job: Job) => Boolean(job.attachment_completed_at && job.document_id && !job.source_moved_at);
function Chip({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "success" | "warning" | "danger" | "info" | "neutral" }) { const colors = { success: "bg-green-100 text-green-800", warning: "bg-amber-100 text-amber-900", danger: "bg-red-100 text-red-800", info: "bg-blue-100 text-blue-800", neutral: "bg-muted text-muted-foreground" }; return <Badge className={colors[tone]}>{children}</Badge>; }
function Overall({ job }: { job: Job }) { if (archivePending(job) || job.status === "failed") return <Chip tone="warning">Needs attention</Chip>; if (job.status === "processing") return <Chip tone="info">Processing</Chip>; if (job.status === "pending") return <Chip tone="info">Queued</Chip>; return <Chip tone="success">Completed</Chip>; }
function ProcessingResult({ job }: { job: Job }) { const matched = job.appointment_id || job.barcode_value; const attached = Boolean(job.attachment_completed_at && job.document_id); return <div className="space-y-1 text-xs"><div>Patient match: <span className="font-medium">{matched ? "Completed" : job.status === "failed" ? "Requires review" : "Pending"}</span></div><div>Document: <span className="font-medium">{attached ? "Attached" : job.status === "failed" ? "Failed" : "Pending"}</span></div>{attached && <p className="text-green-700">Already attached to the RIS record.</p>}<Overall job={job} /></div>; }
function ArchiveStatus({ job }: { job: Job }) { if (job.source_moved_at) return <Chip tone="success">Archived</Chip>; if (archivePending(job)) return <div className="space-y-1"><Chip tone="warning">Archive {job.status === "processing" || job.status === "pending" ? "pending" : "failed"}</Chip><p className="text-xs text-muted-foreground">{job.archive_attempt_count ?? 0} attempts · Last tried {date(job.last_archive_attempt_at)}</p>{job.archive_last_error && <p className="max-w-52 truncate text-xs text-amber-800" title={job.archive_last_error}>{job.archive_last_error}</p>}</div>; return <span className="text-xs text-muted-foreground">Not applicable</span>; }

export default function RequestScansPage() {
  const [tab, setTab] = useState<RequestScanTab>("active"); const [category, setCategory] = useState(""); const [selected, setSelected] = useState<number[]>([]); const [preview, setPreview] = useState<Job | null>(null); const [previewUrl, setPreviewUrl] = useState<string | null>(null); const [assign, setAssign] = useState<Job | null>(null); const [query, setQuery] = useState(""); const [appointmentId, setAppointmentId] = useState(""); const [assignmentConfirmed, setAssignmentConfirmed] = useState(false); const [bulkConfirm, setBulkConfirm] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  const url = useRef<string | null>(null); const navigate = useNavigate(); const client = useQueryClient();
  useEffect(() => () => { if (url.current) URL.revokeObjectURL(url.current); }, []);
  const status = useQuery({ queryKey: ["request-scans-status"], queryFn: () => request<RequestScanStatus>("/status"), refetchInterval: q => requestScanStatusPollInterval(q.state.data), refetchIntervalInBackground: false });
  const jobs = useQuery({ queryKey: ["request-scans", tab, category], queryFn: () => request<{ jobs: Job[] }>(`?status=${tab}${category ? `&category=${category}` : ""}`), refetchInterval: () => requestScanJobsPollInterval(tab, status.data), refetchIntervalInBackground: false });
  const appointments = useQuery({ queryKey: ["request-scan-appointments", query], queryFn: () => request<{ appointments: Appointment[] }>(`/eligible-appointments?q=${encodeURIComponent(query)}`), enabled: Boolean(assign) });
  const refresh = () => { void client.invalidateQueries({ queryKey: ["request-scans"] }); void client.invalidateQueries({ queryKey: ["request-scans-status"] }); };
  const archiveRetry = useMutation({ mutationFn: (id: number) => request<{ job: Job; trigger: WorkerTrigger }>(`/${id}/retry-archive`, { method: "POST" }), onSuccess: () => { setNotice("Archive transfer queued. Attached documents will not be duplicated."); refresh(); } });
  const genericRetry = useMutation({ mutationFn: (id: number) => request(`/${id}/retry`, { method: "POST" }), onSuccess: refresh });
  const bulkRetry = useMutation({ mutationFn: (ids: number[]) => request<{ queued: Job[]; failed: Array<{ id: number; message: string }> }>("/bulk-retry-archives", { method: "POST", body: JSON.stringify({ jobIds: ids }) }), onSuccess: (result) => { setBulkConfirm(false); setSelected([]); setNotice(`${result.queued.length} archive transfers queued. Attached documents will not be duplicated.`); refresh(); } });
  const testConnection = useMutation({ mutationFn: () => request<{ state: string }>("/archive-destination/test", { method: "POST" }), onSuccess: () => { setNotice("Archive destination connection succeeded."); refresh(); } });
  const assignMutation = useMutation({ mutationFn: () => request(`/${assign!.id}/manual-assign`, { method: "POST", body: JSON.stringify({ appointmentId: Number(appointmentId), confirmed: assignmentConfirmed }) }), onSuccess: () => { setAssign(null); setNotice("Document attached and processed."); refresh(); } });
  const openPreview = async (job: Job) => { if (url.current) URL.revokeObjectURL(url.current); setPreview(job); const response = await fetch(`/api/request-scans/${job.id}/file`, { credentials: "include" }); if (!response.ok) { setNotice(await message(response, "Preview could not be loaded.")); return; } url.current = URL.createObjectURL(await response.blob()); setPreviewUrl(url.current); };
  const visible = jobs.data?.jobs ?? []; const selectedArchive = visible.filter(job => selected.includes(job.id) && archivePending(job)); const selectedAppointment = appointments.data?.appointments.find(item => String(item.id) === appointmentId);
  const primary = (job: Job) => archivePending(job) ? status.data?.canRetryArchives ? <Button size="sm" onClick={() => archiveRetry.mutate(job.id)} disabled={archiveRetry.isPending}>Retry archive</Button> : <span className="text-xs text-muted-foreground">Archive retry requires supervisor access</span> : job.status === "failed" && !job.appointment_id ? <Button size="sm" onClick={() => { setAssign(job); setAppointmentId(""); setAssignmentConfirmed(false); }}>Assign appointment</Button> : job.status === "failed" ? <Button size="sm" onClick={() => genericRetry.mutate(job.id)} disabled={genericRetry.isPending}>Retry</Button> : job.appointment_id ? <Button size="sm" variant="secondary" onClick={() => navigate(`/registrations?appointmentId=${job.appointment_id}`)}>Open appointment</Button> : null;
  const health = status.data?.archiveDestination;
  return <main className="space-y-5 p-4">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">Request Scans</h1><p className="text-sm text-muted-foreground">Document processing, attachment, and archive recovery.</p></div><Button onClick={() => request("/run-now", { method: "POST" }).then(refresh)}>Scan folder now</Button></header>
    {notice && <Alert><AlertDescription>{notice}</AlertDescription></Alert>}
    {health?.affectedCount ? <Alert className="border-amber-300 bg-amber-50"><AlertTitle>Archive destination unavailable</AlertTitle><AlertDescription><p>{health.affectedCount} documents are safely attached but are waiting for archive transfer.</p><p className="mt-1 text-xs">Destination: {health.name || "Configured archive"} · Last check: {date(health.lastConnectionCheck)} · Last successful archive: {date(health.lastSuccessfulArchive)} · Next automatic retry: {date(health.nextRetryAt)}</p>{health.lastError && <p className="mt-1 text-xs">Latest error: {health.lastError}</p>}{status.data?.canRetryArchives && <div className="mt-3 flex gap-2"><Button size="sm" variant="secondary" onClick={() => testConnection.mutate()} disabled={testConnection.isPending}>Test connection</Button><Button size="sm" onClick={() => { setSelected(visible.filter(archivePending).map(j => j.id)); setBulkConfirm(true); }}>Retry pending archives</Button></div>}</AlertDescription></Alert> : null}
    <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-lg border p-4"><h2 className="font-semibold">Workload</h2><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><p>Processing <b className="block text-lg">{status.data?.processing ?? "—"}</b></p><p>Queued <b className="block text-lg">{status.data?.pending ?? "—"}</b></p><p>Processed today <b className="block text-lg">{status.data?.processedToday ?? "—"}</b></p><p>Needs attention <b className="block text-lg">{status.data?.failed ?? "—"}</b></p></div></section><section className="rounded-lg border p-4"><h2 className="font-semibold">System health</h2><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><p>Folder watcher <b className="block">{status.data?.running ? "Running" : status.data?.workerOnline ? "Idle" : "Unknown"}</b></p><p>Archive destination <b className="block">{health ? health.state === "unavailable" ? "Unavailable" : health.state : "Unknown"}</b></p><p>Last folder scan <b className="block">{date(status.data?.lastRunAt)}</b></p><p>Last successful archive <b className="block">{date(health?.lastSuccessfulArchive)}</b></p></div></section></div>
    {status.isError && <ErrorState message={`Request Scan status could not be loaded: ${status.error.message}`} />}
    <div className="flex flex-wrap items-end justify-between gap-3"><div className="flex flex-wrap gap-1 border-b">{(["active", "processed", "duplicate", "failed", "all"] as RequestScanTab[]).map(value => <button key={value} className={`px-3 py-2 text-sm font-medium ${tab === value ? "border-b-2 border-teal-600" : ""}`} onClick={() => { setTab(value); setSelected([]); }}>{value === "failed" ? `Needs attention${status.data ? ` (${status.data.failed})` : ""}` : value[0].toUpperCase() + value.slice(1)}</button>)}</div><label className="text-sm">Attention stage <select className="input-premium ml-2" value={category} onChange={event => setCategory(event.target.value)}><option value="">All</option><option value="smb_storage">Archive error</option><option value="recognition">Recognition</option><option value="identifier_conflict">Unmatched appointment</option><option value="processing_interrupted">Interrupted processing</option></select></label></div>
    {status.data?.canRetryArchives && selectedArchive.length > 0 && <div className="flex items-center justify-between rounded-md border bg-muted/30 p-3 text-sm"><span>{selectedArchive.length} archive-pending documents selected</span><Button size="sm" onClick={() => setBulkConfirm(true)}>Retry selected archives</Button></div>}
    {jobs.isLoading ? <LoadingState /> : jobs.isError ? <ErrorState message={`Request Scans could not be loaded: ${jobs.error.message}`} /> : !visible.length ? <EmptyState message={tab === "active" ? "No active request scans. New scans and retries will appear here automatically." : "No request scans found for this view."} /> : <div className="overflow-x-auto rounded-lg border"><Table><TableHeader className="sticky top-0 bg-background"><TableRow><TableHead><input aria-label="Select archive-pending rows" type="checkbox" checked={visible.filter(archivePending).length > 0 && selectedArchive.length === visible.filter(archivePending).length} onChange={event => setSelected(event.target.checked ? visible.filter(archivePending).map(j => j.id) : [])} /></TableHead><TableHead>Time</TableHead><TableHead>Document</TableHead><TableHead>Accession</TableHead><TableHead>Patient</TableHead><TableHead>Examination</TableHead><TableHead>Processing result</TableHead><TableHead>Archive status</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{visible.map(job => <TableRow key={job.id}><TableCell>{archivePending(job) && <input aria-label={`Select ${job.filename}`} type="checkbox" checked={selected.includes(job.id)} onChange={event => setSelected(ids => event.target.checked ? [...ids, job.id] : ids.filter(id => id !== job.id))} />}</TableCell><TableCell>{date(job.created_at)}</TableCell><TableCell className="max-w-44 truncate" title={job.filename}>{job.filename}</TableCell><TableCell>{job.barcode_value || job.accession_number || "-"}</TableCell><TableCell><p className="font-medium">{job.patient_name || "Unconfirmed"}</p><p className="text-xs text-muted-foreground">{job.patient_mrn ? `MRN: ${job.patient_mrn}` : "No stable identifier"}{job.patient_date_of_birth ? ` · DOB: ${job.patient_date_of_birth}` : ""}</p></TableCell><TableCell><p>{[job.modality_name, job.exam_name].filter(Boolean).join(" · ") || "-"}</p><p className="text-xs text-muted-foreground">{job.appointment_date || ""}</p></TableCell><TableCell><ProcessingResult job={job} /></TableCell><TableCell><ArchiveStatus job={job} /></TableCell><TableCell><div className="flex flex-col items-start gap-1">{primary(job)}<details className="text-xs"><summary className="cursor-pointer text-muted-foreground">More</summary><div className="mt-1 flex flex-col items-start gap-1"><button onClick={() => void openPreview(job)}>Preview scanned document</button>{job.document_id && <a href={`/api/documents/${job.document_id}/view`} target="_blank" rel="noreferrer">View attached document</a>}{job.appointment_id && <button onClick={() => navigate(`/registrations?appointmentId=${job.appointment_id}`)}>Open appointment</button>}<span title={job.error_message || "No additional diagnostic"}>View processing details</span></div></details></div></TableCell></TableRow>)}</TableBody></Table></div>}
    <Dialog open={bulkConfirm} onClose={() => setBulkConfirm(false)}><DialogContent><DialogHeader><DialogTitle>Retry pending archives?</DialogTitle></DialogHeader><p className="text-sm">Retry archive transfer for {selectedArchive.length} documents? The already attached documents will not be duplicated.</p><DialogFooter><Button variant="secondary" onClick={() => setBulkConfirm(false)}>Cancel</Button><Button onClick={() => bulkRetry.mutate(selectedArchive.map(job => job.id))} disabled={!selectedArchive.length || bulkRetry.isPending}>Retry archive transfers</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(assign)} onClose={() => setAssign(null)}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Assign request scan to appointment</DialogTitle></DialogHeader>{assign && <div className="grid gap-4 md:grid-cols-2 text-sm"><section className="rounded border p-3"><h3 className="font-semibold">Detected/scanned information</h3><p className="mt-2">Filename: {assign.filename}</p><p>Barcode/accession: {assign.barcode_value || "Not detected"}</p><p>Detected patient: {assign.patient_name || "Not detected"}</p><p>Scanned: {date(assign.created_at)}</p><Button className="mt-3" size="sm" variant="secondary" onClick={() => void openPreview(assign)}>Preview scanned document</Button></section><section className="rounded border p-3"><h3 className="font-semibold">Selected RIS appointment</h3><input className="input-premium mt-2 w-full" placeholder="Search accession, MRN, or patient" value={query} onChange={event => setQuery(event.target.value)} /><select className="input-premium mt-2 w-full" value={appointmentId} onChange={event => setAppointmentId(event.target.value)}><option value="">Select appointment</option>{appointments.data?.appointments.map(item => <option key={item.id} value={item.id}>{item.accession_number} · {item.patient_name || "Patient"}</option>)}</select>{selectedAppointment && <div className="mt-3 space-y-1"><p>{selectedAppointment.patient_name}</p><p>MRN: {selectedAppointment.patient_mrn || "—"}</p><p>DOB: {selectedAppointment.patient_date_of_birth || "—"}</p><p>Accession: {selectedAppointment.accession_number}</p><p>{[selectedAppointment.modality_name, selectedAppointment.exam_name].filter(Boolean).join(" · ")}</p><p>{selectedAppointment.appointment_date}</p></div>}</section></div>}<label className="mt-4 flex gap-2 text-sm"><Checkbox checked={assignmentConfirmed} onCheckedChange={(checked) => setAssignmentConfirmed(Boolean(checked))} />I confirm that this scanned document belongs to the selected patient and appointment.</label><DialogFooter><Button variant="secondary" onClick={() => setAssign(null)}>Cancel</Button><Button disabled={!appointmentId || !assignmentConfirmed || assignMutation.isPending} onClick={() => assignMutation.mutate()}>Attach and process</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(preview)} onClose={() => { if (url.current) URL.revokeObjectURL(url.current); url.current = null; setPreviewUrl(null); setPreview(null); }}><DialogContent className="h-[90vh] max-w-5xl"><DialogHeader><DialogTitle>{preview?.filename}</DialogTitle></DialogHeader>{previewUrl && (preview?.filename.toLowerCase().endsWith(".pdf") ? <iframe className="h-full w-full" src={previewUrl} title="Request scan preview" /> : <img className="max-h-full max-w-full object-contain" src={previewUrl} alt={preview?.filename} />)}</DialogContent></Dialog>
  </main>;
}
