import { expect, test } from "@playwright/test";
import { signInWithSession } from "../helpers/auth.js";

test("SOP V1 library, bilingual authoring, publishing, revision, archive, and permissions", async ({ page }, testInfo) => {
  test.setTimeout(120_000);
  const pageErrors: string[] = [];
  const consoleErrors: string[] = [];
  page.on("pageerror", (error) => pageErrors.push(error.message));
  page.on("console", (message) => { if (message.type() === "error") consoleErrors.push(message.text()); });
  const screenshot = (name: string) => page.screenshot({ path: testInfo.outputPath(name), fullPage: false });
  const dismissToast = async () => {
    const close = page.getByRole("button", { name: /close/i });
    if (await close.count()) await close.last().click();
  };
  const noOverflow = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBeTruthy();
  const requiredEditors = () => page.locator(".ProseMirror");
  const code = `RAD-GEN-E2E-${Date.now().toString().slice(-6)}`;

  await signInWithSession(page, "e2e_supervisor");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/dashboard");
  const administration = page.getByRole("button", { name: "Administration", exact: true });
  if (await administration.isVisible()) await administration.click();
  await page.getByRole("button", { name: "SOP Library", exact: true }).click();
  await expect(page.getByRole("heading", { name: "SOP Library", exact: true })).toBeVisible();
  await expect(page.getByRole("textbox", { name: "Search SOPs" })).toBeVisible();
  await expect(page.getByRole("combobox", { name: "Category" })).toBeVisible();
  await expect(page.getByRole("combobox", { name: "Status" })).toBeVisible();
  await page.evaluate(() => window.scrollTo(0, 0));
  await dismissToast();
  await screenshot("01-sop-library-desktop.png");

  await page.getByRole("button", { name: "New SOP", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Create new SOP", exact: true })).toBeVisible();
  await expect(page.getByText("Purpose", { exact: true }).first()).toBeVisible();
  await expect(page.getByRole("button", { name: "Bold" }).first()).toBeVisible();
  await expect(page.getByRole("button", { name: "Insert table" }).first()).toBeVisible();
  await dismissToast();
  await screenshot("02-create-sop-editor-desktop.png");

  await page.getByRole("textbox", { name: "Title" }).fill("E2E General Safety");
  await page.getByRole("textbox", { name: "SOP Code" }).fill(code.toLowerCase());
  await page.getByRole("combobox", { name: "Category" }).selectOption("General");
  await page.locator("input[type='date']").fill("2026-10-15");
  await page.getByRole("textbox", { name: "Change summary" }).fill("Initial bilingual SOP");
  const editors = requiredEditors();
  await editors.nth(0).click();
  await page.keyboard.insertText("Purpose: protect patients and staff.");
  await editors.nth(1).click();
  await page.keyboard.insertText("Scope: all radiology examinations.");
  await editors.nth(2).click();
  await page.keyboard.insertText("Responsibilities: the radiology team.");
  await editors.nth(5).click();
  await page.getByRole("button", { name: "Numbered list" }).nth(5).click();
  await page.keyboard.insertText("Verify identity");
  await page.keyboard.press("Enter");
  await page.keyboard.insertText("Complete safety screening");
  await editors.nth(0).press("Control+A");
  await page.getByRole("button", { name: "Bold" }).first().click();
  await page.getByRole("button", { name: "Save Draft", exact: true }).click();
  await expect(page).toHaveURL(/\/sops\/\d+\?version=1\.0/);
  const sopPath = new URL(page.url()).pathname;
  await page.reload({ waitUntil: "domcontentloaded" });
  await expect(page.getByRole("heading", { name: /Edit draft/ })).toBeVisible();
  await expect(page.getByText("Purpose", { exact: true }).first()).toBeVisible();

  const arabicEditor = requiredEditors().nth(0);
  await arabicEditor.click();
  await arabicEditor.press("Control+A");
  await page.getByRole("button", { name: "RTL" }).first().click();
  await page.keyboard.insertText("\u0625\u062c\u0631\u0627\u0621\u0627\u062a \u0633\u0644\u0627\u0645\u0629 MRI");
  await dismissToast();
  await screenshot("03-arabic-rtl-editor-desktop.png");

  const englishEditor = requiredEditors().nth(1);
  await englishEditor.click();
  await englishEditor.press("Control+A");
  await page.getByRole("button", { name: "LTR" }).nth(1).click();
  await page.keyboard.insertText("Use MRI T1-weighted sequences when clinically indicated.");
  const mixedEditor = requiredEditors().nth(2);
  await mixedEditor.click();
  await mixedEditor.press("Control+A");
  await page.getByRole("button", { name: "RTL" }).nth(2).click();
  await page.keyboard.insertText("\u064a\u062c\u0628 \u0645\u0631\u0627\u062c\u0639\u0629 MRI protocol \u0642\u0628\u0644 \u0627\u0644\u0628\u062f\u0621.");
  await dismissToast();
  await screenshot("04-mixed-language-editor-desktop.png");
  const languageSave = page.waitForResponse((response) => response.request().method() === "PATCH" && response.url().includes("/api/sops/"));
  await page.getByRole("button", { name: "Save Draft", exact: true }).click();
  expect((await languageSave).status()).toBe(200);
  await page.reload({ waitUntil: "domcontentloaded" });
  await expect(requiredEditors().nth(0).locator("[dir='rtl']")).toBeVisible();

  await page.getByRole("button", { name: "Publish SOP", exact: true }).click();
  const publishDialog = page.getByRole("dialog");
  await expect(publishDialog).toContainText("Published versions cannot be edited directly.");
  await publishDialog.getByRole("button", { name: "Publish SOP", exact: true }).click();
  await expect(page.getByText("Published SOP", { exact: true })).toBeVisible();
  await expect(page.getByText(code, { exact: true })).toBeVisible();
  await expect(page.getByText("Version 1.0", { exact: true })).toBeVisible();
  await expect(page.getByTestId("sop-read-only-document")).toBeVisible();
  await page.evaluate(() => window.scrollTo(0, 0));
  await dismissToast();
  await screenshot("05-published-sop-desktop.png");

  await page.getByRole("button", { name: "Create New Revision", exact: true }).click();
  const revisionDialog = page.getByRole("dialog");
  await revisionDialog.getByRole("textbox", { name: "Change summary" }).fill("Clarified bilingual safety procedure");
  await revisionDialog.getByRole("textbox", { name: "Effective date" }).fill("2026-11-01");
  await revisionDialog.getByRole("button", { name: "Create draft revision", exact: true }).click();
  await expect(page).toHaveURL(/version=1\.1/);
  await expect(page.getByRole("heading", { name: /Edit draft/ })).toBeVisible();
  const revisionEditors = requiredEditors();
  await revisionEditors.nth(5).click();
  await revisionEditors.nth(5).press("Control+A");
  await page.keyboard.insertText("Updated procedure: verify, screen, document.");
  const revisionSave = page.waitForResponse((response) => response.request().method() === "PATCH" && response.url().includes("/api/sops/"));
  await page.getByRole("button", { name: "Save Draft", exact: true }).click();
  expect((await revisionSave).status()).toBe(200);

  await page.goto(`${sopPath}?version=1.0`);
  await expect(page.getByText("Published SOP", { exact: true })).toBeVisible();
  await expect(page.getByText("Read-only historical version", { exact: true })).toHaveCount(0);
  await page.goto(`${sopPath}?version=1.1`);
  await expect(page.getByRole("heading", { name: /Edit draft/ })).toBeVisible();
  await page.getByRole("button", { name: "Publish SOP", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Publish SOP", exact: true }).click();
  await expect(page.getByText("Version 1.1", { exact: true })).toBeVisible();
  await expect(page.getByText("Superseded", { exact: true })).toBeVisible();
  await page.getByRole("heading", { name: "Version history", exact: true }).scrollIntoViewIfNeeded();
  await dismissToast();
  await screenshot("06-version-history-desktop.png");
  await page.getByRole("button", { name: "Open", exact: true }).last().click();
  await expect(page.getByText("Read-only historical version", { exact: true })).toBeVisible();
  await expect(page.getByRole("toolbar", { name: "SOP formatting toolbar" })).toHaveCount(0);

  await signInWithSession(page, "e2e_reception");
  await page.goto(`${sopPath}?version=1.1`);
  await expect(page.getByText("Published SOP", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Create New Revision", exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Archive SOP", exact: true })).toHaveCount(0);
  await expect(page.getByTestId("sop-read-only-document")).toContainText("\u0625\u062c\u0631\u0627\u0621\u0627\u062a \u0633\u0644\u0627\u0645\u0629 MRI");
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await dismissToast();
  await screenshot("08-arabic-sop-mobile.png");
  const protectedResponse = await page.request.post(`http://127.0.0.1:3100/api/sops/${sopPath.split("/").at(-1)}/archive`, { data: {} });
  expect(protectedResponse.status()).toBe(403);

  await signInWithSession(page, "e2e_supervisor");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${sopPath}?version=1.1`);
  await page.getByRole("button", { name: "Archive SOP", exact: true }).click();
  const archiveDialog = page.getByRole("dialog");
  await expect(archiveDialog).toContainText("All published versions will be preserved.");
  await archiveDialog.getByRole("button", { name: "Archive SOP", exact: true }).click();
  await expect(page).toHaveURL(/\/sops$/);
  await expect(page.getByText(code, { exact: true })).toHaveCount(0);
  await page.getByRole("combobox", { name: "Status" }).selectOption("archived");
  await expect(page.getByText(code, { exact: true })).toBeVisible();
  await noOverflow();
  await dismissToast();
  await screenshot("07-sop-library-mobile.png");

  expect(pageErrors, `Unexpected page errors: ${pageErrors.join(" | ")}`).toEqual([]);
  expect(consoleErrors, `Unexpected console errors: ${consoleErrors.join(" | ")}`).toEqual([]);
});

test("SOP V1 hardening protects unsaved publish state, draft isolation, and dirty navigation", async ({ page }) => {
  test.setTimeout(120_000);
  const code = `RAD-HARD-E2E-${Date.now().toString().slice(-6)}`;
  const editors = () => page.locator(".ProseMirror");

  await signInWithSession(page, "e2e_supervisor");
  await page.goto("/sops/new");
  await expect(page.getByRole("heading", { name: "Create new SOP", exact: true })).toBeVisible();
  await page.getByRole("textbox", { name: "Title" }).fill("SOP Hardening Safety");
  await page.getByRole("textbox", { name: "SOP Code" }).fill(code);
  await page.getByRole("combobox", { name: "Category" }).selectOption("Patient Safety");
  await page.locator("input[type='date']").fill("2026-12-01");
  await page.getByRole("textbox", { name: "Change summary" }).fill("Hardening baseline");
  await editors().nth(0).click();
  await page.keyboard.insertText("Purpose baseline.");
  await editors().nth(1).click();
  await page.keyboard.insertText("Scope baseline.");
  await editors().nth(2).click();
  await page.keyboard.insertText("Responsibilities baseline.");
  await editors().nth(5).click();
  await page.keyboard.insertText("Procedure baseline.");
  await page.getByRole("button", { name: "Save Draft", exact: true }).click();
  await expect(page).toHaveURL(/\/sops\/\d+\?version=1\.0/);
  const sopPath = new URL(page.url()).pathname;
  await page.reload({ waitUntil: "domcontentloaded" });

  await editors().nth(0).click();
  await editors().nth(0).press("Control+A");
  await page.keyboard.insertText("Latest edit confirmed without manual save.");
  await page.getByRole("button", { name: "Publish SOP", exact: true }).click();
  const patchResponse = page.waitForResponse((response) => response.request().method() === "PATCH" && response.url().includes("/api/sops/"));
  const publishResponse = page.waitForResponse((response) => response.request().method() === "POST" && response.url().includes("/publish"));
  await page.getByRole("dialog").getByRole("button", { name: "Publish SOP", exact: true }).click();
  expect((await patchResponse).status()).toBe(200);
  expect((await publishResponse).status()).toBe(200);
  await expect(page.getByText("Published SOP", { exact: true })).toBeVisible();
  await expect(page.getByTestId("sop-read-only-document")).toContainText("Latest edit confirmed without manual save.");

  await page.getByRole("button", { name: "Create New Revision", exact: true }).click();
  const revisionDialog = page.getByRole("dialog");
  await revisionDialog.getByRole("textbox", { name: "Change summary" }).fill("Hardening revision");
  await revisionDialog.getByRole("textbox", { name: "Effective date" }).fill("2027-01-01");
  await revisionDialog.getByRole("button", { name: "Create draft revision", exact: true }).click();
  await expect(page).toHaveURL(/version=1\.1/);
  await expect(page.getByRole("heading", { name: /Edit draft/ })).toBeVisible();
  await expect(page.getByRole("textbox", { name: "Title" })).toHaveAttribute("readonly", "");
  await expect(page.getByRole("combobox", { name: "Category" })).toBeDisabled();

  const revisionEditor = editors().nth(5);
  await revisionEditor.click();
  await revisionEditor.press("Control+A");
  await page.keyboard.insertText("Unsaved revision edit preserved by guard.");
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  const guardDialog = page.getByRole("dialog");
  await expect(guardDialog).toContainText("SOP edits have not been saved.");
  await guardDialog.getByRole("button", { name: "Keep editing", exact: true }).click();
  await expect(revisionEditor).toContainText("Unsaved revision edit preserved by guard.");
  const revisionPatch = page.waitForResponse((response) => response.request().method() === "PATCH" && response.url().includes("/api/sops/"));
  await page.getByRole("button", { name: "Save Draft", exact: true }).click();
  expect((await revisionPatch).status()).toBe(200);
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(page.getByText("Published SOP", { exact: true })).toBeVisible();
  await expect(page.getByText("Version 1.0", { exact: true })).toBeVisible();

  await signInWithSession(page, "e2e_reception");
  await page.goto("/sops");
  const row = page.locator("tr").filter({ hasText: code });
  await expect(row).toContainText("1.0");
  await expect(row).not.toContainText("1.1");
  await row.getByRole("button", { name: "Open", exact: true }).click();
  await expect(page.getByText("Version 1.0", { exact: true })).toBeVisible();
  await expect(page.getByText("1.1", { exact: true })).toHaveCount(0);
  await expect(page.getByText("Unsaved revision edit preserved by guard.", { exact: true })).toHaveCount(0);
  await page.goto(`${sopPath}?version=1.1`);
  await expect(page.getByText("Version 1.0", { exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: /Edit draft/ })).toHaveCount(0);

  await signInWithSession(page, "e2e_supervisor");
  await page.goto(`${sopPath}?version=1.1`);
  await expect(page.getByRole("heading", { name: /Edit draft/ })).toBeVisible();
  await expect(page.getByTestId("sop-structured-editor")).toContainText("Unsaved revision edit preserved by guard.");
});
