import { formatDateLy } from "@/lib/date-format";
import { LIBYAN_CITIES } from "@/lib/libyan-cities";
import type { AppointmentWithDetails } from "@/lib/mappers";
import { filterVisibleAppointments } from "@/lib/print-utils";
import { directPrintRegistrationList } from "@/services/printing/direct-print-service";
import { resolveDirectPrintFailureAction } from "@/services/printing/direct-print-failure-action";
import { loadQzPrinterSettings } from "@/services/printing/workstation-printer-settings";
import { pushToast } from "@/lib/toast";
import { shouldUseBrowserPrint } from "@/services/printing/browser-printing";
import { t } from "@/lib/i18n";

function escapeHtml(value: unknown): string {
  return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export function prepareAppointmentListHtml(rows: AppointmentWithDetails[], label: string, generatedAt = new Date(), directPdf = false): string {
  const timestamp = generatedAt.toLocaleString();
  const renderedRows = rows.map((appointment, index) => `
    <div class="row"><div class="arabic"><div class="label">${index + 1}</div><div class="value">${appointment.dailySequence ?? "—"}</div></div>
      <div class="arabic"><div class="label">Patient</div><div class="value">${escapeHtml(appointment.arabicFullName)}</div><div class="meta">Age: ${escapeHtml(appointment.ageYears || "N/A")} | City: ${escapeHtml(appointment.address ? (LIBYAN_CITIES.find((city) => city.code === appointment.address)?.nameEn ?? appointment.address) : "N/A")}</div></div>
      <div><div class="label">Accession</div><div class="value">${escapeHtml(appointment.accessionNumber)}</div></div><div><div class="label">Date</div><div class="value">${escapeHtml(formatDateLy(appointment.appointmentDate))}</div></div>
      <div><div class="label">Modality</div><div class="value">${escapeHtml(appointment.modalityNameEn || "—")}</div></div><div><div class="label">Exam</div><div class="value">${escapeHtml(appointment.examNameEn || "—")}</div></div>
      <div><div class="label">Priority</div><div class="value">${escapeHtml(appointment.priorityNameEn || "Routine")}</div></div><div><div class="label">Status</div><div class="value">${escapeHtml(appointment.status || "—")}</div></div></div>`).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><title>Appointment List</title><style>
    @page { size: 297mm 210mm;${directPdf ? "" : " margin: 12mm;"} } * { box-sizing: border-box; }
    body { margin: 0; font-family: Arial, Helvetica, sans-serif; color: #111827; background: #fff; }
    .registration-list { width: 100%; min-height: 100%; }
    .header { display: flex; align-items: center; justify-content: center; gap: 12px; padding-bottom: 8px; margin-bottom: 8px; border-bottom: 1px solid #d1d5db; }
    .logo { width: 20mm; height: 20mm; object-fit: contain; flex: 0 0 auto; } .brand-wrap { text-align: center; }
    .brand { margin: 0; font-size: 17px; font-weight: 800; color: #0f766e; } .brand-ar { margin: 2px 0 0; font-size: 12px; font-weight: 700; color: #0f766e; direction: rtl; }
    .title { margin: 3px 0 0; font-size: 10px; color: #6b7280; text-transform: uppercase; letter-spacing: .14em; } .summary { margin: 0 0 8px; font-size: 10px; color: #374151; text-align: center; }
    .row { display: grid; grid-template-columns: 22mm 2fr 22mm 1fr 22mm 1.1fr 22mm 1.5fr; gap: 5px 7px; align-items: center; padding: 10px 12px; border-bottom: 1px solid #e5e7eb; font-size: 11px; break-inside: avoid; }
    .row:nth-child(odd) { background: #f8fafc; } .row:nth-child(even) { background: #eef6f5; } .label { font-size: 8.5px; color: #6b7280; text-transform: uppercase; letter-spacing: .05em; }
    .value { font-size: 11px; font-weight: 700; color: #111827; word-break: break-word; line-height: 1.25; } .meta { margin-top: 2px; font-size: 8.5px; color: #4b5563; line-height: 1.2; }
    .arabic { direction: rtl; text-align: right; } .footer { margin-top: 8px; padding-top: 8px; border-top: 1px dashed #d1d5db; display: flex; justify-content: space-between; gap: 12px; font-size: 8px; color: #6b7280; }
  </style></head><body><div class="registration-list" data-registration-list-document="true" data-direct-pdf="${directPdf}"><div class="header"><img class="logo" src="/assets/nccb-logo.png" alt="Hospital logo"><div class="brand-wrap"><p class="brand">National Cancer Center Benghazi</p><p class="brand-ar">المركز الوطني للأورام بنغازي</p><p class="title">Appointment List</p></div></div><p class="summary">Date window: ${escapeHtml(label)} · Total: ${rows.length} · Printed: ${escapeHtml(timestamp)}</p>${renderedRows}<div class="footer"><span>Generated by RISpro</span><span>${escapeHtml(timestamp)}</span></div></div></body></html>`;
}

export function printAppointmentListV2(rows: AppointmentWithDetails[], label: string): void {
  const visibleRows = filterVisibleAppointments(rows);
  if (visibleRows.length === 0) return;
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;
  printWindow.document.write(prepareAppointmentListHtml(visibleRows, label));
  printWindow.document.close();
  printWindow.focus();
  printWindow.print();
}

function printExactAppointmentList(rows: AppointmentWithDetails[], label: string): boolean {
  if (rows.length === 0) return false;
  const printWindow = window.open("", "_blank");
  if (!printWindow) return false;
  printWindow.document.write(prepareAppointmentListHtml(rows, label));
  printWindow.document.close();
  printWindow.focus();
  printWindow.print();
  return true;
}

function showBrowserPrintBlocked(language: "ar" | "en"): void {
  pushToast({ type: "error", title: t(language, "print.browserBlocked"), message: t(language, "print.browserBlockedMessage"), placement: "center" }, 10_000);
}

export async function directPrintRegistrationRows(rows: AppointmentWithDetails[], label: string): Promise<void> {
  if (rows.length === 0) return;
  const settings = loadQzPrinterSettings();
  if (shouldUseBrowserPrint(settings, "A4_LANDSCAPE_DOCUMENT")) {
    if (!printExactAppointmentList(rows, label)) showBrowserPrintBlocked(window.localStorage.getItem("rispro-language") === "ar" ? "ar" : "en");
    return;
  }
  const profile = settings.profiles?.find((candidate) => candidate.documentType === "A4_LANDSCAPE_DOCUMENT");
  if (profile && !profile.printerName.trim()) {
    const language = window.localStorage.getItem("rispro-language") === "ar" ? "ar" : "en";
    if (!printExactAppointmentList(rows, label)) { showBrowserPrintBlocked(language); return; }
    pushToast({ type: "error", title: t(language, "print.directUnavailable"), message: t(language, "print.directPrinterMissing"), placement: "center" }, 10_000);
    return;
  }
  const result = await directPrintRegistrationList(rows.map((row) => row.id), label);
  if (result.success) {
    pushToast({ type: "success", title: "Print job submitted", message: `Print job sent to ${result.printerName}.` });
    return;
  }
  const action = resolveDirectPrintFailureAction(result.errorCode, true, true);
  if (action === "BROWSER_PRINT") {
    const language = window.localStorage.getItem("rispro-language") === "ar" ? "ar" : "en";
    if (!printExactAppointmentList(rows, label)) { showBrowserPrintBlocked(language); return; }
    pushToast({
      type: "error",
      title: t(language, "print.directUnavailable"),
      message: result.errorCode === "PRINTER_NOT_CONFIGURED" ? t(language, "print.directPrinterMissing") : t(language, "print.browserFallbackOpened"),
      placement: "center",
    }, 10_000);
    return;
  }
  const toastAction = action === "OPEN_SETTINGS"
    ? { label: "Open Printing settings", onClick: () => window.location.assign("/workstation/printing") }
    : null;
  pushToast({ type: "error", title: "Print failed", message: result.message, ...(toastAction ? { action: toastAction } : {}) }, 10_000);
}
